#!/usr/bin/env bash
# Shared plumbing for the #3217 WS0 full-box C(N) + attribution harness.
# Sourced by sweep.sh / profile-oncpu.sh / profile-offcpu.sh. Never run directly.
#
# Everything here is deliberately explicit about the two traps that have already
# burned this program:
#   1. kernel.perf_event_paranoid / kptr_restrict SILENTLY REVERT to 4 / 1.
#      => ws0_assert_sysctl at the start of EVERY script, every time.
#   2. `pkill -f 'cqlite-flight --data-dir'` MATCHES AND KILLS THE LAUNCHING SHELL.
#      => ws0_stop_server takes an explicit PID. There is no pkill -f anywhere.

set -euo pipefail

# ---------------------------------------------------------------- paths / env
WS0_ROOT="${WS0_ROOT:-/data/ws0}"
WS0_LOGS="${WS0_LOGS:-$WS0_ROOT/logs}"
WS0_RESULTS="${WS0_RESULTS:-$WS0_ROOT/results}"
WS0_PROFILES="${WS0_PROFILES:-$WS0_ROOT/profiles}"
WS0_ARTIFACTS="${WS0_ARTIFACTS:-$WS0_ROOT/artifacts}"
FLAMEGRAPH_DIR="${FLAMEGRAPH_DIR:-$WS0_ROOT/tools/FlameGraph}"
HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The three inputs that are NEVER hardcoded (corpus is generated by a peer agent;
# the binaries live in the issue worktree's target/release).
WS0_STAGE="${WS0_STAGE:-}"            # staged SSTable dir  (--data-dir)
WS0_FLIGHT_BIN="${WS0_FLIGHT_BIN:-}"  # cqlite-flight binary
WS0_LOADGEN_BIN="${WS0_LOADGEN_BIN:-}"# flight-loadgen binary
WS0_TICKET_TPL="${WS0_TICKET_TPL:-}"  # --ticket-template JSON

WS0_LISTEN_HOST="${WS0_LISTEN_HOST:-127.0.0.1}"
WS0_LISTEN_PORT="${WS0_LISTEN_PORT:-8815}"
WS0_ENDPOINT="http://${WS0_LISTEN_HOST}:${WS0_LISTEN_PORT}"

# Server flags — verbatim from the #3100 recorded invocation so a S=1 run is a
# like-for-like reproduction of that control.
WS0_BATCH_SIZE="${WS0_BATCH_SIZE:-8192}"
WS0_MAX_BATCH_BYTES="${WS0_MAX_BATCH_BYTES:-4194304}"
WS0_MAX_INFLIGHT_EGRESS_BYTES="${WS0_MAX_INFLIGHT_EGRESS_BYTES:-12582912}"
WS0_MAX_CONCURRENT_SCANS="${WS0_MAX_CONCURRENT_SCANS:-16}"
WS0_ADMISSION_WAIT_TIMEOUT_MS="${WS0_ADMISSION_WAIT_TIMEOUT_MS:-30000}"
WS0_SEED="${WS0_SEED:-42}"

# Validity gate (AC1/AC2): above this client-pinned-set utilisation the point
# measured the CLIENT, not the engine.
WS0_CLIENT_SAT_THRESHOLD="${WS0_CLIENT_SAT_THRESHOLD:-0.70}"
# AC3: unsymbolized frames must stay under this fraction of samples.
WS0_UNSYM_THRESHOLD="${WS0_UNSYM_THRESHOLD:-0.10}"

# --------------------------------------------------------------------- output
ws0_log()  { printf '[%s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
ws0_die()  { printf '[%s] ERROR: %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; exit 1; }
ws0_warn() { printf '[%s] WARN: %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }

# ------------------------------------------------------- TRAP 1: sysctl revert
# kernel.perf_event_paranoid and kernel.kptr_restrict revert to 4 / 1 on this box
# on their own schedule. Re-assert unconditionally; a stale value silently
# produces unsymbolized kernel frames (blowing AC3) or refuses -C profiling.
ws0_assert_sysctl() {
  local want_paranoid=-1 want_kptr=0 p k
  sudo -n sysctl -q -w kernel.perf_event_paranoid=$want_paranoid \
                       kernel.kptr_restrict=$want_kptr >/dev/null 2>&1 || true
  p=$(cat /proc/sys/kernel/perf_event_paranoid)
  k=$(cat /proc/sys/kernel/kptr_restrict)
  [ "$p" = "$want_paranoid" ] || ws0_die "perf_event_paranoid=$p (want $want_paranoid); sudo sysctl -w failed"
  [ "$k" = "$want_kptr" ]     || ws0_die "kptr_restrict=$k (want $want_kptr); sudo sysctl -w failed"
  ws0_log "sysctl asserted: perf_event_paranoid=$p kptr_restrict=$k"
}

# --------------------------------------------------------- CPU topology (AC2)
# VERIFIED from /sys, never assumed. Writes an artefact and exports
# WS0_SIBLING_PAIRS / WS0_TOPOLOGY_JSON.
ws0_verify_topology() {
  local out="${1:-$WS0_ARTIFACTS/cpu-topology.json}"
  mkdir -p "$(dirname "$out")"
  python3 - "$out" <<'PY'
import glob, json, os, re, sys
out = sys.argv[1]
cores = {}
for path in sorted(glob.glob('/sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list')):
    cpu = int(re.search(r'cpu(\d+)', path).group(1))
    sibs = []
    for part in open(path).read().strip().split(','):
        if '-' in part:
            a, b = part.split('-'); sibs += list(range(int(a), int(b) + 1))
        else:
            sibs.append(int(part))
    core = int(open(path.replace('thread_siblings_list', 'core_id')).read())
    pkg_p = path.replace('thread_siblings_list', 'physical_package_id')
    pkg = int(open(pkg_p).read()) if os.path.exists(pkg_p) else 0
    cores.setdefault((pkg, core), set()).update(sibs)
pairs = sorted(tuple(sorted(v)) for v in cores.values())
model = ''
for line in open('/proc/cpuinfo'):
    if line.startswith('model name'):
        model = line.split(':', 1)[1].strip(); break
nodes = sorted(os.path.basename(p) for p in glob.glob('/sys/devices/system/node/node[0-9]*'))
doc = {
    "source": "/sys/devices/system/cpu/cpu*/topology/thread_siblings_list (read, not assumed)",
    "model_name": model,
    "logical_cpus": len(glob.glob('/sys/devices/system/cpu/cpu[0-9]*/topology')),
    "physical_cores": len(pairs),
    "numa_nodes": nodes,
    "smt_sibling_pairs": [list(p) for p in pairs],
    "sibling_pair_rule_observed": "(c, c+8)" if all(
        len(p) == 2 and p[1] - p[0] == 8 for p in pairs) else "NON-UNIFORM - read pairs explicitly",
    "kernel": open('/proc/sys/kernel/osrelease').read().strip(),
}
open(out, 'w').write(json.dumps(doc, indent=1) + "\n")
print(doc["sibling_pair_rule_observed"])
PY
  WS0_TOPOLOGY_JSON="$out"; export WS0_TOPOLOGY_JSON
  ws0_log "topology verified -> $out"
}

# ------------------------------------------------- server-core set table (AC2)
# TABLE-DRIVEN, not inlined in the flow. Each S uses BOTH SMT siblings of S
# physical cores. S=1 -> "2,10" reproduces #3100's pinned control exactly.
# Client is fixed at 2 physical cores (6,7 + siblings 14,15) for every S so the
# client side is a constant across the curve.
ws0_server_cpus_for_s() {
  case "$1" in
    1) echo "2,10" ;;
    2) echo "0,2,8,10" ;;
    4) echo "0-3,8-11" ;;
    6) echo "0-5,8-13" ;;
    *) ws0_die "no server-cpu set defined for S=$1 (known: 1 2 4 6)" ;;
  esac
}
WS0_CLIENT_CPUS_DEFAULT="6,7,14,15"

# Expand "0-3,8-11" -> count of logical CPUs.
ws0_cpulist_count() {
  python3 -c '
import sys
n=0
for part in sys.argv[1].split(","):
    if "-" in part:
        a,b=part.split("-"); n+=int(b)-int(a)+1
    else:
        n+=1
print(n)' "$1"
}
ws0_cpulist_expand() {
  python3 -c '
import sys
o=[]
for part in sys.argv[1].split(","):
    if "-" in part:
        a,b=part.split("-"); o+=list(range(int(a),int(b)+1))
    else:
        o.append(int(part))
print(",".join(str(x) for x in sorted(set(o))))' "$1"
}

# ------------------------------------------------------------ input validation
ws0_require_inputs() {
  [ -n "$WS0_STAGE" ]       || ws0_die "WS0_STAGE unset (staged SSTable dir; corpus is generated by a peer agent, never hardcoded)"
  [ -d "$WS0_STAGE" ]       || ws0_die "WS0_STAGE=$WS0_STAGE is not a directory"
  [ -n "$WS0_FLIGHT_BIN" ]  || ws0_die "WS0_FLIGHT_BIN unset (path to cqlite-flight)"
  [ -x "$WS0_FLIGHT_BIN" ]  || ws0_die "WS0_FLIGHT_BIN=$WS0_FLIGHT_BIN is not executable"
  [ -n "$WS0_LOADGEN_BIN" ] || ws0_die "WS0_LOADGEN_BIN unset (path to flight-loadgen)"
  [ -x "$WS0_LOADGEN_BIN" ] || ws0_die "WS0_LOADGEN_BIN=$WS0_LOADGEN_BIN is not executable"
  [ -n "$WS0_TICKET_TPL" ]  || ws0_die "WS0_TICKET_TPL unset (--ticket-template JSON)"
  [ -f "$WS0_TICKET_TPL" ]  || ws0_die "WS0_TICKET_TPL=$WS0_TICKET_TPL not found"
  ls "$WS0_STAGE"/*Data.db >/dev/null 2>&1 || \
    ls "$WS0_STAGE"/*/*Data.db >/dev/null 2>&1 || \
    ws0_warn "no *-Data.db directly under $WS0_STAGE — check the stage layout"
}

# ------------------------------------------------------------ server lifecycle
# ws0_start_server <server-cpu-list> <merge-path: bypass|merge> <log-file>
# Exports WS0_SERVER_PID. Blocks until the port answers (<=60s) or dies.
ws0_start_server() {
  local cpus="$1" merge_path="$2" logfile="$3"
  mkdir -p "$(dirname "$logfile")"
  ws0_log "starting cqlite-flight on cpus=$cpus merge_path=$merge_path"
  CQLITE_FLIGHT_MERGE_PATH="$merge_path" \
  taskset -c "$cpus" "$WS0_FLIGHT_BIN" \
      --data-dir "$WS0_STAGE" \
      --listen "${WS0_LISTEN_HOST}:${WS0_LISTEN_PORT}" \
      --batch-size "$WS0_BATCH_SIZE" \
      --max-batch-bytes "$WS0_MAX_BATCH_BYTES" \
      --max-inflight-egress-bytes "$WS0_MAX_INFLIGHT_EGRESS_BYTES" \
      --max-concurrent-scans "$WS0_MAX_CONCURRENT_SCANS" \
      --admission-wait-timeout-ms "$WS0_ADMISSION_WAIT_TIMEOUT_MS" \
      >"$logfile" 2>&1 &
  WS0_SERVER_PID=$!
  export WS0_SERVER_PID
  local i
  for i in $(seq 1 60); do
    if ! kill -0 "$WS0_SERVER_PID" 2>/dev/null; then
      ws0_die "cqlite-flight (pid $WS0_SERVER_PID) died during startup; see $logfile"
    fi
    if (echo >"/dev/tcp/${WS0_LISTEN_HOST}/${WS0_LISTEN_PORT}") 2>/dev/null; then
      ws0_log "server ready pid=$WS0_SERVER_PID after ${i}s"
      return 0
    fi
    sleep 1
  done
  ws0_stop_server
  ws0_die "server did not accept on ${WS0_LISTEN_HOST}:${WS0_LISTEN_PORT} within 60s; see $logfile"
}

# TRAP 2: explicit PID only. `pkill -f 'cqlite-flight --data-dir'` matches the
# launching shell's own command line and kills the harness. Never use it.
ws0_stop_server() {
  local pid="${1:-${WS0_SERVER_PID:-}}"
  [ -n "$pid" ] || return 0
  kill -0 "$pid" 2>/dev/null || { unset WS0_SERVER_PID || true; return 0; }
  ws0_log "stopping server pid=$pid"
  kill -TERM "$pid" 2>/dev/null || true
  local i
  for i in $(seq 1 15); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
  kill -0 "$pid" 2>/dev/null && kill -9 "$pid" 2>/dev/null || true
  wait "$pid" 2>/dev/null || true
  unset WS0_SERVER_PID || true
}

# ------------------------------------------------------------- counter helpers
# CPU seconds consumed by a pid (utime+stime), from /proc/<pid>/stat fields 14,15.
ws0_proc_cpu_secs() {
  local pid="$1"
  awk -v hz="$(getconf CLK_TCK)" '{print ($14+$15)/hz}' "/proc/$pid/stat" 2>/dev/null || echo 0
}
# /proc/<pid>/io as compact JSON. rchar / read_bytes / syscr are reported
# SEPARATELY and are NEVER divided by one another (different units, different
# layers) — see README.
ws0_proc_io_json() {
  local pid="$1"
  python3 -c '
import json,sys
d={}
try:
    for line in open("/proc/%s/io"%sys.argv[1]):
        k,v=line.split(":"); d[k.strip()]=int(v)
except OSError: pass
print(json.dumps(d))' "$pid"
}
# voluntary / nonvoluntary context switches from /proc/<pid>/status (AC5).
ws0_proc_ctxt_json() {
  local pid="$1"
  python3 -c '
import json,sys
d={}
try:
    for line in open("/proc/%s/status"%sys.argv[1]):
        if line.startswith(("voluntary_ctxt_switches","nonvoluntary_ctxt_switches")):
            k,v=line.split(":"); d[k.strip()]=int(v)
except OSError: pass
print(json.dumps(d))' "$pid"
}
# Aggregate CPU busy seconds over a CPU list, from /proc/stat (used for the
# CLIENT-set utilisation validity gate, which must not depend on knowing the
# client's pid tree).
ws0_cpuset_busy_secs() {
  python3 -c '
import sys
want=set()
for part in sys.argv[1].split(","):
    if "-" in part:
        a,b=part.split("-"); want|=set(range(int(a),int(b)+1))
    else:
        want.add(int(part))
hz=100.0
tot=0.0
for line in open("/proc/stat"):
    f=line.split()
    if not f or not f[0].startswith("cpu") or f[0]=="cpu": continue
    try: n=int(f[0][3:])
    except ValueError: continue
    if n not in want: continue
    v=[int(x) for x in f[1:11]]
    idle=v[3]+v[4]           # idle + iowait
    tot += (sum(v)-idle)/hz
print(tot)' "$1"
}

# Best-effort page-cache warm pre-pass. This is a CPU measurement; a cold read
# would attribute page-fault/IO stalls to the engine.
ws0_warm_prepass() {
  local client_cpus="$1" secs="${2:-45}" logfile="$3"
  ws0_log "warm pre-pass ${secs}s (page cache)"
  taskset -c "$client_cpus" "$WS0_LOADGEN_BIN" \
      --endpoint "$WS0_ENDPOINT" --ticket-template "$WS0_TICKET_TPL" \
      --shape full --ramp 1 --step-duration "${secs}s" --seed "$WS0_SEED" \
      --round prewarm --out /dev/null >"$logfile" 2>&1 || \
    ws0_warn "warm pre-pass returned non-zero (see $logfile) — continuing"
}
