//! Regeneration of the components that are PURE functions of `Data.db`'s
//! existing bytes (`Digest.crc32`, `CRC.db`), plus the copy-untouched +
//! `TOC.txt` publication-barrier machinery shared by every rebuild run
//! (design D2/D5, R1).

use crate::error::{Error, Result};
use crate::storage::sstable::directory::types::SSTableComponent;
use crate::storage::sstable::writer::crc_writer::{
    assemble_crc_bytes, CrcTrailer, StreamingCrc, CRC_CHUNK_SIZE,
};
use crate::storage::sstable::writer::digest_writer::DigestWriter;
use crate::storage::sstable::writer::toc_writer::{ComponentEntry, TocWriter};
use std::io::Read;
use std::path::{Path, PathBuf};

/// Regenerate `Digest.crc32` — a pure function of `Data.db`'s (unchanged)
/// bytes (design D2's `always yes`; spec R1.1).
pub(super) fn write_digest(data_db_path: &Path, out_dir: &Path, base: &str) -> Result<()> {
    let crc32 = DigestWriter::compute_crc32(&data_db_path.to_path_buf())?;
    let digest_path = out_dir.join(format!("{base}-Digest.crc32"));
    DigestWriter::new(digest_path).write(crc32)
}

/// Regenerate `CRC.db` (uncompressed BIG only) by re-reading `Data.db` in
/// [`CRC_CHUNK_SIZE`] chunks (design D2's `always yes` for uncompressed BIG
/// input; spec R1.1).
///
/// # Declared gap: the flush-vs-compaction trailer (issue #1222)
///
/// Cassandra's compaction write path appends one trailing empty-final-chunk
/// `CRC32 = 0` group that the flush path does not (`crc_writer.rs` module
/// doc). Rebuild has no persisted signal distinguishing a flush-produced
/// `Data.db` from a compaction-produced one — Statistics.db does not record
/// this either — so it ALWAYS assumes [`CrcTrailer::None`] (the flush
/// convention). This is correct for every flush-produced input (the common
/// case, and every committed test fixture); a compaction-produced
/// uncompressed `Data.db`'s rebuilt `CRC.db` will differ from the original
/// by exactly one trailing `00000000` group until a detection mechanism is
/// added (tracked as follow-up work under epic #4192, alongside the
/// `min_index_interval` gap this change also declares rather than silently
/// getting wrong).
pub(super) fn write_crc(data_db_path: &Path, out_dir: &Path, base: &str) -> Result<()> {
    let mut file = std::fs::File::open(data_db_path)
        .map_err(|e| Error::Io(std::io::Error::new(e.kind(), format!("Data.db: {e}"))))?;
    let mut crc = StreamingCrc::new();
    let mut buffer = vec![0u8; CRC_CHUNK_SIZE];
    loop {
        let n = file.read(&mut buffer)?;
        if n == 0 {
            break;
        }
        crc.update(&buffer[..n]);
    }
    let (_, chunk_crcs) = crc.finalize();
    let bytes = assemble_crc_bytes(&chunk_crcs, CrcTrailer::None);
    let crc_path = out_dir.join(format!("{base}-CRC.db"));
    std::fs::write(&crc_path, bytes)?;
    Ok(())
}

/// Copy every component present in `dir` under the `{base}-` prefix that
/// [`will_regenerate`] does NOT claim, verbatim (byte-for-byte, read-only on
/// the source) into `out_dir` — so a rebuild run into `--out` produces a
/// COMPLETE, self-contained generation directory (Data.db + every existing
/// derived component + the freshly regenerated ones), never a directory
/// holding only the requested subset (spec R7.1/R10: the output must pass
/// `verify --mode full` and serve reads end-to-end).
///
/// `will_regenerate` decides PER COMPONENT (including `TOC` itself) whether
/// the caller is about to write a fresh copy — that component is left
/// alone here (never shadowed with a stale copy first); everything else
/// present under the `{base}-` prefix is copied verbatim, `TOC.txt`
/// included when the caller is NOT rebuilding it (a rebuild run that does
/// not request `toc` must not silently drop an otherwise-healthy original).
///
/// Returns the set of [`SSTableComponent`]s now known to be present in
/// `out_dir` (copied here, or already regenerated by an earlier step) so the
/// caller can build the final `TOC.txt` listing.
pub(super) fn copy_untouched_components(
    dir: &Path,
    out_dir: &Path,
    base: &str,
    will_regenerate: impl Fn(SSTableComponent) -> bool,
) -> Result<Vec<SSTableComponent>> {
    let mut present = Vec::new();
    let prefix = format!("{base}-");
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        let Some(suffix) = name.strip_prefix(&prefix) else {
            continue;
        };
        let Ok(component) = suffix.parse::<SSTableComponent>() else {
            continue;
        };
        if will_regenerate(component.clone()) {
            // Will be written fresh by the caller; do not shadow it with a
            // stale copy first.
            present.push(component);
            continue;
        }
        std::fs::copy(entry.path(), out_dir.join(name))?;
        present.push(component);
    }
    Ok(present)
}

/// Write the final `TOC.txt` — the publication barrier, always written
/// LAST, after every other requested component (design D2/D4).
pub(super) fn write_toc(out_dir: &Path, base: &str, present: &[SSTableComponent]) -> Result<()> {
    let entries: Vec<ComponentEntry> = present.iter().cloned().map(ComponentEntry::new).collect();
    let toc_path: PathBuf = out_dir.join(format!("{base}-TOC.txt"));
    TocWriter::new(toc_path).write(&entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn copy_untouched_components_skips_only_what_will_regenerate() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("in");
        let out = tmp.path().join("out");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::create_dir_all(&out).unwrap();
        std::fs::write(dir.join("nb-1-big-Data.db"), b"data").unwrap();
        std::fs::write(dir.join("nb-1-big-Statistics.db"), b"stats").unwrap();
        std::fs::write(dir.join("nb-1-big-TOC.txt"), b"Data.db\n").unwrap();

        let present = copy_untouched_components(&dir, &out, "nb-1-big", |c| {
            c == SSTableComponent::Statistics
        })
        .unwrap();

        assert!(out.join("nb-1-big-Data.db").exists());
        assert!(
            !out.join("nb-1-big-Statistics.db").exists(),
            "a component claimed by `will_regenerate` must not be copied"
        );
        assert!(
            out.join("nb-1-big-TOC.txt").exists(),
            "TOC.txt not claimed by `will_regenerate` (the caller isn't rebuilding `toc`) must \
             still be preserved verbatim, not silently dropped"
        );
        assert!(present.contains(&SSTableComponent::Data));
        assert!(present.contains(&SSTableComponent::Statistics));
        assert!(present.contains(&SSTableComponent::TOC));
    }

    #[test]
    fn copy_untouched_components_skips_toc_when_it_will_be_rebuilt() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("in");
        let out = tmp.path().join("out");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::create_dir_all(&out).unwrap();
        std::fs::write(dir.join("nb-1-big-Data.db"), b"data").unwrap();
        std::fs::write(dir.join("nb-1-big-TOC.txt"), b"Data.db\n").unwrap();

        let present =
            copy_untouched_components(&dir, &out, "nb-1-big", |c| c == SSTableComponent::TOC)
                .unwrap();

        assert!(
            !out.join("nb-1-big-TOC.txt").exists(),
            "a stale TOC.txt must not survive when the caller is about to write a fresh one"
        );
        assert!(present.contains(&SSTableComponent::TOC));
    }
}
