#!/usr/bin/env bash
# Shared plumbing for the #3217 WS0 full-box C(N) + attribution harness.
# Sourced by sweep.sh / profile-oncpu.sh / profile-offcpu.sh. Never run directly.
#
# Everything here is deliberately explicit about the two traps that have already
# burned this program:
#   1. kernel.perf_event_paranoid / kptr_restrict SILENTLY REVERT to 4 / 1.
#      => ws0_assert_sysctl at the start of EVERY script, every time.
#   2. `pkill -f 'cqlite-flight --data-dir'` MATCHES AND KILLS THE LAUNCHING SHELL.
#      => ws0_stop_server takes an explicit PID. There is no pkill -f anywhere.

set -euo pipefail

# ---------------------------------------------------------------- paths / env
WS0_ROOT="${WS0_ROOT:-/data/ws0}"
WS0_LOGS="${WS0_LOGS:-$WS0_ROOT/logs}"
WS0_RESULTS="${WS0_RESULTS:-$WS0_ROOT/results}"
WS0_PROFILES="${WS0_PROFILES:-$WS0_ROOT/profiles}"
WS0_ARTIFACTS="${WS0_ARTIFACTS:-$WS0_ROOT/artifacts}"
FLAMEGRAPH_DIR="${FLAMEGRAPH_DIR:-$WS0_ROOT/tools/FlameGraph}"
HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The three inputs that are NEVER hardcoded (corpus is generated by a peer agent;
# the binaries live in the issue worktree's target/release).
WS0_STAGE="${WS0_STAGE:-}"            # staged SSTable dir  (--data-dir)
WS0_FLIGHT_BIN="${WS0_FLIGHT_BIN:-}"  # cqlite-flight binary
WS0_LOADGEN_BIN="${WS0_LOADGEN_BIN:-}" # flight-loadgen binary
WS0_TICKET_TPL="${WS0_TICKET_TPL:-}"  # --ticket-template JSON

WS0_LISTEN_HOST="${WS0_LISTEN_HOST:-127.0.0.1}"
WS0_LISTEN_PORT="${WS0_LISTEN_PORT:-8815}"
WS0_ENDPOINT="http://${WS0_LISTEN_HOST}:${WS0_LISTEN_PORT}"

# Server flags — verbatim from the #3100 recorded invocation so a S=1 run is a
# like-for-like reproduction of that control.
WS0_BATCH_SIZE="${WS0_BATCH_SIZE:-8192}"
WS0_MAX_BATCH_BYTES="${WS0_MAX_BATCH_BYTES:-4194304}"
WS0_MAX_INFLIGHT_EGRESS_BYTES="${WS0_MAX_INFLIGHT_EGRESS_BYTES:-12582912}"
WS0_MAX_CONCURRENT_SCANS="${WS0_MAX_CONCURRENT_SCANS:-16}"
WS0_ADMISSION_WAIT_TIMEOUT_MS="${WS0_ADMISSION_WAIT_TIMEOUT_MS:-30000}"
WS0_SEED="${WS0_SEED:-42}"

# Validity gate (AC1/AC2): above this client-pinned-set utilisation the point
# measured the CLIENT, not the engine.
WS0_CLIENT_SAT_THRESHOLD="${WS0_CLIENT_SAT_THRESHOLD:-0.70}"
# Minimum busy fraction for an occupancy arm (roborev round 4 finding #1). Guards
# against IDLE PERIODS inside a step, which would break the interior convention's
# assumption that whole-step throughput represents the interior perf window. Low by
# design: the estimate is a product of three measured quantities and carries their
# combined error, so a tight floor would be a false-FAIL generator. Committed reps
# land at ~0.99.
WS0_BUSY_FRACTION_FLOOR="${WS0_BUSY_FRACTION_FLOOR:-0.90}"
# AC3: unsymbolized frames must stay under this fraction of samples.
WS0_UNSYM_THRESHOLD="${WS0_UNSYM_THRESHOLD:-0.10}"

# --------------------------------------------------------------------- output
ws0_log()  { printf '[%s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
ws0_die()  { printf '[%s] ERROR: %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; exit 1; }
ws0_warn() { printf '[%s] WARN: %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }

# ------------------------------------------------------- TRAP 1: sysctl revert
# kernel.perf_event_paranoid and kernel.kptr_restrict revert to 4 / 1 on this box
# on their own schedule. Re-assert unconditionally; a stale value silently
# produces unsymbolized kernel frames (blowing AC3) or refuses -C profiling.
ws0_assert_sysctl() {
  local want_paranoid=-1 want_kptr=0 p k
  sudo -n sysctl -q -w kernel.perf_event_paranoid=$want_paranoid \
                       kernel.kptr_restrict=$want_kptr >/dev/null 2>&1 || true
  p=$(cat /proc/sys/kernel/perf_event_paranoid)
  k=$(cat /proc/sys/kernel/kptr_restrict)
  [ "$p" = "$want_paranoid" ] || ws0_die "perf_event_paranoid=$p (want $want_paranoid); sudo sysctl -w failed"
  [ "$k" = "$want_kptr" ]     || ws0_die "kptr_restrict=$k (want $want_kptr); sudo sysctl -w failed"
  ws0_log "sysctl asserted: perf_event_paranoid=$p kptr_restrict=$k"
}

# --------------------------------------------------------- CPU topology (AC2)
# VERIFIED from /sys, never assumed. Writes an artefact and exports
# WS0_SIBLING_PAIRS / WS0_TOPOLOGY_JSON.
ws0_verify_topology() {
  local out="${1:-$WS0_ARTIFACTS/cpu-topology.json}"
  mkdir -p "$(dirname "$out")"
  python3 - "$out" <<'PY'
import glob, json, os, re, sys
out = sys.argv[1]
cores = {}
for path in sorted(glob.glob('/sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list')):
    cpu = int(re.search(r'cpu(\d+)', path).group(1))
    sibs = []
    for part in open(path).read().strip().split(','):
        if '-' in part:
            a, b = part.split('-'); sibs += list(range(int(a), int(b) + 1))
        else:
            sibs.append(int(part))
    core = int(open(path.replace('thread_siblings_list', 'core_id')).read())
    pkg_p = path.replace('thread_siblings_list', 'physical_package_id')
    pkg = int(open(pkg_p).read()) if os.path.exists(pkg_p) else 0
    cores.setdefault((pkg, core), set()).update(sibs)
pairs = sorted(tuple(sorted(v)) for v in cores.values())
model = ''
for line in open('/proc/cpuinfo'):
    if line.startswith('model name'):
        model = line.split(':', 1)[1].strip(); break
nodes = sorted(os.path.basename(p) for p in glob.glob('/sys/devices/system/node/node[0-9]*'))
doc = {
    "source": "/sys/devices/system/cpu/cpu*/topology/thread_siblings_list (read, not assumed)",
    "model_name": model,
    "logical_cpus": len(glob.glob('/sys/devices/system/cpu/cpu[0-9]*/topology')),
    "physical_cores": len(pairs),
    "numa_nodes": nodes,
    "smt_sibling_pairs": [list(p) for p in pairs],
    # #3217 hardcoded the string "(c, c+8)" here and only tested offset 8, so on
    # THIS box (offset 64) it would have reported "NON-UNIFORM" — true but
    # useless, and it hid that the offset is uniform at a DIFFERENT value.
    # Derive the offset instead of testing for one.
    "sibling_pair_rule_observed": (
        "(c, c+%d)" % (pairs[0][1] - pairs[0][0])
        if pairs and all(len(p) == 2 for p in pairs)
        and len({p[1] - p[0] for p in pairs}) == 1
        else "NON-UNIFORM - read pairs explicitly"),
    "numa_node_cpulists": {
        os.path.basename(p): open(os.path.join(p, 'cpulist')).read().strip()
        for p in sorted(glob.glob('/sys/devices/system/node/node[0-9]*'))
        if os.path.exists(os.path.join(p, 'cpulist'))},
    "kernel": open('/proc/sys/kernel/osrelease').read().strip(),
}
open(out, 'w').write(json.dumps(doc, indent=1) + "\n")
print(doc["sibling_pair_rule_observed"])
PY
  WS0_TOPOLOGY_JSON="$out"; export WS0_TOPOLOGY_JSON
  ws0_log "topology verified -> $out"
}

# ------------------------------------------------- server-core set table (AC2)
# ############################################################################
# ## REWRITTEN FOR THE #3224 HOST. #3217's TABLE IS WRONG HERE. ##
# ############################################################################
#
# #3217's host: 16 logical CPUs, sibling pairs (c, c+8), ONE NUMA node. Its
# table was  1)"2,10"  2)"0,2,8,10"  4)"0-3,8-11"  6)"0-5,8-13", client
# "6,7,14,15".
#
# THIS host (i4i.metal, Xeon Platinum 8375C, Ice Lake-SP): 128 logical CPUs,
# 64 physical, 2 sockets, **2 NUMA nodes**, and sibling pairs are
# **(c, c+64)** — read from sysfs, see host/thread-siblings.txt:
#
#     cpu0 -> 0,64     cpu1 -> 1,65     cpu2 -> 2,66     ...
#     node0 = CPUs 0-31,64-95        node1 = CPUs 32-63,96-127
#
# So EVERY set in #3217's table is wrong here in two independent ways: the
# sibling offset is 64 not 8 (so "2,10" pins two DIFFERENT physical cores
# instead of one core's two threads), and nothing constrains the set to one
# socket. `selftest.sh` CANNOT catch this — it verifies the topology
# *derivation*, not this hardcoded table.
#
# Three rules, per RUNBOOK step 3:
#   1. Both SMT siblings of a physical core are always pinned together
#      (physical-core basis, #3217 §2.2). Hence each entry is "<cores>,<cores+64>".
#   2. Every server set stays inside ONE NUMA node/socket — node 0. This is NEW
#      (#3217's host had one node). A set spanning sockets would measure UPI
#      traffic and cross-socket LLC behaviour, a DIFFERENT question that would
#      make the endpoint comparison meaningless. S=1 and S=6 both live on node 0.
#   3. The client set is a CONSTANT across both endpoints, 2 physical cores, on
#      the SAME NUMA node as the server set, and MUST NOT overlap it —
#      `perf stat -C <server>` would otherwise count client work as engine work.
#
# Physical-core indices mirror #3217's choices so the shape of the comparison is
# preserved; only the sibling offset and the NUMA confinement change.
#   S=1 -> physical core 2          -> "2,66"
#   S=2 -> physical cores 0,2       -> "0,2,64,66"
#   S=4 -> physical cores 0-3       -> "0-3,64-67"
#   S=6 -> physical cores 0-5       -> "0-5,64-69"
#   client (constant) -> cores 8,9  -> "8,9,72,73"
# All of 0-5,8,9 are in node0's 0-31 and all of 64-69,72,73 are in node0's
# 64-95, so every set above is node-0-confined and client/server are disjoint.
ws0_server_cpus_for_s() {
  case "$1" in
    1) echo "2,66" ;;
    2) echo "0,2,64,66" ;;
    4) echo "0-3,64-67" ;;
    6) echo "0-5,64-69" ;;
    *) ws0_die "no server-cpu set defined for S=$1 (known: 1 2 4 6)" ;;
  esac
}
WS0_CLIENT_CPUS_DEFAULT="8,9,72,73"

# NUMA node every arm is confined to (rule 2). The server is additionally
# launched under `numactl --cpunodebind --membind` so page-cache and heap
# allocations cannot land on the far node: a mixed-NUMA allocation is a
# plausible alternative explanation for an IPC delta and must be excluded BY
# CONSTRUCTION, not by argument.
WS0_NUMA_NODE="${WS0_NUMA_NODE:-0}"

# Fail closed if a pinned set is not actually inside WS0_NUMA_NODE, or if the
# two sets overlap. This is the mechanical guard that replaces trusting the
# table above — the table is hand-written, so it gets checked at run time.
ws0_assert_cpuset_on_node() {
  local label="$1" cpus="$2" node="${3:-$WS0_NUMA_NODE}"
  python3 - "$label" "$cpus" "$node" <<'PY'
import sys
label, cpus, node = sys.argv[1], sys.argv[2], sys.argv[3]
def expand(s):
    o=set()
    for part in s.split(','):
        part=part.strip()
        if not part: continue
        if '-' in part:
            a,b=part.split('-'); o|=set(range(int(a),int(b)+1))
        else: o.add(int(part))
    return o
want = expand(cpus)
have = expand(open('/sys/devices/system/node/node%s/cpulist' % node).read().strip())
stray = sorted(want - have)
if stray:
    sys.exit("FATAL: %s set %s has CPUs %s OUTSIDE numa node %s "
             "(node%s cpulist = %s). A cross-socket server set measures UPI/"
             "remote-LLC behaviour, which is a different question."
             % (label, cpus, stray, node, node, sorted(have)))
print("%s=%s -> %d cpus, all on node %s" % (label, cpus, len(want), node))
PY
}
# The guard that actually catches #3217's table. ws0_assert_cpuset_on_node does
# NOT: on this box #3217's S=1 set "2,10" is entirely inside node 0 and passes
# it, yet sysfs says cpu2 -> {2,66} and cpu10 -> {10,74}, so "2,10" is TWO
# DIFFERENT PHYSICAL CORES — one thread of each, siblings idle. It would have
# measured S=2 on a half-populated pair while labelling the point S=1, and
# nothing downstream would have noticed. Verified as a negative test, recorded
# in harness/README.md.
#
# So assert the physical-core basis directly: the pinned set must be an exact
# union of COMPLETE SMT sibling groups, and the number of those groups must equal
# the S the caller asked for.
ws0_assert_full_physical_cores() {
  local label="$1" cpus="$2" want_cores="$3"
  python3 - "$label" "$cpus" "$want_cores" <<'PY'
import glob, re, sys
label, cpus, want = sys.argv[1], sys.argv[2], int(sys.argv[3])
def expand(s):
    o=set()
    for part in s.split(','):
        part=part.strip()
        if not part: continue
        if '-' in part:
            a,b=part.split('-'); o|=set(range(int(a),int(b)+1))
        else: o.add(int(part))
    return o
want_set = expand(cpus)
groups = {}
for path in glob.glob('/sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list'):
    cpu = int(re.search(r'cpu(\d+)', path).group(1))
    groups[cpu] = frozenset(expand(open(path).read().strip()))
touched = {groups[c] for c in want_set if c in groups}
partial = [sorted(g) for g in touched if not g <= want_set]
if partial:
    sys.exit("FATAL: %s set %s is NOT a union of complete SMT sibling groups. "
             "Partially-pinned physical cores: %s. Both siblings of a physical "
             "core must be pinned together (physical-core basis); pinning one "
             "thread of each of two cores measures a different machine than the "
             "label claims. This is exactly the defect in #3217's hardcoded "
             "table on this host (its S=1 '2,10' is cpu2->{2,66} and "
             "cpu10->{10,74} = two half-pinned cores)."
             % (label, cpus, partial))
if len(touched) != want:
    sys.exit("FATAL: %s set %s spans %d physical cores, but S=%d was requested."
             % (label, cpus, len(touched), want))
print("%s=%s -> %d complete physical cores (%d hw threads), physical-core basis OK"
      % (label, cpus, len(touched), len(want_set)))
PY
}

ws0_assert_sets_disjoint() {
  local scpus="$1" ccpus="$2"
  python3 - "$scpus" "$ccpus" <<'PY'
import sys
def expand(s):
    o=set()
    for part in s.split(','):
        part=part.strip()
        if not part: continue
        if '-' in part:
            a,b=part.split('-'); o|=set(range(int(a),int(b)+1))
        else: o.add(int(part))
    return o
s,c = expand(sys.argv[1]), expand(sys.argv[2])
both = sorted(s & c)
if both:
    sys.exit("FATAL: server and client CPU sets OVERLAP on %s. "
             "perf stat -C <server> would count client work as engine work." % both)
print("server/client sets disjoint (server %d cpus, client %d cpus)" % (len(s), len(c)))
PY
}

# Expand "0-3,8-11" -> count of logical CPUs.
ws0_cpulist_count() {
  python3 -c '
import sys
n=0
for part in sys.argv[1].split(","):
    if "-" in part:
        a,b=part.split("-"); n+=int(b)-int(a)+1
    else:
        n+=1
print(n)' "$1"
}
ws0_cpulist_expand() {
  python3 -c '
import sys
o=[]
for part in sys.argv[1].split(","):
    if "-" in part:
        a,b=part.split("-"); o+=list(range(int(a),int(b)+1))
    else:
        o.append(int(part))
print(",".join(str(x) for x in sorted(set(o))))' "$1"
}

# ------------------------------------------------------------ input validation
ws0_require_inputs() {
  [ -n "$WS0_STAGE" ]       || ws0_die "WS0_STAGE unset (staged SSTable dir; corpus is generated by a peer agent, never hardcoded)"
  [ -d "$WS0_STAGE" ]       || ws0_die "WS0_STAGE=$WS0_STAGE is not a directory"
  [ -n "$WS0_FLIGHT_BIN" ]  || ws0_die "WS0_FLIGHT_BIN unset (path to cqlite-flight)"
  [ -x "$WS0_FLIGHT_BIN" ]  || ws0_die "WS0_FLIGHT_BIN=$WS0_FLIGHT_BIN is not executable"
  [ -n "$WS0_LOADGEN_BIN" ] || ws0_die "WS0_LOADGEN_BIN unset (path to flight-loadgen)"
  [ -x "$WS0_LOADGEN_BIN" ] || ws0_die "WS0_LOADGEN_BIN=$WS0_LOADGEN_BIN is not executable"
  [ -n "$WS0_TICKET_TPL" ]  || ws0_die "WS0_TICKET_TPL unset (--ticket-template JSON)"
  [ -f "$WS0_TICKET_TPL" ]  || ws0_die "WS0_TICKET_TPL=$WS0_TICKET_TPL not found"
  # #3217's check tested only 1-2 levels, so the CORRECT layout warned. The
  # layout cqlite-flight actually discovers is <keyspace>/<table>-<uuid>/, i.e.
  # THREE levels down — and a flat stage (which this check ACCEPTED) makes the
  # server log "discovered 0 tables across 0 keyspaces" and every request
  # NotFound. So search at any depth, and require at least one Data.db.
  local ndata
  ndata="$(find "$WS0_STAGE" -name '*-Data.db' -type f 2>/dev/null | wc -l)"
  [ "$ndata" -gt 0 ] || ws0_die "no *-Data.db anywhere under WS0_STAGE=$WS0_STAGE"
  ls "$WS0_STAGE"/*/*/*-Data.db >/dev/null 2>&1 || \
    ws0_warn "WS0_STAGE=$WS0_STAGE has $ndata Data.db but not at the <keyspace>/<table-uuid>/ depth cqlite-flight discovers — a flat stage yields 'discovered 0 tables' and all-NotFound"
}

# ------------------------------------------------------------ server lifecycle
# ws0_start_server <server-cpu-list> <merge-path: bypass|merge> <log-file>
# Exports WS0_SERVER_PID. Blocks until the port answers (<=60s) or dies.
ws0_start_server() {
  local cpus="$1" merge_path="$2" logfile="$3"
  mkdir -p "$(dirname "$logfile")"
  ws0_log "starting cqlite-flight on cpus=$cpus merge_path=$merge_path numa-node=$WS0_NUMA_NODE"
  # NUMA binding (RUNBOOK step 3 rule 2) — NEW vs #3217, whose host had one node.
  # --cpunodebind confines scheduling to node N and --membind confines page-cache
  # and heap allocation to node N's memory, so a far-node allocation cannot be an
  # alternative explanation for an IPC delta. taskset then pins to the exact set
  # inside that node. Recorded in the run config verbatim.
  CQLITE_FLIGHT_MERGE_PATH="$merge_path" \
  numactl --cpunodebind="$WS0_NUMA_NODE" --membind="$WS0_NUMA_NODE" \
  taskset -c "$cpus" "$WS0_FLIGHT_BIN" \
      --data-dir "$WS0_STAGE" \
      --listen "${WS0_LISTEN_HOST}:${WS0_LISTEN_PORT}" \
      --batch-size "$WS0_BATCH_SIZE" \
      --max-batch-bytes "$WS0_MAX_BATCH_BYTES" \
      --max-inflight-egress-bytes "$WS0_MAX_INFLIGHT_EGRESS_BYTES" \
      --max-concurrent-scans "$WS0_MAX_CONCURRENT_SCANS" \
      --admission-wait-timeout-ms "$WS0_ADMISSION_WAIT_TIMEOUT_MS" \
      >"$logfile" 2>&1 &
  WS0_SERVER_PID=$!
  export WS0_SERVER_PID
  local i
  for i in $(seq 1 60); do
    if ! kill -0 "$WS0_SERVER_PID" 2>/dev/null; then
      ws0_die "cqlite-flight (pid $WS0_SERVER_PID) died during startup; see $logfile"
    fi
    if (echo >"/dev/tcp/${WS0_LISTEN_HOST}/${WS0_LISTEN_PORT}") 2>/dev/null; then
      ws0_log "server ready pid=$WS0_SERVER_PID after ${i}s"
      return 0
    fi
    sleep 1
  done
  ws0_stop_server
  ws0_die "server did not accept on ${WS0_LISTEN_HOST}:${WS0_LISTEN_PORT} within 60s; see $logfile"
}

# TRAP 2: explicit PID only. `pkill -f 'cqlite-flight --data-dir'` matches the
# launching shell's own command line and kills the harness. Never use it.
ws0_stop_server() {
  local pid="${1:-${WS0_SERVER_PID:-}}"
  [ -n "$pid" ] || return 0
  kill -0 "$pid" 2>/dev/null || { unset WS0_SERVER_PID || true; return 0; }
  ws0_log "stopping server pid=$pid"
  kill -TERM "$pid" 2>/dev/null || true
  local i
  for i in $(seq 1 15); do kill -0 "$pid" 2>/dev/null || break; sleep 1; done
  kill -0 "$pid" 2>/dev/null && kill -9 "$pid" 2>/dev/null || true
  wait "$pid" 2>/dev/null || true
  unset WS0_SERVER_PID || true
}

# ------------------------------------------------------------- counter helpers
# CPU seconds consumed by a pid (utime+stime), from /proc/<pid>/stat fields 14,15.
ws0_proc_cpu_secs() {
  local pid="$1"
  awk -v hz="$(getconf CLK_TCK)" '{print ($14+$15)/hz}' "/proc/$pid/stat" 2>/dev/null || echo 0
}
# /proc/<pid>/io as compact JSON. rchar / read_bytes / syscr are reported
# SEPARATELY and are NEVER divided by one another (different units, different
# layers) — see README.
ws0_proc_io_json() {
  local pid="$1"
  python3 -c '
import json,sys
d={}
try:
    for line in open("/proc/%s/io"%sys.argv[1]):
        k,v=line.split(":"); d[k.strip()]=int(v)
except OSError: pass
print(json.dumps(d))' "$pid"
}
# voluntary / nonvoluntary context switches from /proc/<pid>/status (AC5).
ws0_proc_ctxt_json() {
  local pid="$1"
  python3 -c '
import json,sys
d={}
try:
    for line in open("/proc/%s/status"%sys.argv[1]):
        if line.startswith(("voluntary_ctxt_switches","nonvoluntary_ctxt_switches")):
            k,v=line.split(":"); d[k.strip()]=int(v)
except OSError: pass
print(json.dumps(d))' "$pid"
}
# Aggregate CPU busy seconds over a CPU list, from /proc/stat (used for the
# CLIENT-set utilisation validity gate, which must not depend on knowing the
# client's pid tree).
ws0_cpuset_busy_secs() {
  python3 -c '
import sys
want=set()
for part in sys.argv[1].split(","):
    if "-" in part:
        a,b=part.split("-"); want|=set(range(int(a),int(b)+1))
    else:
        want.add(int(part))
hz=100.0
tot=0.0
for line in open("/proc/stat"):
    f=line.split()
    if not f or not f[0].startswith("cpu") or f[0]=="cpu": continue
    try: n=int(f[0][3:])
    except ValueError: continue
    if n not in want: continue
    v=[int(x) for x in f[1:11]]
    idle=v[3]+v[4]           # idle + iowait
    tot += (sum(v)-idle)/hz
print(tot)' "$1"
}

# Best-effort page-cache warm pre-pass. This is a CPU measurement; a cold read
# would attribute page-fault/IO stalls to the engine.
ws0_warm_prepass() {
  local client_cpus="$1" secs="${2:-45}" logfile="$3"
  ws0_log "warm pre-pass ${secs}s (page cache)"
  taskset -c "$client_cpus" "$WS0_LOADGEN_BIN" \
      --endpoint "$WS0_ENDPOINT" --ticket-template "$WS0_TICKET_TPL" \
      --shape full --ramp 1 --step-duration "${secs}s" --seed "$WS0_SEED" \
      --round prewarm --out /dev/null >"$logfile" 2>&1 || \
    ws0_warn "warm pre-pass returned non-zero (see $logfile) — continuing"
}
