/**
 * Platform loader tests (Issue #571).
 *
 * The root `index.js` is generated by `scripts/generate-loader.mjs` and selects
 * the correct bundled `cqlite-node.<triple>.node` for the host. @cqlite/node is a
 * single fat package — there are NO per-platform scoped npm packages and no
 * optionalDependencies, so the loader must:
 *   1. never `require` a scoped `@cqlite/node-*` package, and
 *   2. throw one actionable error naming the unsupported platform + the supported
 *      matrix when there is no bundled binary for the host.
 *
 * These tests exercise the generated loader source itself (wiring evidence) so a
 * regression in the template is caught before publish.
 */

const path = require('path');
const fs = require('fs');
const { execFileSync } = require('child_process');

const BINDINGS_DIR = path.resolve(__dirname, '..');
const LOADER_SCRIPT = path.join(BINDINGS_DIR, 'scripts', 'generate-loader.mjs');
const INDEX_JS = path.join(BINDINGS_DIR, 'index.js');

const SUPPORTED_MATRIX = [
  'linux-x64-gnu',
  'linux-arm64-gnu',
  'darwin-x64',
  'darwin-arm64',
  'win32-x64-msvc',
];

function generateLoader() {
  // Runs the exact script used by the `pretest`/`postbuild` npm hooks.
  execFileSync(process.execPath, [LOADER_SCRIPT], {
    cwd: BINDINGS_DIR,
    encoding: 'utf8',
  });
  return fs.readFileSync(INDEX_JS, 'utf8');
}

/**
 * Require the generated index.js in a child process under a faked
 * platform/arch and capture the error thrown at load time.
 * Returns the child process stderr (the uncaught error text).
 */
function loadUnderFakePlatform(platform, arch, preamble = '') {
  const script = `
    Object.defineProperty(process, 'platform', { value: ${JSON.stringify(platform)} });
    Object.defineProperty(process, 'arch', { value: ${JSON.stringify(arch)} });
    ${preamble}
    require(${JSON.stringify(INDEX_JS)});
  `;
  try {
    execFileSync(process.execPath, ['-e', script], {
      cwd: BINDINGS_DIR,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { threw: false, stderr: '' };
  } catch (err) {
    // Non-zero exit: the uncaught throw is on stderr.
    return { threw: true, stderr: String(err.stderr || err.message || '') };
  }
}

describe('Platform loader (Issue #571)', () => {
  let source;

  beforeAll(() => {
    source = generateLoader();
  });

  describe('Generated source invariants', () => {
    test('never requires a scoped @cqlite/node-* fallback package', () => {
      // The single fat-package model: no scoped packages are published, so the
      // loader must not reference them at all.
      expect(source).not.toMatch(/require\(['"`]@cqlite\/node-/);
      expect(source).not.toContain("@cqlite/node-darwin");
      expect(source).not.toContain("@cqlite/node-linux");
      expect(source).not.toContain("@cqlite/node-win32");
    });

    test('embeds the supported-platform matrix string', () => {
      for (const triple of SUPPORTED_MATRIX) {
        expect(source).toContain(triple);
      }
    });

    test('throws a no-prebuilt-binary error referencing the supported matrix', () => {
      expect(source).toContain('has no prebuilt binary for');
      expect(source).toContain('supported:');
    });
  });

  describe('Unsupported-platform load behavior', () => {
    test.each([
      ['linux', 'ia32'], // unsupported arch on a supported OS
      ['win32', 'arm64'], // unsupported arch on Windows
      ['aix', 'ppc64'], // unsupported OS entirely
    ])('throws actionable error on %s-%s', (platform, arch) => {
      const { threw, stderr } = loadUnderFakePlatform(platform, arch);
      expect(threw).toBe(true);
      expect(stderr).toContain('@cqlite/node has no prebuilt binary for');
      expect(stderr).toContain(`${platform}-${arch}`);
      expect(stderr).toContain('linux-x64-gnu');
      // Crucially: NOT the confusing scoped-module error.
      expect(stderr).not.toContain("Cannot find module '@cqlite/node-");
    });

    test('reports linux-<arch>-musl on a musl host (no gnu/musl contradiction)', () => {
      // Force the musl branch by faking the libc probe used by isMusl():
      // process.report.getReport().header.glibcVersionRuntime === undefined.
      const preamble = `
        process.report = {
          getReport: () => ({ header: {} }),
        };
      `;
      const { threw, stderr } = loadUnderFakePlatform('linux', 'x64', preamble);
      expect(threw).toBe(true);
      // The reported target carries the -musl suffix so it does not read as a
      // contradiction against the libc-qualified supported matrix.
      expect(stderr).toContain('linux-x64-musl');
      expect(stderr).not.toContain('binary for linux-x64;');
      expect(stderr).toContain('linux-x64-gnu');
      expect(stderr).not.toContain("Cannot find module '@cqlite/node-");
    });
  });
});
