blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/psacuto/cqlite/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: https://github.com/psacuto/cqlite/security/advisories/new
    about: Report security vulnerabilities privately