name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
projects: ["cqlite-development"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear/confusing content
        - Code examples don't work
        - API documentation
        - Installation instructions
        - Usage guide
        - Architecture/design docs
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      options:
        - README.md
        - API docs (rustdoc)
        - CLI help text
        - Code comments
        - Separate documentation file
        - GitHub wiki
        - Examples
        - No documentation exists
        - Other
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (if applicable)

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should this be improved?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that would help improve the documentation