#!/usr/bin/env bash
# Guards for scripts/perf/ws0_quiescence_evidence.py — the CLOSED verdict-evidence checker.
#
# WHY A DEDICATED SUITE. The inline predecessor of this checker was holed by review three rounds
# running (jobs 73, 75, 78) because it was patched pointwise and its properties were verified BY
# HAND and never pinned. Every case below perturbs exactly ONE aspect of a baseline the POSITIVE
# CONTROL proves acceptable, and asserts a diagnostic naming ITS OWN subject: a refusal from some
# other precondition is the vacuous-pass shape these guards exist to refuse.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PERF="$REPO_ROOT/perf"
# `-B` ON EVERY PYTHON INVOCATION, AND A CACHE SWEEP, BECAUSE A STALE .pyc FOOLED THIS SUITE.
# While RED-verifying the drift check I mutated CANONICAL_MAX_LOAD1 2.0 -> 7.5 and restored it.
# The suite kept reporting drift: `2.0` and `7.5` are the SAME BYTE LENGTH, and the restore landed
# in the same mtime SECOND, so CPython's (mtime, size) cache-validity test saw a valid .pyc and
# served the mutated constant from a source file that no longer contained it. A test that can be
# fooled by a stale cache reports on a module nobody is running.
export PYTHONDONTWRITEBYTECODE=1
find "$REPO_ROOT/perf" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

checks=0
fails=0
pass() { checks=$((checks + 1)); echo "ok   - $1"; }
fail() { checks=$((checks + 1)); fails=$((fails + 1)); echo "FAIL - $1"; }

# --------------------------------------------------------------------------------------------
# The canonical thresholds are DUPLICATED in the evidence module (to keep it dependency-free),
# so they are asserted against the writer's here. A silent divergence would let the reporter
# certify a bar the writer refuses, or red a verdict the writer accepts -- and a duplicated
# constant with no drift check is exactly the kind of pair that rots.
# --------------------------------------------------------------------------------------------
if out=$(python3 - "$PERF" <<'PY'
import sys
sys.path.insert(0, sys.argv[1])
import ws0_quiescence as w
import ws0_quiescence_evidence as e
# ALL THREE bounds, because job 80 F1 was a bound that existed in the writer and not here.
pairs = [("MAX_LOAD1", w.DEFAULT_MAX_LOAD1, e.CANONICAL_MAX_LOAD1),
         ("MAX_LOAD1_MOVEMENT", w.DEFAULT_MAX_LOAD1_MOVEMENT, e.CANONICAL_MAX_LOAD1_MOVEMENT),
         ("MAX_SAMPLE_GAP_S", w.MAX_SAMPLE_GAP_S, e.CANONICAL_COVERAGE_GAP_BOUND_S)]
# ...and the table must not have grown a bound the drift check does not cover.
if len(e.CANONICAL_BOUNDS) != len(pairs):
    sys.exit(f"DRIFT: CANONICAL_BOUNDS has {len(e.CANONICAL_BOUNDS)} entries but this check "
             f"covers {len(pairs)}. A bound with no drift check is the job-80 F1 defect again.")
bad = [f"{n}: writer={a!r} evidence={b!r}" for n, a, b in pairs if a != b]
if bad:
    sys.exit("DRIFT: " + "; ".join(bad))
print("aligned")
PY
); then
  pass "the evidence module's canonical thresholds MATCH ws0_quiescence's defaults ($out)"
else
  fail "canonical threshold drift between writer and evidence checker: $out"
fi

# --------------------------------------------------------------------------------------------
# The mutation matrix. The baseline is generated by the SHIPPED writer path so the suite cannot
# drift from the real record shape -- the failure mode that cost jobs 73 and 75.
# --------------------------------------------------------------------------------------------
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
python3 "$PERF/ws0_quiescence.py" sample --out "$TMP/b.json" >/dev/null 2>&1
python3 "$PERF/ws0_quiescence.py" sample --out "$TMP/a.json" >/dev/null 2>&1
WS="$(python3 -c "import datetime;print((datetime.datetime.now(datetime.timezone.utc)-datetime.timedelta(seconds=240)).strftime('%Y-%m-%dT%H:%M:%SZ'))")"
WE="$(python3 -c "import datetime;print(datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'))")"
if ! python3 "$PERF/ws0_quiescence.py" judge --before "$TMP/b.json" --after "$TMP/a.json" \
       --out "$TMP/v.json" --timeseries "$(ls -d /data/ws0-3248/sampler/box-load.jsonl 2>/dev/null || echo /nonexistent)" \
       --window-start "$WS" --window-end "$WE" >/dev/null 2>&1; then
  echo "SKIP - no live box-load timeseries on this host, so the shipped writer cannot produce a"
  echo "       baseline verdict. The matrix below needs one; the threshold-drift check above ran."
  echo
  echo "ws0-quiescence-evidence guards: $checks check(s) ran, $fails failed (matrix SKIPPED)"
  [ "$fails" -eq 0 ] || exit 1
  exit 0
fi

run_matrix() {
python3 - "$PERF" "$TMP/v.json" <<'PY'
import copy, json, sys
sys.path.insert(0, sys.argv[1])
from ws0_quiescence_evidence import assert_self_consistent, EvidenceError
base = json.loads(open(sys.argv[2]).read())

# POSITIVE CONTROL FIRST: without it every refusal below could be firing on a broken baseline.
try:
    assert_self_consistent(copy.deepcopy(base), "baseline")
    print("PASS|the shipped writer's own verdict is ACCEPTED (positive control)")
except EvidenceError as exc:
    print(f"FAILCASE|positive control REFUSED, so the whole matrix is vacuous: {exc}")
    raise SystemExit(1)

CASES = [
    ("a dotted key forging a nested path is refused", "PATH SEPARATOR",
     lambda v: (v["before"].__setitem__("competing", ["cc1"]),
                v["before"].__setitem__("competing_count", 1),
                v.__setitem__("before.competing", []),
                v.__setitem__("before.competing_count", 0))),
    ("a dotted key is refused even when its value is harmless", "PATH SEPARATOR",
     lambda v: v.__setitem__("window_census.samples", 41)),
    ("thresholds.max_load1 LOOSER than canonical is refused", "LOOSER than the canonical",
     lambda v: v["thresholds"].__setitem__("max_load1", 999.0)),
    ("thresholds.max_load1_movement LOOSER than canonical is refused",
     "LOOSER than the canonical",
     lambda v: v["thresholds"].__setitem__("max_load1_movement", 9.0)),
    ("an UNDECLARED field is refused (the writer grew a field)", "does not know",
     lambda v: v.__setitem__("brand_new_field", 1)),
    ("a MISSING declared field is refused", "missing",
     lambda v: v.pop("thresholds")),
    ("a competitor at the before boundary is refused", "before boundary census lists",
     lambda v: (v["before"].__setitem__("competing", ["cc1"]),
                v["before"].__setitem__("competing_count", 1))),
    ("a competitor at the after boundary is refused", "after boundary census lists",
     lambda v: (v["after"].__setitem__("competing", ["ld", "rustc"]),
                v["after"].__setitem__("competing_count", 2))),
    ("competing_count disagreeing with len(competing) is refused", "holds 0 entr",
     lambda v: v["after"].__setitem__("competing_count", 3)),
    ("a top-level/nested duplicate that disagrees is refused", "must",
     lambda v: v.__setitem__("competing_before", 4)),
    ("nonzero in-window competing_samples is refused", "with a competing process",
     lambda v: v["window_census"].__setitem__("competing_samples", 7)),
    ("a zero-sample window is refused (unmeasured, not quiet)", "not an integer >= 1",
     lambda v: v["window_census"].__setitem__("samples", 0)),
    ("narrow_census_records exceeding samples is refused as impossible", "impossible",
     lambda v: v["window_census"].__setitem__("narrow_census_records", 999)),
    ("a gap wider than the verdict's OWN bound is refused", "exceeds",
     lambda v: v["window_census"].__setitem__("coverage_largest_gap_s", 999.0)),
    ("census_breadth claiming FULL while narrow>0 is refused", "NOT what narrow_census_records",
     lambda v: (v["window_census"].__setitem__("narrow_census_records", 3),
                v["window_census"].__setitem__("census_breadth", "FULL (all records)"))),
    ("census_breadth claiming NARROW while narrow==0 is refused", "NOT what narrow_census_records",
     lambda v: (v["window_census"].__setitem__("narrow_census_records", 0),
                v["window_census"].__setitem__("census_breadth", "NARROW on 2 of 5"))),
    ("load1_mean outside its own min/max is refused", "impossible",
     lambda v: v["window_census"].__setitem__("load1_mean", 99.0)),
    ("a judged window running backwards is refused", "does not run forwards",
     lambda v: v["window_census"]["window"].__setitem__("end", "2020-01-01T00:00:00Z")),
    ("a recorded load1_movement disagreeing with the boundaries is refused", "differ by",
     lambda v: v.__setitem__("load1_movement", 7.77)),
    ("load1_before above its own max_load1 is refused", "above its own",
     lambda v: (v.__setitem__("load1_before", 99.0),
                v["before"]["load"].__setitem__("load1", 99.0),
                v.__setitem__("load1_movement", abs(v["load1_after"] - 99.0)))),
    # --- job 80: the FAMILY sweep, not the three reported instances ---
    ("coverage_gap_bound_s LOOSER than canonical is refused (the third bound, missed in job 78)",
     "LOOSER than the canonical",
     lambda v: (v["window_census"].__setitem__("coverage_gap_bound_s", 9999.0),
                v["window_census"].__setitem__("coverage_largest_gap_s", 9998.0))),
    ("census_breadth as ARBITRARY text beside a nonzero narrow count is refused",
     "NOT what narrow_census_records",
     lambda v: (v["window_census"].__setitem__("narrow_census_records", 2),
                v["window_census"].__setitem__("census_breadth", "everything is fine"))),
    ("census_breadth with the WRONG sample count in its own text is refused",
     "NOT what narrow_census_records",
     lambda v: (v["window_census"].__setitem__("narrow_census_records", 2),
                v["window_census"].__setitem__(
                    "census_breadth",
                    "NARROW on 2 of 999 record(s): those carry rustc/cargo/gate only, so a"
                    " short-lived cc1/ld/lld/mold between boundaries would not appear. Stated"
                    " rather than implied."))),
    ("load1_after_note disagreeing with load1_after_is_bounded is refused (swept, not reported)",
     "NOT what load1_after_is_bounded",
     lambda v: v.__setitem__("load1_after_note", "bounded: the caller asserted this sample was"
                                                " taken after settling")),
    ("a non-dict verdict is refused", "not a JSON object", lambda v: None),
]
for label, expect, mut in CASES:
    v = copy.deepcopy(base)
    if mut(v) is None and label.startswith("a non-dict"):
        v = ["not", "a", "dict"]
    try:
        assert_self_consistent(v, "verdict")
        print(f"FAILCASE|{label}: ACCEPTED a verdict it must refuse")
    except EvidenceError as exc:
        if expect in str(exc):
            print(f"PASS|{label}")
        else:
            print(f"FAILCASE|{label}: refused for the WRONG cause (wanted {expect!r}): {exc}")
PY
}

while IFS='|' read -r verdict label; do
  [ -n "$verdict" ] || continue
  case "$verdict" in
    PASS) pass "$label" ;;
    FAILCASE) fail "$label" ;;
  esac
done < <(run_matrix)

MIN_CHECKS=26
if [ "$checks" -lt "$MIN_CHECKS" ]; then
  echo
  echo "FAIL - only $checks check(s) ran; this suite has at least $MIN_CHECKS."
  echo "       A block that silently never executed would lower the count with no failure."
  exit 1
fi
echo
if [ "$fails" -eq 0 ]; then
  echo "ws0-quiescence-evidence guards: all $checks checks passed"
  exit 0
fi
echo "ws0-quiescence-evidence guards: $fails of $checks check(s) FAILED"
exit 1
