[package]
name = "cqlite-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
chrono = "0.4"

[[bin]]
name = "cqlite-validator"
path = "src/main.rs"