//! Regression test for issue #1104: the compaction stitch path must honor
//! incompressible/raw chunks.
//!
//! Cassandra stores a compressed chunk RAW (uncompressed) when its compressed
//! length would meet/exceed `max_compressed_length` (the incompressible-chunk
//! fallback). The read/scan path (`stitch_all_chunks`) was taught this rule in
//! epic #970, but the compaction path
//! (`iterate_all_partitions_for_compaction` -> `stitch_and_parse_all_chunks_for_compaction`)
//! still blindly LZ4/Snappy/etc-decoded every chunk. On an SSTable with a
//! raw-stored chunk that failed with e.g. "the offset to copy is not contained
//! in the decompressed buffer".
//!
//! This test drives the compaction read path over the
//! `test_comp/incompressible_uncompressed_chunk` fixture (>= 1 chunk stored
//! raw) and asserts it (a) succeeds and (b) returns the full golden row count.
//!
//! The fixture's binary `Data.db` is generated by
//! `test-data/scripts/generate-compression-parity.sh` and is gitignored. When
//! it is absent the test SKIPs cleanly (mirrors issue_998); when present, a
//! 0-row or error result is a hard failure.

use std::fs::{self, File};
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use cqlite_core::storage::sstable::reader::SSTableReader;
use cqlite_core::{Config, Platform};

const TABLE: &str = "incompressible_uncompressed_chunk";

/// Locate the test_comp dataset directory, honoring CQLITE_DATASETS_ROOT.
fn datasets_root() -> PathBuf {
    std::env::var("CQLITE_DATASETS_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .map(|p| p.join("test-data/datasets"))
                .unwrap_or_else(|| PathBuf::from("test-data/datasets"))
        })
}

/// Resolve the `<table>-<uuid>` directory that actually holds a `Data.db`
/// (no hardcoded UUID; the generator assigns a fresh UUID per run). Returns the
/// Data.db path, or None when absent so the caller SKIPs.
fn resolve_data_db(table: &str) -> Option<PathBuf> {
    let comp_dir = datasets_root().join("sstables/test_comp");
    if !comp_dir.is_dir() {
        return None;
    }
    let prefix = format!("{}-", table);
    for entry in fs::read_dir(&comp_dir).ok()?.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with(&prefix) && entry.path().is_dir() {
            let data_db = entry.path().join("nb-1-big-Data.db");
            if data_db.exists() {
                return Some(data_db);
            }
        }
    }
    None
}

/// Count `row` objects in an sstabledump JSONL golden. The dump is
/// partition-granular (one JSON object per partition, each carrying a `rows`
/// array), so a line count under-counts a single wide partition — count the
/// embedded `"type":"row"` markers instead.
fn count_golden_rows(path: &Path) -> std::io::Result<usize> {
    let file = File::open(path)?;
    let mut rows = 0usize;
    for line in BufReader::new(file).lines() {
        rows += line?.matches("\"type\":\"row\"").count();
    }
    Ok(rows)
}

#[tokio::test]
async fn issue_1104_compaction_over_incompressible_chunks_succeeds() {
    let Some(data_db) = resolve_data_db(TABLE) else {
        eprintln!(
            "SKIP[{}]: Data.db absent under {} (run generate-compression-parity.sh)",
            TABLE,
            datasets_root().display()
        );
        return;
    };

    let config = Config::default();
    let platform = Arc::new(Platform::new(&config).await.unwrap());

    let reader = SSTableReader::open(&data_db, &config, platform)
        .await
        .expect("Failed to open incompressible-chunk SSTable");

    // The compaction read path. Before #1104 this errored on the raw chunk with
    // "LZ4 decompression failed: the offset to copy is not contained in the
    // decompressed buffer".
    let rows = reader
        .iterate_all_partitions_for_compaction(None)
        .await
        .unwrap_or_else(|e| {
            panic!(
                "[{}] compaction path failed on incompressible/raw chunk (issue #1104): {}",
                TABLE, e
            )
        });

    assert!(
        !rows.is_empty(),
        "[{}] compaction path returned 0 rows on a valid SSTable",
        TABLE
    );

    // Correctness: row count must match the golden JSONL beside the Data.db.
    let jsonl = data_db.with_file_name("nb-1-big-Data.db.jsonl");
    if jsonl.exists() {
        let expected = count_golden_rows(&jsonl).expect("read golden JSONL");
        assert_eq!(
            rows.len(),
            expected,
            "[{}] compaction path produced {} rows; golden JSONL has {}",
            TABLE,
            rows.len(),
            expected
        );
    }
}
