//! Issue #1295 (follow-up to #1275) — SIGNED numeric collection-element /
//! map-key ordering, validated BYTE-FOR-BYTE against a REAL Cassandra 5.0.2
//! golden.
//!
//! ## Why this test exists
//!
//! Issue #1275 added a type-aware SIGNED comparator for SET elements / MAP keys
//! (Cassandra `SetType`/`MapType` sort by the element/key type's own
//! `AbstractType.compare`, which for the integer marshal types and
//! DecimalType/DoubleType is SIGNED). The #1275 writer tests
//! (`writer/data_writer/tests/scenarios_4.rs`) are oracle-GROUNDED but DERIVE the
//! expected byte layout from Cassandra's comparator rule — there was no committed
//! Cassandra-written golden with NEGATIVE numeric collection elements/keys.
//!
//! This test closes that gap. It reads the `test_signed_coll` fixtures
//! (`test-data/schemas/signed-collection-parity.cql`, generated by
//! `test-data/scripts/generate-signed-collection-parity.sh` from Cassandra
//! 5.0.2) and asserts that:
//!
//!   1. The persisted on-disk element/key ORDER recorded in the sstabledump
//!      golden matches the SIGNED comparator oracle (a hardcoded expected order),
//!      so a regenerated or corrupt golden cannot silently false-pass.
//!   2. CQLite's reader (`scan_delta`) decodes the SAME order from the SAME
//!      Data.db — i.e. CQLite reads the Cassandra-written signed order exactly.
//!
//! ## Gate
//!
//!   * `#[cfg(feature = "delta-scan")]`.
//!   * Skips cleanly when `CQLITE_DATASETS_ROOT` is unset or the binary `Data.db`
//!     is absent (the `.db` reference binaries are gitignored / local-only and
//!     supplied via `CQLITE_DATASETS_ROOT`). When a fixture IS present, decoding
//!     to ZERO rows is a HARD FAILURE — a present-but-empty fixture cannot pass.
//!   * `CQLITE_REQUIRE_FIXTURES=1` makes a missing fixture a hard failure (the
//!     nightly/exhaustive lane sets this).
//!
//! Run with:
//! ```bash
//! env CQLITE_DATASETS_ROOT=$PWD/test-data/datasets \
//!   cargo test -p cqlite-core --features delta-scan \
//!   --test issue_1295_signed_collection_order_parity -- --nocapture
//! ```

#![cfg(feature = "delta-scan")]

use std::path::{Path, PathBuf};

use cqlite_core::schema::TableSchema;
use cqlite_core::storage::sstable::reader::delta_scan::{scan_delta, DeltaRecord};
use cqlite_core::types::Value;

// ===========================================================================
// Canonical scalar rendering — collapses both the golden JSONL value and the
// CQLite-decoded `Value` to the SAME stable string so element/key ORDER can be
// compared apples-to-apples across the two sources.
// ===========================================================================

/// Render a CQLite-decoded scalar collection element / map key into the same
/// canonical string sstabledump emits for it. Only the scalar types used by the
/// #1295 fixtures are handled; anything else is a loud panic (an unexpected type
/// is a regression, never silently rendered).
fn render_value(v: &Value) -> String {
    match v {
        Value::Integer(i) => i.to_string(),
        Value::BigInt(i) => i.to_string(),
        Value::SmallInt(i) => i.to_string(),
        Value::TinyInt(i) => i.to_string(),
        Value::Text(s) => s.clone(),
        Value::Float(f) => render_double(*f),
        Value::Float32(f) => render_double(*f as f64),
        Value::Decimal { scale, unscaled } => render_decimal(*scale, unscaled),
        Value::Frozen(inner) => render_value(inner),
        other => panic!("unexpected scalar type in #1295 fixture decode: {other:?}"),
    }
}

/// Canonical double rendering matching sstabledump's tokens for the special
/// values the `set<double>` fixture locks: `NaN`, `Infinity`, `-Infinity`,
/// `-0.0` vs `0.0`. Finite values render with Rust's `Display`, which matches
/// the fixture's chosen finite values (`-1.5`, `2.5`).
fn render_double(f: f64) -> String {
    if f.is_nan() {
        "NaN".to_string()
    } else if f.is_infinite() {
        if f.is_sign_negative() {
            "-Infinity".to_string()
        } else {
            "Infinity".to_string()
        }
    } else if f == 0.0 {
        // Preserve signed zero: sstabledump emits "-0.0" / "0.0".
        if f.is_sign_negative() {
            "-0.0".to_string()
        } else {
            "0.0".to_string()
        }
    } else {
        // -1.5 / 2.5 render identically under Display.
        let s = format!("{f}");
        if s.contains('.') {
            s
        } else {
            format!("{s}.0")
        }
    }
}

/// Render a CQLite `Decimal { scale, unscaled }` to the same decimal string
/// sstabledump prints (unscaled big-endian two's-complement integer / 10^scale).
/// Uses `num_bigint::BigInt` (a crate dependency) so the LARGE-unscaled fixture
/// value beyond i128 is rendered without overflow (no saturating cast).
fn render_decimal(scale: i32, unscaled: &[u8]) -> String {
    use num_bigint::BigInt;
    let unscaled_int = BigInt::from_signed_bytes_be(unscaled);
    if scale == 0 {
        return unscaled_int.to_string();
    }
    // Positive scale -> insert a decimal point `scale` digits from the right.
    let negative = unscaled_int < BigInt::from(0);
    let digits = unscaled_int.magnitude().to_str_radix(10);
    let scale_usize = scale.max(0) as usize;
    let padded = if digits.len() <= scale_usize {
        format!("{:0>width$}", digits, width = scale_usize + 1)
    } else {
        digits
    };
    let point = padded.len() - scale_usize;
    let (int_part, frac_part) = padded.split_at(point);
    let body = format!("{int_part}.{frac_part}");
    if negative {
        format!("-{body}")
    } else {
        body
    }
}

// ===========================================================================
// Golden JSONL: persisted element/key ORDER per column (the Cassandra oracle).
// ===========================================================================

/// For a given column, the persisted ORDER of its elements (set) or keys (map)
/// as recorded by sstabledump in the golden — rendered to canonical strings.
fn golden_order(golden_json: &serde_json::Value, column: &str) -> Vec<String> {
    let rows = golden_json
        .get("rows")
        .and_then(|r| r.as_array())
        .expect("golden has rows array");
    let mut order = Vec::new();
    for row in rows {
        let cells = match row.get("cells").and_then(|c| c.as_array()) {
            Some(c) => c,
            None => continue,
        };
        for cell in cells {
            if cell.get("name").and_then(|n| n.as_str()) != Some(column) {
                continue;
            }
            // Multicell (non-frozen) collection: one cell per element with a
            // `path` (set element / map key). The leading path-less cell is the
            // complex-deletion shell — skip it.
            if let Some(path) = cell.get("path").and_then(|p| p.as_array()) {
                if let Some(first) = path.first().and_then(|v| v.as_str()) {
                    order.push(first.to_string());
                }
                continue;
            }
            // Frozen (single-cell) collection: `value` is the whole collection.
            if let Some(value) = cell.get("value") {
                match value {
                    // frozen set -> JSON array, in persisted order.
                    serde_json::Value::Array(arr) => {
                        for e in arr {
                            order.push(json_scalar_string(e));
                        }
                    }
                    // frozen map -> JSON object; serde_json::Map preserves
                    // insertion order (sstabledump emits keys in persisted order).
                    serde_json::Value::Object(map) => {
                        for k in map.keys() {
                            order.push(k.clone());
                        }
                    }
                    _ => {}
                }
            }
        }
    }
    order
}

/// Render a scalar JSON value (number / string) into the same canonical string
/// `render_value` produces, so frozen-set elements compare correctly.
fn json_scalar_string(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Number(n) => n.to_string(),
        other => other.to_string(),
    }
}

fn load_golden_json(path: &Path) -> serde_json::Value {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read golden {path:?}: {e}"));
    // The golden is one JSON object per line (single partition here).
    let line = text
        .lines()
        .find(|l| !l.trim().is_empty())
        .unwrap_or_else(|| panic!("golden {path:?} is empty"));
    serde_json::from_str(line).unwrap_or_else(|e| panic!("parse golden {path:?}: {e}"))
}

// ===========================================================================
// CQLite decode: persisted element/key ORDER per column via scan_delta.
// ===========================================================================

async fn cqlite_order(fixture_dir: &Path, schema: TableSchema, column: &str) -> Vec<String> {
    let (mut rx, _summary) = scan_delta(fixture_dir.to_path_buf(), schema, 256);
    let mut order = Vec::new();
    while let Some(result) = rx.recv().await {
        let rec = result.unwrap_or_else(|e| panic!("scan_delta error in {fixture_dir:?}: {e}"));
        if let DeltaRecord::Upsert { cells, .. } = rec {
            for (col, cd) in &cells {
                if col.0 != column {
                    continue;
                }
                if let Some(v) = &cd.value {
                    append_collection_order(v, &mut order);
                }
            }
        }
    }
    order
}

/// Append the element / key order of a decoded collection value. Sets contribute
/// element strings in order; maps contribute KEY strings in order. A `Frozen`
/// wrapper is unwrapped first.
fn append_collection_order(v: &Value, out: &mut Vec<String>) {
    match v {
        Value::Frozen(inner) => append_collection_order(inner, out),
        Value::Set(xs) | Value::List(xs) => {
            for e in xs {
                out.push(render_value(e));
            }
        }
        Value::Map(kvs) => {
            for (k, _val) in kvs {
                out.push(render_value(k));
            }
        }
        other => panic!("expected a collection value for #1295 column, got {other:?}"),
    }
}

// ===========================================================================
// Schema loading from the committed DDL.
// ===========================================================================

fn schema_file() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("test-data")
        .join("schemas")
        .join("signed-collection-parity.cql")
}

fn load_table_schema(table: &str) -> TableSchema {
    let ddl = std::fs::read_to_string(schema_file())
        .unwrap_or_else(|e| panic!("read schema {:?}: {e}", schema_file()));
    let stmt = extract_create_table(&ddl, table)
        .unwrap_or_else(|| panic!("CREATE TABLE {table} not found in DDL"));
    let (_, mut schema) = cqlite_core::schema::cql_parser::parse_create_table(&stmt)
        .unwrap_or_else(|e| panic!("parse CREATE TABLE {table}: {e:?}"));
    schema.keyspace = "test_signed_coll".to_string();
    schema.table = table.to_string();
    schema
}

fn extract_create_table(ddl: &str, table: &str) -> Option<String> {
    let needle = format!("create table if not exists {table} ");
    let lower = ddl.to_lowercase();
    let start = lower.find(&needle).or_else(|| {
        let alt = format!("create table {table} ");
        lower.find(&alt)
    })?;
    let rest = &ddl[start..];
    let semi = rest.find(';')?;
    let stmt = &rest[..=semi];
    let stmt = stmt.replacen("IF NOT EXISTS ", "", 1);
    let cleaned = stmt
        .lines()
        .map(|line| match line.find("--") {
            Some(idx) => &line[..idx],
            None => line,
        })
        .collect::<Vec<_>>()
        .join("\n");
    Some(cleaned)
}

// ===========================================================================
// Fixture discovery + skip-on-absence guard.
// ===========================================================================

fn datasets_root() -> Option<PathBuf> {
    let p = PathBuf::from(std::env::var("CQLITE_DATASETS_ROOT").ok()?);
    p.exists().then_some(p)
}

fn fixture_dir(table: &str) -> Option<PathBuf> {
    let root = datasets_root()?;
    let ks = root.join("sstables").join("test_signed_coll");
    for entry in std::fs::read_dir(&ks).ok()?.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let n = name.to_str().unwrap_or("");
        if n.starts_with(&format!("{table}-")) {
            return Some(path);
        }
    }
    None
}

/// The JSONL goldens are committed in the repo's `test-data` tree (binary
/// `Data.db` files are gitignored and supplied via `CQLITE_DATASETS_ROOT`).
fn golden_path(table: &str) -> Option<PathBuf> {
    let ks = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("test-data")
        .join("datasets")
        .join("sstables")
        .join("test_signed_coll");
    for entry in std::fs::read_dir(&ks).ok()?.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let n = name.to_str().unwrap_or("");
        if n.starts_with(&format!("{table}-")) {
            let p = path.join("nb-1-big-Data.db.jsonl");
            if p.exists() {
                return Some(p);
            }
        }
    }
    None
}

fn require_fixtures_strict() -> bool {
    std::env::var("CQLITE_REQUIRE_FIXTURES")
        .map(|v| v == "1")
        .unwrap_or(false)
}

fn skip_or_fail(table: &str, reason: &str) {
    if require_fixtures_strict() {
        panic!("CQLITE_REQUIRE_FIXTURES=1 but {table} fixture unavailable: {reason}");
    }
    println!("[SKIP] {table}: {reason}");
}

// ===========================================================================
// Core assertion: golden order == expected signed oracle, AND CQLite order ==
// golden order. A present fixture decoding to zero elements is a hard failure.
// ===========================================================================

/// For one column, assert (a) the golden's persisted order matches the hardcoded
/// SIGNED oracle and (b) CQLite decodes the same order. Returns Some(n_elements)
/// when the fixture is present, None when skipped.
async fn assert_column_order(table: &str, column: &str, expected_signed: &[&str]) -> Option<usize> {
    let dir = match fixture_dir(table) {
        Some(d) => d,
        None => {
            skip_or_fail(table, "no fixture dir under CQLITE_DATASETS_ROOT");
            return None;
        }
    };
    let data_db = dir.join("nb-1-big-Data.db");
    if !data_db.exists() {
        skip_or_fail(table, "binary nb-1-big-Data.db absent");
        return None;
    }
    let golden = golden_path(table)
        .unwrap_or_else(|| panic!("{table}: golden nb-1-big-Data.db.jsonl missing"));
    let golden_json = load_golden_json(&golden);

    let expected: Vec<String> = expected_signed.iter().map(|s| s.to_string()).collect();

    // (a) The Cassandra-written golden's persisted order must equal the signed oracle.
    let g_order = golden_order(&golden_json, column);
    assert!(
        !g_order.is_empty(),
        "[{table}] column '{column}': golden produced ZERO elements — fixture/golden regression"
    );
    assert_eq!(
        g_order, expected,
        "[{table}] column '{column}': Cassandra-written GOLDEN order != SIGNED oracle.\n  \
         golden:   {g_order:?}\n  expected: {expected:?}"
    );

    // (b) CQLite must decode the SAME persisted order from the SAME Data.db.
    let schema = load_table_schema(table);
    let c_order = cqlite_order(&dir, schema, column).await;
    assert!(
        !c_order.is_empty(),
        "[{table}] column '{column}': CQLite decoded ZERO elements from a PRESENT fixture — failure"
    );
    assert_eq!(
        c_order, expected,
        "[{table}] column '{column}': CQLite decode order != Cassandra golden order.\n  \
         cqlite:   {c_order:?}\n  expected: {expected:?}"
    );

    println!(
        "[{table}] column '{column}': {} elements, signed order matched ({expected:?})",
        expected.len()
    );
    Some(expected.len())
}

// ===========================================================================
// Tests — one per comparator branch the fixtures lock.
// ===========================================================================

/// Non-frozen set<int> / map<int,text>: negative elements/keys sort SIGNED
/// (-2,-1,0,1,3 / keys -5,-1,0,2), not raw unsigned (-1 would sort last).
#[tokio::test]
async fn nonfrozen_set_map_int_negative_signed_order() {
    if let Some(n) =
        assert_column_order("signed_int_collections", "s", &["-2", "-1", "0", "1", "3"]).await
    {
        assert_eq!(n, 5);
    }
    assert_column_order("signed_int_collections", "m", &["-5", "-1", "0", "2"]).await;
}

/// frozen<set<int>> / frozen<map<int,text>>: single-cell blob with the same
/// negative SIGNED ordering. This is the exact on-disk blob the #1275
/// `test_frozen_set_int_negative_sorts_signed` /
/// `test_frozen_map_int_key_negative_sorts_signed` writer tests derive.
#[tokio::test]
async fn frozen_set_map_int_negative_signed_order() {
    assert_column_order("frozen_int_collections", "fs", &["-2", "-1", "0", "1", "3"]).await;
    assert_column_order("frozen_int_collections", "fm", &["-5", "-1", "0", "2"]).await;
}

/// set<bigint> / set<smallint> / set<tinyint>: the other integer-width signed
/// comparator branches (LongType / ShortType / ByteType).
#[tokio::test]
async fn nonfrozen_set_signed_width_order() {
    assert_column_order(
        "signed_width_collections",
        "sb",
        &["-100", "-1", "0", "1", "100"],
    )
    .await;
    assert_column_order(
        "signed_width_collections",
        "ss",
        &["-300", "-1", "0", "1", "300"],
    )
    .await;
    assert_column_order(
        "signed_width_collections",
        "st",
        &["-120", "-1", "0", "1", "120"],
    )
    .await;
}

/// set<decimal>: DecimalType signed order including a LARGE-unscaled value beyond
/// i128 (no overflow / saturating cast in the reader's decimal decode).
#[tokio::test]
async fn nonfrozen_set_decimal_large_unscaled_signed_order() {
    assert_column_order(
        "signed_special_collections",
        "sd",
        &[
            "-999999999999999999999999999999.999",
            "-1.5",
            "0",
            "123456789012345678901234567890.123",
        ],
    )
    .await;
}

/// set<double>: DoubleType signed order — NaN sorts LAST and -0.0 < +0.0
/// (the float-ordering-vs-Java comparator branch added in #1275).
#[tokio::test]
async fn nonfrozen_set_double_nan_signed_zero_order() {
    assert_column_order(
        "signed_special_collections",
        "sf",
        &["-Infinity", "-1.5", "-0.0", "0.0", "2.5", "Infinity", "NaN"],
    )
    .await;
}
