//! Issue #1190 (epic #969): whole-artifact byte parity of CQLite writer output
//! against committed Cassandra 5.0.2-written reference SSTables.
//!
//! This is the FIRST test that diffs a *finished* CQLite-written SSTable
//! file-vs-file against a Cassandra-written reference for the same logical
//! schema/data (not a derived-value invariant, not a round-trip). It backs the
//! upgrade of two `write_load_path` parity-manifest scenarios from `partial` to
//! `byte_for_byte`:
//!
//!   * cass.write_load_path.cql_sstable_writer.finished_data_db_artifacts
//!     → `finished_data` (int PK, one text col): a finished Data.db artifact.
//!   * cass.write_load_path.flush.partition_boundary_artifacts
//!     → `partition_boundary` (int PK, int CK, text col; two partitions, several
//!     clustering rows each): partition-boundary Data.db + Index.db layout.
//!
//! The reference fixtures are generated by
//! `test-data/scripts/generate-write-load-parity.sh` (Cassandra 5.0.2, sha
//! f278f6774fc76465c182041e081982105c3e7dbb) and committed under
//! `test-data/datasets/sstables/test_writeparity/`. CQLite re-emits the exact
//! same logical input (same fixed writetime `T_WRITE`, same int keys, same text
//! values) via `SSTableWriter` and the bytes are compared.
//!
//! DETERMINISM CONTRACT (why two independent writers can byte-match):
//!   * Every cell uses the single fixed writetime `T_WRITE`, so the
//!     EncodingStats.minTimestamp delta baseline is identical (verified by the
//!     committed `*-Statistics.db.txt`: `EncodingStats minTimestamp: 1700000000000000`).
//!   * Tables are UNCOMPRESSED, so Data.db is a direct byte slice (no chunk
//!     framing differences).
//!   * Partition keys are int / (int,int): identical 4-byte big-endian key
//!     bytes and identical token ordering on both writers.
//!   * No TTL and no DELETE in these two tables. TTL/DELETE `localDeletionTime`
//!     is wall-clock-derived (`nowInSeconds`) and CANNOT byte-match across two
//!     independent writers — that is why the tombstone/TTL scenario stays
//!     `partial` (its byte SHAPE is anchored by issue_764 / issue_821 against
//!     derived expected values, not a whole-artifact diff).
//!
//! WHICH COMPONENTS ARE BYTE-FOR-BYTE (verified empirically against the
//! committed reference):
//!   * Data.db, Index.db, Summary.db, Digest.crc32 → BYTE-IDENTICAL. These are
//!     the data artifact, the partition/row offset table, the summary index, and
//!     the whole-file CRC32. They are diffed byte-for-byte here; any mismatch
//!     FAILS. This is the byte parity backing the scenario upgrades.
//!   * Filter.db and Statistics.db → NOT byte-comparable across two independent
//!     writers: Filter.db embeds implementation-specific bloom-filter sizing
//!     (bucket count / hash count), and Statistics.db embeds metadata histograms,
//!     cardinality (HyperLogLog), and host/encoding bookkeeping. CQLite emits
//!     both, but their bytes are an implementation detail, not a parity target.
//!     Their semantic content is covered elsewhere (Filter membership, Statistics
//!     min/max/EncodingStats are anchored by issue_764 / issue_821).
//!   * CRC.db → BYTE-IDENTICAL (issue #1197, gap now closed): Cassandra emits a
//!     per-chunk CRC.db component for uncompressed BIG SSTables alongside
//!     Digest.crc32. CQLite's writer now emits it too — a 64 KiB chunk-size
//!     header (big-endian i32) followed by one big-endian u32 CRC32 per raw-data
//!     chunk (ChecksummedSequentialWriter / ChecksumWriter). Because Data.db is
//!     byte-identical and the chunk size matches Cassandra's 64 KiB default, the
//!     CRC.db bytes match exactly and are diffed byte-for-byte below.
//!
//! Dataset-dependency doctrine (issue #719 / parity mandate):
//!   * If `CQLITE_DATASETS_ROOT` is unset OR the reference Data.db is genuinely
//!     absent (binaries not fetched), the test SKIPS (returns early with a note).
//!   * If the reference is PRESENT but empty / 0-rows, that is a FAILURE — a
//!     present-but-empty fixture must never silently pass.

#![cfg(feature = "write-support")]

use cqlite_core::schema::{ClusteringColumn, ClusteringOrder, Column, KeyColumn, TableSchema};
use cqlite_core::storage::sstable::writer::{SSTableFormat, SSTableWriter};
use cqlite_core::storage::write_engine::mutation::{
    CellOperation, ClusteringKey, DecoratedKey, Mutation, PartitionKey, TableId,
};
use cqlite_core::types::Value;
use std::collections::{BTreeSet, HashMap};
use std::path::{Path, PathBuf};
use tempfile::TempDir;

/// The single fixed writetime (micros). MUST match the `T_WRITE` constant in
/// `test-data/scripts/generate-write-load-parity.sh`.
const T_WRITE: i64 = 1_700_000_000_000_000;

const KEYSPACE: &str = "test_writeparity";

// ---------------------------------------------------------------------------
// Fixture resolution (skip-on-absence; present-but-empty is a failure)
// ---------------------------------------------------------------------------

/// Resolve the committed Cassandra reference directory for `table` under
/// `test_writeparity`. Returns `None` when the dataset root is unset or the
/// table's reference SSTable has not been fetched (genuine absence → skip).
fn reference_dir(table: &str) -> Option<PathBuf> {
    let root = std::env::var("CQLITE_DATASETS_ROOT").ok()?;
    let base = Path::new(&root).join("sstables").join(KEYSPACE);
    let entries = std::fs::read_dir(&base).ok()?;
    for e in entries.flatten() {
        let name = e.file_name().to_string_lossy().to_string();
        if name.starts_with(&format!("{table}-")) {
            let dir = e.path();
            // Genuine absence = no Data.db committed/fetched yet.
            if dir.join("nb-1-big-Data.db").is_file() {
                return Some(dir);
            }
            return None;
        }
    }
    None
}

/// Read a reference component file. Panics if a *present* reference directory is
/// missing a component (a fetched-but-broken fixture is a real failure, never a
/// silent skip).
fn read_component(dir: &Path, suffix: &str) -> Vec<u8> {
    let path = dir.join(format!("nb-1-big-{suffix}"));
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!("reference component {path:?} unreadable in a present fixture: {e}")
    })
}

// ---------------------------------------------------------------------------
// CQLite writer harness
// ---------------------------------------------------------------------------

/// Write `mutations` for `schema` through the real `SSTableWriter` (BIG/nb,
/// uncompressed) and return the finished component directory.
async fn cqlite_write(schema: &TableSchema, mutations: Vec<Mutation>) -> (TempDir, PathBuf) {
    let dir = TempDir::new().expect("tempdir");
    let mut writer =
        SSTableWriter::with_format(dir.path().to_path_buf(), 1, schema, 16, SSTableFormat::Big)
            .expect("writer");

    // Decorate and group by partition key in ascending token order (the writer
    // requires strict token ordering and one write_partition call per key).
    let mut keyed: Vec<(DecoratedKey, Mutation)> = mutations
        .into_iter()
        .map(|m| (m.decorated_key(schema).expect("decorated key"), m))
        .collect();
    keyed.sort_by_key(|(k, _)| k.token);

    let mut grouped: Vec<(DecoratedKey, Vec<Mutation>)> = Vec::new();
    for (k, m) in keyed {
        match grouped.last_mut() {
            Some((lk, ms)) if lk.token == k.token && lk.key == k.key => ms.push(m),
            _ => grouped.push((k, vec![m])),
        }
    }
    for (k, ms) in grouped {
        writer.write_partition(k, ms).expect("write_partition");
    }
    let info = writer.finish().await.expect("finish");
    let table_dir = info.data_path.parent().expect("data parent").to_path_buf();
    (dir, table_dir)
}

/// Set of component suffixes present in a directory (strips the `nb-1-big-`
/// descriptor prefix so CQLite (`nb-1-big-`) and Cassandra (`nb-1-big-`) compare
/// on the logical component name).
fn component_suffixes(dir: &Path) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    if let Ok(rd) = std::fs::read_dir(dir) {
        for e in rd.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            // Every committed/emitted component carries the `nb-1-big-` descriptor
            // prefix (including `nb-1-big-TOC.txt`), so the `-big-` split handles
            // all of them; anything without it is not an SSTable component.
            if let Some(idx) = name.find("-big-") {
                set.insert(name[idx + 5..].to_string());
            }
        }
    }
    // Drop derived/golden sidecars that only exist in the committed reference
    // tree (not emitted by either writer): JSONL + sstablemetadata text.
    set.retain(|s| !s.ends_with(".jsonl") && !s.ends_with("Statistics.db.txt"));
    set
}

/// TOC.txt content as a set of trimmed non-empty component lines.
fn toc_set(toc_bytes: &[u8]) -> BTreeSet<String> {
    String::from_utf8_lossy(toc_bytes)
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect()
}

/// First differing byte index, if any.
fn first_diff(a: &[u8], b: &[u8]) -> Option<usize> {
    let n = a.len().max(b.len());
    (0..n).find(|&i| a.get(i) != b.get(i))
}

// ---------------------------------------------------------------------------
// Schemas (exactly the schema/data the generator writes)
// ---------------------------------------------------------------------------

fn finished_schema() -> TableSchema {
    TableSchema {
        keyspace: KEYSPACE.into(),
        table: "finished_data".into(),
        partition_keys: vec![KeyColumn {
            name: "id".into(),
            data_type: "int".into(),
            position: 0,
        }],
        clustering_keys: vec![],
        columns: vec![
            Column {
                name: "id".into(),
                data_type: "int".into(),
                nullable: false,
                default: None,
                is_static: false,
            },
            Column {
                name: "name".into(),
                data_type: "text".into(),
                nullable: true,
                default: None,
                is_static: false,
            },
        ],
        comments: HashMap::new(),
        dropped_columns: HashMap::new(),
    }
}

fn partition_boundary_schema() -> TableSchema {
    TableSchema {
        keyspace: KEYSPACE.into(),
        table: "partition_boundary".into(),
        partition_keys: vec![KeyColumn {
            name: "id".into(),
            data_type: "int".into(),
            position: 0,
        }],
        clustering_keys: vec![ClusteringColumn {
            name: "ck".into(),
            data_type: "int".into(),
            position: 0,
            order: ClusteringOrder::Asc,
        }],
        columns: vec![
            Column {
                name: "id".into(),
                data_type: "int".into(),
                nullable: false,
                default: None,
                is_static: false,
            },
            Column {
                name: "ck".into(),
                data_type: "int".into(),
                nullable: false,
                default: None,
                is_static: false,
            },
            Column {
                name: "v".into(),
                data_type: "text".into(),
                nullable: true,
                default: None,
                is_static: false,
            },
        ],
        comments: HashMap::new(),
        dropped_columns: HashMap::new(),
    }
}

fn finished_mutations() -> Vec<Mutation> {
    (0..6)
        .map(|i| {
            Mutation::new(
                TableId::new(KEYSPACE, "finished_data"),
                PartitionKey::single("id", Value::Integer(i)),
                None,
                vec![CellOperation::Write {
                    column: "name".into(),
                    value: Value::Text(format!("name{i}")),
                }],
                T_WRITE,
                None,
            )
        })
        .collect()
}

fn partition_boundary_mutations() -> Vec<Mutation> {
    let mut muts = Vec::new();
    for ck in 1..=4 {
        muts.push(Mutation::new(
            TableId::new(KEYSPACE, "partition_boundary"),
            PartitionKey::single("id", Value::Integer(1)),
            Some(ClusteringKey::single("ck", Value::Integer(ck))),
            vec![CellOperation::Write {
                column: "v".into(),
                value: Value::Text(format!("v_1_{ck}")),
            }],
            T_WRITE,
            None,
        ));
    }
    for ck in 1..=2 {
        muts.push(Mutation::new(
            TableId::new(KEYSPACE, "partition_boundary"),
            PartitionKey::single("id", Value::Integer(2)),
            Some(ClusteringKey::single("ck", Value::Integer(ck))),
            vec![CellOperation::Write {
                column: "v".into(),
                value: Value::Text(format!("v_2_{ck}")),
            }],
            T_WRITE,
            None,
        ));
    }
    muts
}

// ---------------------------------------------------------------------------
// Shared whole-artifact byte-parity assertion
// ---------------------------------------------------------------------------

/// Diff a CQLite-written SSTable against the Cassandra reference for `table`:
/// component presence, TOC.txt, full Data.db bytes, full Index.db bytes (the
/// partition/row offset table), AND the committed sstabledump JSONL golden
/// (non-empty / expected partition count). Any mismatch FAILS.
///
/// `expected_jsonl_partitions` is the number of partitions the committed JSONL
/// golden must contain (present-but-empty / wrong-count is a failure).
async fn assert_byte_parity(
    table: &str,
    schema: TableSchema,
    mutations: Vec<Mutation>,
    expected_jsonl_partitions: usize,
) {
    let Some(ref_dir) = reference_dir(table) else {
        eprintln!(
            "[issue_1190] reference for {KEYSPACE}.{table} absent (dataset not fetched); skipping"
        );
        return;
    };

    let (_guard, out_dir) = cqlite_write(&schema, mutations).await;

    // 1. Component presence: every component CQLite emits must be present in the
    //    reference (no spurious CQLite-only component), and the byte-parity data
    //    components must be present on BOTH sides.
    let ref_components = component_suffixes(&ref_dir);
    let our_components = component_suffixes(&out_dir);
    assert!(
        !ref_components.is_empty(),
        "{table}: reference component set is empty (broken fixture)"
    );
    for needed in [
        "Data.db",
        "Index.db",
        "Summary.db",
        "Digest.crc32",
        "Statistics.db",
        "Filter.db",
        "TOC.txt",
        // CRC.db is now emitted by CQLite for uncompressed BIG SSTables
        // (issue #1197), matching Cassandra. Both sides must carry it.
        "CRC.db",
    ] {
        assert!(
            ref_components.contains(needed),
            "{table}: reference missing required component {needed}; have {ref_components:?}"
        );
        assert!(
            our_components.contains(needed),
            "{table}: CQLite output missing component {needed}; have {our_components:?}"
        );
    }

    // No spurious CQLite-only component: every component CQLite emits must be
    // present in the reference. With CRC.db now emitted (issue #1197) the
    // component sets are symmetric for the uncompressed BIG path; the allow-list
    // stays empty and any CQLite-only component is a regression.
    const CQLITE_ONLY_ALLOWED: &[&str] = &[];
    let spurious: Vec<&String> = our_components
        .difference(&ref_components)
        .filter(|c| !CQLITE_ONLY_ALLOWED.contains(&c.as_str()))
        .collect();
    assert!(
        spurious.is_empty(),
        "{table}: CQLite emitted spurious component(s) absent from the reference: \
         {spurious:?} (ours={our_components:?} ref={ref_components:?}); if intentional, \
         add to CQLITE_ONLY_ALLOWED with a documented rationale"
    );

    // 2. TOC.txt: the component SET CQLite lists must match the reference TOC
    //    exactly. With CRC.db now emitted (issue #1197) there is no longer a
    //    carve-out — the uncompressed BIG component set is identical.
    let ref_toc = toc_set(&read_component(&ref_dir, "TOC.txt"));
    let our_toc = toc_set(&std::fs::read(out_dir.join("nb-1-big-TOC.txt")).expect("our TOC"));
    assert!(
        ref_toc.contains("CRC.db"),
        "{table}: reference TOC unexpectedly lacks CRC.db (regenerate fixtures?)"
    );
    assert_eq!(
        ref_toc, our_toc,
        "{table}: TOC.txt component set differs (cass={ref_toc:?} ours={our_toc:?})"
    );

    // 3. Data.db: full byte equality (row layout, headers, offsets, cells).
    assert_component_bytes(table, &ref_dir, &out_dir, "Data.db");

    // 4. Index.db: full byte equality (partition key + Data.db offset table =
    //    the partition/row-offset layout). This is the partition-boundary check.
    assert_component_bytes(table, &ref_dir, &out_dir, "Index.db");

    // 5. Summary.db + Digest.crc32 + CRC.db: full byte equality (summary offset
    //    index, whole-file CRC32, and the per-chunk CRC32 component). Completes
    //    the deterministic byte-parity component set. CRC.db (issue #1197) is a
    //    64 KiB-chunk-size header (big-endian i32) followed by one big-endian u32
    //    CRC32 per raw-data chunk; since Data.db is byte-identical and the chunk
    //    size matches Cassandra's 64 KiB default, CRC.db is byte-identical too.
    assert_component_bytes(table, &ref_dir, &out_dir, "Summary.db");
    assert_component_bytes(table, &ref_dir, &out_dir, "Digest.crc32");
    assert_component_bytes(table, &ref_dir, &out_dir, "CRC.db");

    // 6. sstabledump JSONL golden: must exist, be non-empty, and contain exactly
    //    the expected partition count. Present-but-empty / 0-rows is a failure.
    let jsonl = ref_dir.join("nb-1-big-Data.db.jsonl");
    let jsonl_text = std::fs::read_to_string(&jsonl)
        .unwrap_or_else(|e| panic!("{table}: committed JSONL golden {jsonl:?} unreadable: {e}"));
    let partitions: Vec<&str> = jsonl_text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect();
    assert!(
        !partitions.is_empty(),
        "{table}: committed JSONL golden is present-but-empty (0 partitions) — parity failure"
    );
    assert_eq!(
        partitions.len(),
        expected_jsonl_partitions,
        "{table}: JSONL golden partition count {} != expected {expected_jsonl_partitions}",
        partitions.len()
    );
    for (i, line) in partitions.iter().enumerate() {
        let v: serde_json::Value = serde_json::from_str(line)
            .unwrap_or_else(|e| panic!("{table}: JSONL partition {i} is not valid JSON: {e}"));
        let rows = v.get("rows").and_then(|r| r.as_array());
        assert!(
            rows.is_some_and(|r| !r.is_empty()),
            "{table}: JSONL partition {i} has no rows — parity failure"
        );
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Assert a CQLite-written component byte-matches the Cassandra reference.
/// Present-but-empty reference is a failure; any byte mismatch FAILS with a
/// first-diff report.
fn assert_component_bytes(table: &str, ref_dir: &Path, out_dir: &Path, suffix: &str) {
    let reference = read_component(ref_dir, suffix);
    let ours = std::fs::read(out_dir.join(format!("nb-1-big-{suffix}")))
        .unwrap_or_else(|e| panic!("{table}: CQLite {suffix} unreadable: {e}"));
    assert!(
        !reference.is_empty(),
        "{table}: reference {suffix} is present-but-empty — parity failure"
    );
    if reference != ours {
        let at = first_diff(&reference, &ours);
        panic!(
            "{table}: {suffix} byte mismatch (cass={} ours={} bytes, first diff at {:?})\n  cass={}\n  ours={}",
            reference.len(),
            ours.len(),
            at,
            hex(&reference),
            hex(&ours),
        );
    }
}

// ---------------------------------------------------------------------------
// Scenario 1: finished_data_db_artifacts — finished Data.db artifact.
// ---------------------------------------------------------------------------

/// Whole-artifact byte parity: CQLite's finished `finished_data` SSTable
/// (Data.db / Index.db / TOC.txt / components) is byte-identical to the
/// Cassandra 5.0.2 reference, and the committed JSONL golden has the 6 written
/// partitions. Backs
/// `cass.write_load_path.cql_sstable_writer.finished_data_db_artifacts`.
#[tokio::test]
async fn finished_data_db_artifacts_byte_for_byte() {
    assert_byte_parity("finished_data", finished_schema(), finished_mutations(), 6).await;
}

// ---------------------------------------------------------------------------
// Static-row byte parity (issue #1196): static block must NOT carry row liveness
// ---------------------------------------------------------------------------
//
// The `static_clustering_shape` table (id INT, ck INT, sdata TEXT STATIC, rdata
// TEXT, PRIMARY KEY (id, ck)) is written by Cassandra as a static-only UPDATE
// (`SET sdata WHERE id=1`, no clustering key) followed by a clustering INSERT
// (`(id, ck, rdata) VALUES (1, 7, 'row-val')`). Cassandra emits the resulting
// STATIC ROW with flags byte `0xa0` = HAS_EXTENDED_FLAGS (0x80) | HAS_ALL_COLUMNS
// (0x20): the static block carries NO row-level liveness, so HAS_TIMESTAMP is
// NOT set (the writetime lives on the static cell only). This is universal in
// every committed Cassandra golden — no `static_block` ever has a
// `liveness_info` (the static block is keyed on the empty clustering; PK/row
// liveness lives on regular rows, never on the static pseudo-row).
//
// Issue #1196 fixed a writer gap: CQLite used to set a spurious row-level
// HAS_TIMESTAMP (0x04) on the static row (emitting `0xa4`) plus
// `CELL_USE_ROW_TIMESTAMP` on the static cell. This test now asserts BYTE PARITY
// of the whole static-row shape (flags, body, static cell) against the Cassandra
// 5.0.2 reference: the static row's flags byte must be exactly `0xa0` (no
// row-level HAS_TIMESTAMP) and the static cell must carry its own explicit
// timestamp delta, matching the reference bytes. If CQLite ever re-introduces a
// row-level static timestamp, this test FAILS LOUDLY.

const KS_STATIC_TABLE: &str = "static_clustering_shape";

/// Row flags (Cassandra `nb` `UnfilteredSerializer`): HAS_EXTENDED_FLAGS,
/// HAS_TIMESTAMP, HAS_ALL_COLUMNS.
const ROW_HAS_EXTENDED_FLAGS: u8 = 0x80;
const ROW_HAS_TIMESTAMP: u8 = 0x04;

/// Cassandra (#1196) static-row flags byte for `static_clustering_shape`:
/// EXTENDED | HAS_ALL_COLUMNS, with NO row-level timestamp.
const CASS_STATIC_ROW_FLAGS: u8 = 0xa0;

/// Int-PK partition-header byte size: 2 (u16 key-length) plus 4 (key) plus 4
/// (LDT i32) plus 8 (marked-for-delete-at i64). The static row's flags byte is
/// the first unfiltered byte immediately after this header.
const INT_PK_HEADER_SIZE: usize = 2 + 4 + 4 + 8;

fn static_clustering_schema() -> TableSchema {
    TableSchema {
        keyspace: KEYSPACE.into(),
        table: KS_STATIC_TABLE.into(),
        partition_keys: vec![KeyColumn {
            name: "id".into(),
            data_type: "int".into(),
            position: 0,
        }],
        clustering_keys: vec![ClusteringColumn {
            name: "ck".into(),
            data_type: "int".into(),
            position: 0,
            order: ClusteringOrder::Asc,
        }],
        columns: vec![
            Column {
                name: "sdata".into(),
                data_type: "text".into(),
                nullable: true,
                default: None,
                is_static: true,
            },
            Column {
                name: "rdata".into(),
                data_type: "text".into(),
                nullable: true,
                default: None,
                is_static: false,
            },
        ],
        comments: HashMap::new(),
        dropped_columns: HashMap::new(),
    }
}

/// Reproduce the Cassandra fixture's two writes for `static_clustering_shape`:
/// a static-only UPDATE (`SET sdata WHERE id=1`, no clustering) plus a clustering
/// INSERT (`(1, 7, 'row-val')`), both at the fixed writetime.
fn static_clustering_mutations() -> Vec<Mutation> {
    vec![
        Mutation::new(
            TableId::new(KEYSPACE, KS_STATIC_TABLE),
            PartitionKey::single("id", Value::Integer(1)),
            None,
            vec![CellOperation::Write {
                column: "sdata".into(),
                value: Value::Text("static-val".into()),
            }],
            T_WRITE,
            None,
        ),
        Mutation::new(
            TableId::new(KEYSPACE, KS_STATIC_TABLE),
            PartitionKey::single("id", Value::Integer(1)),
            Some(ClusteringKey::single("ck", Value::Integer(7))),
            vec![CellOperation::Write {
                column: "rdata".into(),
                value: Value::Text("row-val".into()),
            }],
            T_WRITE,
            None,
        ),
    ]
}

/// Static-row byte-parity guard for issue #1196: CQLite must emit the static
/// block with flags `0xa0` (no row-level HAS_TIMESTAMP) and the static cell
/// carrying its own explicit timestamp, byte-identical to the Cassandra 5.0.2
/// reference. Backs the resolved static-row divergence in
/// `cass.write_load_path.flush.tombstone_and_ttl_artifacts`.
///
/// Skips on genuine absence of the committed reference; with the fixture
/// committed (issue #1190) it RUNS. If CQLite ever re-introduces the spurious
/// row-level static timestamp (regressing #1196), this test FAILS.
#[tokio::test]
async fn static_row_timestamp_flags_gap_pinned_1196() {
    let Some(ref_dir) = reference_dir(KS_STATIC_TABLE) else {
        eprintln!(
            "[issue_1190] reference for {KEYSPACE}.{KS_STATIC_TABLE} absent \
             (dataset not fetched); skipping #1196 static-row-parity check"
        );
        return;
    };

    // Cassandra reference: static row is the first unfiltered after the header.
    let cass_data = read_component(&ref_dir, "Data.db");
    assert!(
        cass_data.len() > INT_PK_HEADER_SIZE,
        "{KS_STATIC_TABLE}: reference Data.db too short ({} bytes) — broken fixture",
        cass_data.len()
    );
    let cass_flags = cass_data[INT_PK_HEADER_SIZE];
    assert_eq!(
        cass_flags, CASS_STATIC_ROW_FLAGS,
        "#1196: Cassandra static-row flags byte changed (got {cass_flags:#04x}, \
         expected {CASS_STATIC_ROW_FLAGS:#04x}); regenerate fixtures"
    );
    assert_eq!(
        cass_flags & ROW_HAS_TIMESTAMP,
        0,
        "#1196: Cassandra static row must NOT carry row-level HAS_TIMESTAMP"
    );

    // CQLite writer: re-emit the identical static-only UPDATE + clustering INSERT.
    let (_guard, out_dir) =
        cqlite_write(&static_clustering_schema(), static_clustering_mutations()).await;
    let our_data = std::fs::read(out_dir.join("nb-1-big-Data.db"))
        .unwrap_or_else(|e| panic!("{KS_STATIC_TABLE}: CQLite Data.db unreadable: {e}"));
    assert!(
        our_data.len() > INT_PK_HEADER_SIZE,
        "{KS_STATIC_TABLE}: CQLite Data.db too short ({} bytes)",
        our_data.len()
    );
    let our_flags = our_data[INT_PK_HEADER_SIZE];
    assert_eq!(
        our_flags & ROW_HAS_EXTENDED_FLAGS,
        ROW_HAS_EXTENDED_FLAGS,
        "#1196: CQLite static row must set HAS_EXTENDED_FLAGS (static block)"
    );

    // The fix: CQLite static-row flags must now MATCH Cassandra exactly (0xa0).
    // No spurious row-level HAS_TIMESTAMP (0x04).
    assert_eq!(
        our_flags, CASS_STATIC_ROW_FLAGS,
        "#1196: CQLite static-row flags byte must match Cassandra {CASS_STATIC_ROW_FLAGS:#04x} \
         (got {our_flags:#04x}); a spurious row-level HAS_TIMESTAMP (0x04) regressed #1196"
    );
    assert_eq!(
        our_flags & ROW_HAS_TIMESTAMP,
        0,
        "#1196: CQLite static row must NOT carry row-level HAS_TIMESTAMP"
    );

    // Whole-artifact byte parity: this table is deterministic (fixed writetime,
    // no TTL/DELETE), so the entire Data.db — static row header, static cell with
    // its own explicit timestamp, AND the following clustering row — must be
    // byte-identical to the Cassandra reference.
    if cass_data != our_data {
        let at = first_diff(&cass_data, &our_data);
        panic!(
            "#1196: {KS_STATIC_TABLE} Data.db byte mismatch (cass={} ours={} bytes, \
             first diff at {at:?})\n  cass={}\n  ours={}",
            cass_data.len(),
            our_data.len(),
            hex(&cass_data),
            hex(&our_data),
        );
    }
}

// ---------------------------------------------------------------------------
// Scenario 2: partition_boundary_artifacts — partition/row offset layout.
// ---------------------------------------------------------------------------

/// Whole-artifact byte parity: CQLite's finished `partition_boundary` SSTable
/// (multi-partition, multi-clustering-row) is byte-identical to the Cassandra
/// 5.0.2 reference, including the Index.db partition/row-offset table, and the
/// committed JSONL golden has the 2 written partitions. Backs
/// `cass.write_load_path.flush.partition_boundary_artifacts`.
#[tokio::test]
async fn partition_boundary_artifacts_byte_for_byte() {
    assert_byte_parity(
        "partition_boundary",
        partition_boundary_schema(),
        partition_boundary_mutations(),
        2,
    )
    .await;
}
