//! Issue #3790, acceptance criterion 3 — the `inet` / `time` collection-ordering
//! oracle read out of **Cassandra-written bytes**, not out of a CQLite round-trip.
//!
//! # Why this file exists
//!
//! `cqlite-core/tests/issue_3790_inet_time_value_ordering.rs` pins the comparator
//! against hand-constructed `Value`s. That is necessary and it is not sufficient:
//! it asserts what CQLite's comparator does, and nothing about what Cassandra
//! actually wrote. A CQLite-written + CQLite-read round-trip would be no better —
//! it is **invariant to a uniform ordering error**, because the writer and the
//! reader make the identical mistake, the round-trip closes, and the test stays
//! green while real Cassandra data reads misordered (CLAUDE.md, #3042).
//!
//! So the oracle here is a real Cassandra 5.0.2 SSTable:
//! `test-data/datasets/sstables/test_comparator_order/collection_order-*/`
//! (`nb` BIG, uncompressed, no TTL), generated by
//! `test-data/scripts/generate-issue-3790-comparator-ordering.sh` from
//! `test-data/schemas/issue-3790-comparator-ordering.cql`. The README beside the
//! fixture is the written oracle; the `sstabledump` golden `nb-1-big-Data.db.jsonl`
//! is the machine-readable form of it, and this test reads the golden rather than
//! trusting the prose.
//!
//! # Format authority
//!
//! Never a CQLite `file:line` (#3041). At the pinned tag `cassandra-5.0.8`:
//!
//! * `src/java/org/apache/cassandra/db/marshal/InetAddressType.java` —
//!   `InetAddressType() { super(ComparisonType.BYTE_ORDER); }`
//! * `src/java/org/apache/cassandra/db/marshal/TimeType.java` —
//!   `private TimeType() { super(ComparisonType.BYTE_ORDER); }`
//!
//! `ComparisonType.BYTE_ORDER` is `ByteBufferUtil.compareUnsigned`. For a
//! NON-FROZEN collection the element (SET) or key (MAP) *is* the cell path, so
//! that comparator decides the on-disk cell order — which is what makes the
//! property observable in Cassandra-written bytes at all.
//!
//! # What each leg proves
//!
//! **Leg 1 — the golden vs the comparator.** Take each complex column's cell-path
//! sequence *in file order* (the order Cassandra wrote it), transcribe each path
//! into the `Value` it denotes, and require `ComparatorType` to reproduce exactly
//! that sequence: every adjacent-and-non-adjacent pair `Less` in file order, and a
//! sort of a scrambled permutation landing back on it. The file order is
//! additionally cross-checked against the README's hardcoded oracle, so a
//! regenerated or corrupted golden cannot silently false-pass. Negative controls
//! assert the *wrong* implementations produce a DIFFERENT order, so the assertions
//! provably have teeth rather than being satisfiable by any total order.
//!
//! **Leg 2 — CQLite reads the same order off the same bytes.** Decode the real
//! `nb-1-big-Data.db` through the ungated `SSTableReader` compaction iterator,
//! which surfaces each complex column's per-element cells in on-disk order with
//! their decoded values, and assert (a) the decoded values equal Leg 1's
//! transcription — i.e. Leg 1 reasoned about the values the bytes really carry —
//! and (b) sorting those DECODED values with `ComparatorType` reproduces the
//! on-disk order. Leg 2 alone would be weak (a dump path that never re-orders
//! prints the right sequence with or without the fix, as the fixture README warns);
//! its value is that it closes the loop Cassandra bytes -> CQLite decode ->
//! CQLite comparator -> Cassandra's order.
//!
//! # HONEST SCOPE — `time` is a LATENT case, and this file does not overclaim it
//!
//! CQLite renders `time` as `TIME(HH:MM:SS.nnnnnnnnn)` (`types.rs::fmt_time`),
//! fixed-width and zero-padded, so over the whole valid range
//! `0..=86_399_999_999_999` the formatted-string order and the nanosecond order
//! **coincide**. No `time` value — in this fixture or any other — can falsify the
//! formatted-string implementation. The `time` assertions below are therefore a
//! **value-order pin against future regression**, plus a falsifier for a
//! *decimal-nanosecond string* comparison (`9000000000 < 10000000000` numerically
//! while `"9000000000" > "10000000000"` lexicographically). `inet` is the column
//! that catches the live defect. Any reading of this file as demonstrating a
//! caught `time` misordering is wrong.
//!
//! # RED-verified (measured, not asserted)
//!
//! With the `inet`/`time` arms of `types::comparator::custom::compare` removed —
//! i.e. both types back on the formatted-string fallback that was the #3790
//! defect — **7 of these 11 cases FAIL**: every `inet` case and every composite
//! case, in BOTH legs, plus the formatted-string negative control. The four that
//! still pass are exactly the `time` ones and the whole-tuple-path control,
//! which is the LATENT-`time` scope above measured rather than merely claimed. A
//! green ordering test that has never been shown to red proves nothing.
//!
//! # Gate
//!
//! **Deliberately UNGATED at file level.** A crate-level `#![cfg(feature = ...)]`
//! on a `delta-scan` / `observability-testing` feature would put this target in the
//! set that COMPILES in every lane and EXECUTES in none (CLAUDE.md, #3522) — which
//! is exactly what happened to the otherwise-excellent
//! `issue_1295_signed_collection_order_parity.rs`. The gate of record's
//! `core-tests` runs `cargo test -p cqlite-core --features cli-helpers`, so an
//! ungated target executes there; nothing here needs a non-default feature.
//!
//! The fixture is **git-committed**, so it is `must_run` (#3220): failure to
//! resolve it is a hard FAILURE, never a skip, and a present fixture decoding to
//! zero rows/elements is a hard failure too.
//!
//! ```bash
//! cargo test -p cqlite-core --features cli-helpers \
//!   --test issue_3790_collection_order_cassandra_golden -- --nocapture
//! ```

use std::cmp::Ordering;
use std::net::IpAddr;
use std::path::PathBuf;

use cqlite_core::schema::CqlType;
use cqlite_core::types::comparator::ComparatorType;
use cqlite_core::types::Value;

#[path = "support/datasets_root.rs"]
mod datasets_root;
use datasets_root::{describe_search, sstables_root_for_table};

const KEYSPACE: &str = "test_comparator_order";
const TABLE: &str = "collection_order";
const GOLDEN_FILE: &str = "nb-1-big-Data.db.jsonl";

// ===========================================================================
// The README oracle, hardcoded.
//
// These sequences are transcribed from
// `test-data/datasets/sstables/test_comparator_order/README.md` ("THE ORACLE —
// observed on-disk ordering"), which recorded what Cassandra 5.0.2 wrote. They
// are NOT a snapshot of anything CQLite produced. Their job is to make a
// regenerated or corrupted golden fail loudly instead of silently redefining the
// expectation the rest of this file asserts against.
// ===========================================================================

/// `inet_set` / `inet_map`, partition `id = 1`: first bytes
/// `0x00 < 0x09 < 0x0a < 0x20 < 0xc0 < 0xfe`. IPv4 (4 B) and IPv6 (16 B)
/// INTERLEAVE, which is how the golden proves Cassandra neither groups by family
/// nor compares by length.
const ORACLE_INET_ROW1: &[&str] = &[
    "0:0:0:0:0:0:0:1",
    "9.0.0.1",
    "10.0.0.2",
    "2001:db8:0:0:0:0:0:1",
    "192.168.0.1",
    "fe80:0:0:0:0:0:0:1",
];

/// Partition `id = 2`: the minimal falsifying pair. Cassandra puts `9.0.0.1`
/// BEFORE `10.0.0.2` (`0x09 < 0x0a`); formatted-string order puts `10.0.0.2`
/// first (`'1' < '9'`). This is the pair the defect got wrong.
const ORACLE_INET_ROW2: &[&str] = &["9.0.0.1", "10.0.0.2"];

/// `time_set` / `time_map`, partition `id = 1`: nanosecond order.
const ORACLE_TIME_ROW1: &[&str] = &[
    "00:00:00.000000000",
    "00:00:09.000000000",
    "00:00:10.000000000",
    "12:00:00.000000000",
    "23:59:59.999999999",
];

/// Partition `id = 2`: `00:00:09` then `00:00:10` — the decimal-nanosecond
/// string falsifier (`"9000000000" > "10000000000"` lexicographically).
const ORACLE_TIME_ROW2: &[&str] = &["00:00:09.000000000", "00:00:10.000000000"];

/// `pair_set`, partition `id = 1`. INET-MAJOR, TIME-MINOR: the first component
/// decides between distinct addresses, and entries 2 and 3 share `10.0.0.2` and
/// are separated by the `time` component alone. `\:` is sstabledump's escaping of
/// a `:` INSIDE a tuple component; the unescaped `:` is the component separator.
const ORACLE_PAIR_ROW1: &[&str] = &[
    r"9.0.0.1:23\:59\:59.999999999",
    r"10.0.0.2:00\:00\:00.000000000",
    r"10.0.0.2:00\:00\:09.000000000",
    r"2001\:db8\:0\:0\:0\:0\:0\:1:00\:00\:10.000000000",
    r"192.168.0.1:12\:00\:00.000000000",
];

/// `pair_set`, partition `id = 2`: inet-major beats time-minor. On disk
/// `9.0.0.1` (time `00:00:10`) precedes `10.0.0.2` (time `00:00:09`) — a
/// time-MAJOR comparator would reverse these, and so would one that compared the
/// whole rendered tuple path as a single string.
const ORACLE_PAIR_ROW2: &[&str] = &[
    r"9.0.0.1:00\:00\:10.000000000",
    r"10.0.0.2:00\:00\:09.000000000",
];

// ===========================================================================
// Fixture resolution — committed, therefore must_run (#3220): fail closed.
// ===========================================================================

fn fixture_dir() -> PathBuf {
    let root = sstables_root_for_table(KEYSPACE, TABLE).unwrap_or_else(|| {
        panic!(
            "{KEYSPACE}.{TABLE} is COMMITTED to git and must resolve in every \
             checkout, unconditionally (#3220) — {}",
            describe_search(KEYSPACE, TABLE)
        )
    });
    let ks = root.join(KEYSPACE);

    // AMBIGUITY IS A HARD FAILURE, NOT A CHOICE (roborev job 42, findings 1+3).
    //
    // This used to take the FIRST prefix-matching directory and `break`, which is
    // wrong in two reachable ways, and both of them pass silently:
    //
    //   1. STALE GENERATION. Regenerating the fixture produces a NEW `<uuid>`
    //      directory. If the previous one is still committed (the generator's
    //      printed staging commands used to add the new files without staging the
    //      old directory's DELETION), the keyspace holds two generations and the
    //      winner is whatever `read_dir` yields first — i.e. this test would
    //      validate the CORRECT comparator against a STALE oracle, or vice versa.
    //   2. SHADOWING. `sstables_root_for_table` searches `$CQLITE_DATASETS_ROOT`
    //      BEFORE the checkout, so an out-of-tree corpus that happens to carry a
    //      `test_comparator_order/collection_order-*` would silently replace the
    //      COMMITTED oracle this test exists to assert against.
    //
    // `read_dir` order is filesystem-dependent, so either case is a test that
    // passes or fails for reasons unrelated to the code under review. We therefore
    // require EXACTLY ONE candidate carrying BOTH halves of the committed oracle
    // (the Cassandra-written `*-Data.db` and its `*-Data.db.jsonl` golden), and
    // panic naming every candidate otherwise. Fail-closed: a fixture we cannot
    // identify unambiguously is not an oracle.
    let mut candidates: Vec<PathBuf> = std::fs::read_dir(&ks)
        .unwrap_or_else(|e| panic!("read keyspace dir {ks:?}: {e}"))
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.is_dir()
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.starts_with(&format!("{TABLE}-")))
        })
        .filter(|p| {
            let has = |suffix: &str| {
                std::fs::read_dir(p).is_ok_and(|rd| {
                    rd.flatten().any(|e| {
                        e.file_name()
                            .to_str()
                            .is_some_and(|n| n.ends_with(suffix))
                    })
                })
            };
            has("-Data.db") && has("-Data.db.jsonl")
        })
        .collect();
    candidates.sort();

    match candidates.len() {
        1 => candidates.remove(0),
        0 => panic!(
            "no {TABLE}-<uuid> directory under {ks:?} carries BOTH a *-Data.db and its \
             *-Data.db.jsonl golden. {KEYSPACE}.{TABLE} is COMMITTED to git and must \
             resolve in every checkout, unconditionally (#3220: must_run) — {}",
            describe_search(KEYSPACE, TABLE)
        ),
        n => panic!(
            "AMBIGUOUS fixture: {n} {TABLE}-<uuid> directories under {ks:?} each carry a \
             *-Data.db + golden, so which one this test asserts against would depend on \
             filesystem order. Leave exactly ONE generation committed (a regeneration must \
             stage the previous directory's DELETION, not just add the new files). \
             Candidates: {candidates:?}"
        ),
    }
}

// ===========================================================================
// Golden JSONL -> per-(partition, column) cell-path sequence IN FILE ORDER.
// ===========================================================================

/// One partition of the golden: `(column, Some(cell path))` per cell, in file
/// order. `None` is the path-less complex-column deletion shell Cassandra writes
/// ahead of a whole-collection assignment.
type GoldenCells = Vec<(String, Option<String>)>;

/// Every partition of the golden: `(partition key as rendered by sstabledump,
/// cells)`.
type Golden = Vec<(String, GoldenCells)>;

/// Every partition of the golden, as `(partition key string, cells)` where a
/// cell is `(column, Option<path>)`. The path-less cell is the complex-column
/// deletion shell Cassandra writes ahead of a whole-collection assignment; it is
/// skipped by [`golden_order`] rather than dropped here, so a golden that lost
/// its cells entirely still shows up as an empty sequence and fails loudly.
fn load_golden(path: &std::path::Path) -> Golden {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("golden {path:?} is committed alongside the fixture and must read: {e}")
    });
    let mut out = Vec::new();
    for line in text.lines().filter(|l| !l.trim().is_empty()) {
        let v: serde_json::Value =
            serde_json::from_str(line).unwrap_or_else(|e| panic!("parse golden line: {e}"));
        let key = v["partition"]["key"][0]
            .as_str()
            .unwrap_or_else(|| panic!("golden partition has no key"))
            .to_string();
        let mut cells = Vec::new();
        for row in v["rows"].as_array().into_iter().flatten() {
            for cell in row["cells"].as_array().into_iter().flatten() {
                let name = cell["name"]
                    .as_str()
                    .unwrap_or_else(|| panic!("golden cell has no name"))
                    .to_string();
                let path = cell["path"]
                    .as_array()
                    .and_then(|p| p.first())
                    .and_then(|p| p.as_str())
                    .map(str::to_string);
                cells.push((name, path));
            }
        }
        assert!(
            !cells.is_empty(),
            "golden partition {key} has no cells — a present-but-empty golden must \
             never pass"
        );
        out.push((key, cells));
    }
    assert_eq!(
        out.len(),
        2,
        "the fixture has exactly two partitions (id=1 the full case, id=2 the \
         minimal falsifying pair)"
    );
    out
}

/// The cell paths of one column of one partition, in FILE ORDER — i.e. the order
/// Cassandra's comparator put them in.
fn golden_order(golden: &Golden, partition: &str, column: &str) -> Vec<String> {
    let (_, cells) = golden
        .iter()
        .find(|(k, _)| k == partition)
        .unwrap_or_else(|| panic!("golden has no partition {partition}"));
    let order: Vec<String> = cells
        .iter()
        .filter(|(name, _)| name == column)
        .filter_map(|(_, path)| path.clone())
        .collect();
    assert!(
        !order.is_empty(),
        "column {column} of partition {partition} has no path-bearing cells in the \
         golden — a present fixture yielding zero elements is a hard failure"
    );
    order
}

// ===========================================================================
// Transcription: a sstabledump cell path -> the Value it denotes.
//
// Derived from Cassandra's rendering of the type, never from CQLite output:
// InetAddressType renders the address, TimeType renders HH:MM:SS.nnnnnnnnn, and
// a tuple path joins its components with `:` after escaping any `:` inside a
// component as `\:`.
// ===========================================================================

/// `9.0.0.1` / `2001:db8:0:0:0:0:0:1` -> the RAW serialized address bytes
/// (4 for IPv4, 16 for IPv6) — exactly what `InetAddressType` compares.
fn inet_value(rendered: &str) -> Value {
    let addr: IpAddr = rendered
        .parse()
        .unwrap_or_else(|e| panic!("golden inet path {rendered:?} is not an address: {e}"));
    match addr {
        IpAddr::V4(v4) => Value::inet(v4.octets().to_vec()),
        IpAddr::V6(v6) => Value::inet(v6.octets().to_vec()),
    }
}

/// `HH:MM:SS.nnnnnnnnn` -> nanoseconds since midnight, which is `TimeType`'s
/// serialized 8-byte big-endian long.
fn time_nanos(rendered: &str) -> i64 {
    let (hms, nanos) = rendered
        .split_once('.')
        .unwrap_or_else(|| panic!("golden time path {rendered:?} has no fractional part"));
    let parts: Vec<&str> = hms.split(':').collect();
    assert_eq!(
        parts.len(),
        3,
        "golden time path {rendered:?} is not HH:MM:SS.nnnnnnnnn"
    );
    let num = |s: &str| -> i64 {
        s.parse()
            .unwrap_or_else(|e| panic!("golden time path {rendered:?} component {s:?}: {e}"))
    };
    assert_eq!(
        nanos.len(),
        9,
        "golden time path {rendered:?} must carry 9 fractional digits"
    );
    ((num(parts[0]) * 60 + num(parts[1])) * 60 + num(parts[2])) * 1_000_000_000 + num(nanos)
}

fn time_value(rendered: &str) -> Value {
    Value::Time(time_nanos(rendered))
}

/// Split a sstabledump tuple path on its FIRST unescaped `:` and unescape each
/// component. `2001\:db8\:...\:1:00\:00\:10.000000000` therefore splits into the
/// IPv6 address and the time, not on the address's own colons.
fn split_tuple_path(path: &str) -> (String, String) {
    let mut component = String::new();
    let mut chars = path.chars();
    let mut consumed = 0usize;
    while let Some(c) = chars.next() {
        consumed += c.len_utf8();
        match c {
            '\\' => match chars.next() {
                Some(escaped) => {
                    consumed += escaped.len_utf8();
                    component.push(escaped);
                }
                None => panic!("tuple path {path:?} ends in a dangling escape"),
            },
            ':' => {
                let rest = &path[consumed..];
                return (component, rest.replace("\\:", ":"));
            }
            other => component.push(other),
        }
    }
    panic!("tuple path {path:?} has no unescaped component separator")
}

/// `(inet, time)` frozen tuple, as `pair_set`'s element type declares it.
fn pair_value(path: &str) -> Value {
    let (addr, at) = split_tuple_path(path);
    Value::Frozen(Box::new(Value::Tuple(vec![
        inet_value(&addr),
        time_value(&at),
    ])))
}

// ===========================================================================
// The comparators, built from the DECLARED CQL types (schema-driven, #28) —
// never hand-picked variants.
// ===========================================================================

fn inet_comparator() -> ComparatorType {
    ComparatorType::from_cql_type(&CqlType::Inet).expect("inet comparator")
}

fn time_comparator() -> ComparatorType {
    ComparatorType::from_cql_type(&CqlType::Time).expect("time comparator")
}

/// `pair_set` is `SET<FROZEN<TUPLE<INET, TIME>>>`; the SET's ELEMENT comparator
/// is what orders the cell paths.
fn pair_comparator() -> ComparatorType {
    ComparatorType::from_cql_type(&CqlType::Frozen(Box::new(CqlType::Tuple(vec![
        CqlType::Inet,
        CqlType::Time,
    ]))))
    .expect("frozen tuple comparator")
}

// ===========================================================================
// The core assertion.
// ===========================================================================

/// Require `cmp` to make `values` a strictly increasing sequence, and require a
/// scrambled permutation of it to sort back onto it.
///
/// Pairwise-over-ALL-pairs, not just adjacent ones: an "always Equal" or
/// otherwise degenerate comparator satisfies a sort trivially (a sort of an
/// already-ordered slice is a no-op for a stable sort), so the sort alone would
/// be a vacuous pass.
fn assert_strict_order(cmp: &ComparatorType, values: &[Value], what: &str) {
    assert!(
        values.len() >= 2,
        "{what}: an ordering claim needs at least two values, got {}",
        values.len()
    );
    for i in 0..values.len() {
        for j in (i + 1)..values.len() {
            let fwd = cmp
                .compare(&values[i], &values[j])
                .unwrap_or_else(|e| panic!("{what}: compare({i},{j}) failed: {e}"));
            assert_eq!(
                fwd,
                Ordering::Less,
                "{what}: Cassandra wrote element {i} before element {j}, so the \
                 comparator must order them Less — got {fwd:?} for {:?} vs {:?}",
                values[i],
                values[j]
            );
            let rev = cmp
                .compare(&values[j], &values[i])
                .unwrap_or_else(|e| panic!("{what}: compare({j},{i}) failed: {e}"));
            assert_eq!(
                rev,
                Ordering::Greater,
                "{what}: the comparator must be antisymmetric"
            );
        }
    }

    // Deterministic scrambles — every rotation of the REVERSED sequence — so the
    // sort is doing real work rather than confirming an already-sorted slice.
    // (A two-element sequence has exactly one such scramble; the identity
    // rotation is filtered out rather than asserted away.)
    let reversed: Vec<Value> = values.iter().rev().cloned().collect();
    let scrambles: Vec<Vec<Value>> = (0..reversed.len())
        .map(|shift| {
            let mut p = reversed.clone();
            p.rotate_left(shift);
            p
        })
        .filter(|p| p != values)
        .collect();
    assert!(
        !scrambles.is_empty(),
        "{what}: no scramble differs from the expected order — the sort below \
         would be a no-op and prove nothing"
    );
    for mut scrambled in scrambles {
        scrambled.sort_by(|a, b| {
            cmp.compare(a, b)
                .unwrap_or_else(|e| panic!("{what}: sort compare failed: {e}"))
        });
        assert_eq!(
            scrambled, values,
            "{what}: sorting with ComparatorType must reproduce the order \
             Cassandra wrote on disk"
        );
    }
}

/// One column of one partition: cross-check the golden's file order against the
/// README oracle, then require the comparator to reproduce it.
fn assert_column(
    golden: &Golden,
    partition: &str,
    column: &str,
    oracle: &[&str],
    cmp: &ComparatorType,
    transcribe: fn(&str) -> Value,
) -> Vec<Value> {
    let observed = golden_order(golden, partition, column);
    assert_eq!(
        observed, oracle,
        "{column} (partition {partition}): the golden's on-disk cell-path order \
         no longer matches the README oracle. Either the golden was regenerated \
         or it is corrupt — resolve THAT before touching the comparator."
    );
    let values: Vec<Value> = observed.iter().map(|p| transcribe(p)).collect();
    assert_strict_order(cmp, &values, &format!("{column}/partition {partition}"));
    values
}

// ===========================================================================
// LEG 1 — the golden vs the comparator oracle.
// ===========================================================================

/// `inet` as a SET element and as a MAP key, both partitions.
///
/// This is the case that catches the LIVE defect: `9.0.0.1` before `10.0.0.2`
/// by bytes, the reverse by formatted string.
#[test]
fn leg1_golden_inet_order_is_reproduced_by_the_comparator() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let cmp = inet_comparator();
    for column in ["inet_set", "inet_map"] {
        assert_column(&golden, "1", column, ORACLE_INET_ROW1, &cmp, inet_value);
        assert_column(&golden, "2", column, ORACLE_INET_ROW2, &cmp, inet_value);
    }
}

/// The single pair the #3790 defect got wrong, asserted on its own so a failure
/// names it rather than hiding inside a six-element sequence.
#[test]
fn leg1_cassandra_puts_9_0_0_1_before_10_0_0_2() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    for column in ["inet_set", "inet_map"] {
        for partition in ["1", "2"] {
            let order = golden_order(&golden, partition, column);
            let nine = order
                .iter()
                .position(|p| p == "9.0.0.1")
                .unwrap_or_else(|| panic!("{column}/{partition}: 9.0.0.1 absent from the golden"));
            let ten = order
                .iter()
                .position(|p| p == "10.0.0.2")
                .unwrap_or_else(|| panic!("{column}/{partition}: 10.0.0.2 absent from the golden"));
            assert!(
                nine < ten,
                "{column}/partition {partition}: Cassandra wrote 9.0.0.1 (0x09…) \
                 BEFORE 10.0.0.2 (0x0a…); the golden says otherwise"
            );
        }
    }
    let cmp = inet_comparator();
    assert_eq!(
        cmp.compare(&inet_value("9.0.0.1"), &inet_value("10.0.0.2"))
            .expect("inet compare"),
        Ordering::Less,
        "the comparator must agree with the Cassandra-written order, not with \
         formatted-string order (\"10.0.0.2\" < \"9.0.0.1\" as text)"
    );
}

/// `time` as a SET element and as a MAP key, both partitions.
///
/// LATENT CASE — see the module docs. `fmt_time` is fixed-width and zero-padded,
/// so no valid `time` value falsifies the formatted-string implementation. This
/// is a value-order PIN over Cassandra-written bytes, not a demonstration of a
/// caught defect.
#[test]
fn leg1_golden_time_order_is_reproduced_by_the_comparator() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let cmp = time_comparator();
    for column in ["time_set", "time_map"] {
        assert_column(&golden, "1", column, ORACLE_TIME_ROW1, &cmp, time_value);
        assert_column(&golden, "2", column, ORACLE_TIME_ROW2, &cmp, time_value);
    }
}

/// `pair_set` — the composite case: `SET<FROZEN<TUPLE<INET, TIME>>>`, where the
/// scalar-leaf delegation of the tuple comparator is what decides the order.
#[test]
fn leg1_golden_composite_tuple_order_is_reproduced_by_the_comparator() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let cmp = pair_comparator();
    assert_column(&golden, "1", "pair_set", ORACLE_PAIR_ROW1, &cmp, pair_value);
    assert_column(&golden, "2", "pair_set", ORACLE_PAIR_ROW2, &cmp, pair_value);
}

/// `pair_set` is INET-MAJOR, TIME-MINOR, and both halves are load-bearing.
///
/// Partition 2 separates inet-major from time-major: on disk `9.0.0.1` at
/// `00:00:10` precedes `10.0.0.2` at `00:00:09`, so the time components run
/// BACKWARDS relative to the element order. Partition 1's entries 2 and 3 share
/// `10.0.0.2` and differ only in the time component, so the minor key decides
/// there.
#[test]
fn leg1_composite_is_inet_major_and_the_time_component_is_load_bearing() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let cmp = pair_comparator();

    // Inet-major: the first component decides AGAINST the time components' order.
    let row2 = golden_order(&golden, "2", "pair_set");
    assert_eq!(row2, ORACLE_PAIR_ROW2);
    let (first_addr, first_time) = split_tuple_path(&row2[0]);
    let (second_addr, second_time) = split_tuple_path(&row2[1]);
    assert_eq!(
        (first_addr.as_str(), second_addr.as_str()),
        ("9.0.0.1", "10.0.0.2")
    );
    assert!(
        time_nanos(&first_time) > time_nanos(&second_time),
        "partition 2's element order must run OPPOSITE to its time components, or \
         it cannot distinguish inet-major from time-major"
    );
    assert_eq!(
        cmp.compare(&pair_value(&row2[0]), &pair_value(&row2[1]))
            .expect("tuple compare"),
        Ordering::Less
    );

    // Time-minor: two entries sharing an inet are separated by the time alone.
    let row1 = golden_order(&golden, "1", "pair_set");
    let (a_addr, a_time) = split_tuple_path(&row1[1]);
    let (b_addr, b_time) = split_tuple_path(&row1[2]);
    assert_eq!(
        (a_addr.as_str(), b_addr.as_str()),
        ("10.0.0.2", "10.0.0.2"),
        "entries 2 and 3 must share an address for the minor key to be exercised"
    );
    assert!(time_nanos(&a_time) < time_nanos(&b_time));
    assert_eq!(
        cmp.compare(&pair_value(&row1[1]), &pair_value(&row1[2]))
            .expect("tuple compare"),
        Ordering::Less,
        "with the inet components equal, the time component must decide"
    );
}

// ===========================================================================
// LEG 1 negative controls — the assertions above have teeth.
//
// A green ordering test proves nothing unless the WRONG implementations are
// shown to produce a DIFFERENT answer. These cases construct the wrong orders
// explicitly and assert they diverge from the Cassandra-written one.
// ===========================================================================

/// Formatted-string order (the #3790 defect) does NOT reproduce the golden.
///
/// Three independent falsifying pairs, inverting in both the v4/v4 and the v4/v6
/// direction, so no single coincidence satisfies them all.
#[test]
fn negative_control_formatted_string_order_diverges_from_cassandra_for_inet() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let on_disk = golden_order(&golden, "1", "inet_set");

    let mut by_string: Vec<Value> = on_disk.iter().map(|p| inet_value(p)).collect();
    by_string.sort_by_key(|v| format!("{v}"));
    let expected: Vec<Value> = on_disk.iter().map(|p| inet_value(p)).collect();
    assert_ne!(
        by_string, expected,
        "if formatted-string order reproduced the Cassandra order, this fixture \
         could not catch the #3790 defect at all"
    );

    for (lo, hi) in [
        ("9.0.0.1", "10.0.0.2"),
        ("2001:db8:0:0:0:0:0:1", "192.168.0.1"),
        ("9.0.0.1", "2001:db8:0:0:0:0:0:1"),
    ] {
        let (lo_v, hi_v) = (inet_value(lo), inet_value(hi));
        assert_eq!(
            inet_comparator().compare(&lo_v, &hi_v).expect("compare"),
            Ordering::Less,
            "byte order: {lo} < {hi}"
        );
        assert!(
            format!("{lo_v}") > format!("{hi_v}"),
            "the pair must INVERT under formatted-string comparison, else it is \
             not a falsifier: {lo} vs {hi}"
        );
    }
}

/// `time`: the honest negative control.
///
/// There is deliberately NO formatted-string falsifier here — `fmt_time` is
/// fixed-width and zero-padded, so string order and nanosecond order coincide
/// over the whole valid range, and this case ASSERTS that coincidence rather
/// than pretending otherwise. What the fixture does falsify is a
/// DECIMAL-NANOSECOND string comparison, the other plausible wrong
/// implementation.
#[test]
fn negative_control_time_falsifies_decimal_nanos_strings_but_not_fmt_time() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let on_disk = golden_order(&golden, "1", "time_set");
    let expected: Vec<Value> = on_disk.iter().map(|p| time_value(p)).collect();

    // (a) fmt_time order COINCIDES with the on-disk order — the latency, stated.
    let mut by_fmt: Vec<Value> = expected.clone();
    by_fmt.sort_by_key(|v| format!("{v}"));
    assert_eq!(
        by_fmt, expected,
        "fmt_time is fixed-width and zero-padded, so string order and nanosecond \
         order coincide; a `time` value that falsified fmt_time would mean the \
         renderer changed, not that this test got stronger"
    );

    // (b) a DECIMAL-NANOSECOND string comparison IS falsified: 00:00:09 and
    //     00:00:10 are 9000000000 and 10000000000 nanos.
    let nine = time_nanos("00:00:09.000000000");
    let ten = time_nanos("00:00:10.000000000");
    assert_eq!(nine, 9_000_000_000);
    assert_eq!(ten, 10_000_000_000);
    assert!(
        nine.to_string() > ten.to_string(),
        "\"9…\" > \"10…\" as text"
    );
    assert_eq!(
        time_comparator()
            .compare(&Value::Time(nine), &Value::Time(ten))
            .expect("time compare"),
        Ordering::Less,
        "nanosecond (byte) order, not decimal-string order"
    );
}

/// A comparator that compared the WHOLE rendered tuple path as one string would
/// reverse partition 2's `pair_set`.
#[test]
fn negative_control_whole_tuple_path_string_order_diverges_from_cassandra() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let on_disk = golden_order(&golden, "2", "pair_set");
    let mut by_string = on_disk.clone();
    by_string.sort();
    assert_ne!(
        by_string, on_disk,
        "partition 2's pair_set must invert under whole-path string order, else \
         the composite case proves nothing about component-wise comparison"
    );
}

// ===========================================================================
// LEG 2 — CQLite reads the same order off the same Cassandra-written bytes.
//
// Read path: `SSTableReader::open` + `iterate_all_partitions_for_compaction`,
// which surfaces each complex column's per-element cells IN ON-DISK ORDER with
// their decoded values (`ComplexColumn::elements`) plus the collapsed
// `Value::Set`/`Value::Map` a consumer sees. Both are public and UNGATED, so
// this leg needs no feature flag and executes wherever the target does.
//
// WHAT THIS LEG IS AND IS NOT. On its own it would be weak: a path that emits
// cells in the order it read them prints the right sequence with or without the
// comparator fix (the fixture README says exactly this). Its value is closing
// the loop — Cassandra bytes -> CQLite decode -> CQLite comparator -> the order
// Cassandra wrote — and, specifically, PROVING Leg 1's transcription of the
// sstabledump text is the same value the bytes actually carry. Leg 1 remains the
// leg that satisfies AC3.
// ===========================================================================

use std::collections::BTreeMap;
use std::sync::Arc;

use cqlite_core::platform::Platform;
use cqlite_core::schema::TableSchema;
use cqlite_core::storage::sstable::reader::compaction_row::CompactionRowData;
use cqlite_core::storage::sstable::reader::SSTableReader;
use cqlite_core::Config;

/// The ORDERING values of one complex column as CQLite decoded them, in on-disk
/// order, from two independent surfaces of the same read.
struct DecodedColumn {
    /// Per-element: the SET element, or the MAP key — the value that IS the cell
    /// path and therefore the one Cassandra's comparator ordered by.
    per_element: Vec<Value>,
    /// The same ordering values taken from the collapsed `Value::Set`/`Map` the
    /// reader hands a consumer.
    collapsed: Vec<Value>,
}

/// `test_comparator_order.collection_order` parsed from its COMMITTED DDL —
/// authoritative schema, never inferred from the bytes (#28).
fn table_schema() -> TableSchema {
    let path =
        datasets_root::schema_path("issue-3790-comparator-ordering.cql").unwrap_or_else(|| {
            panic!(
                "committed schema issue-3790-comparator-ordering.cql is unreadable — it \
             is checkout-relative source (#3148), so this is a resolution defect, \
             never an absence"
            )
        });
    let ddl = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read committed schema {path:?}: {e}"));
    let lower = ddl.to_lowercase();
    let needle = format!("create table if not exists {TABLE}");
    let start = lower
        .find(&needle)
        .unwrap_or_else(|| panic!("CREATE TABLE {TABLE} not found in {path:?}"));
    let rest = &ddl[start..];
    let semi = rest
        .find(';')
        .unwrap_or_else(|| panic!("unterminated CREATE TABLE in {path:?}"));
    let stmt = rest[..=semi].replacen("IF NOT EXISTS ", "", 1);
    let (_, mut schema) = cqlite_core::schema::cql_parser::parse_create_table(&stmt)
        .unwrap_or_else(|e| panic!("parse CREATE TABLE {TABLE}: {e:?}"));
    schema.keyspace = KEYSPACE.to_string();
    schema.table = TABLE.to_string();
    schema
}

/// Decode every complex column of every partition of the real `Data.db`, keyed
/// by `(partition key as int string, column)`.
async fn decode_fixture() -> BTreeMap<(String, String), DecodedColumn> {
    let data_db = fixture_dir().join("nb-1-big-Data.db");
    assert!(
        data_db.is_file(),
        "the Cassandra-written {data_db:?} is committed and must_run (#3220)"
    );
    let config = Config::default();
    let platform = Arc::new(
        Platform::new(&config)
            .await
            .expect("platform init for the fixture read"),
    );
    let reader = SSTableReader::open(&data_db, &config, platform)
        .await
        .unwrap_or_else(|e| panic!("open {data_db:?}: {e}"));
    let schema = table_schema();
    let rows = reader
        .iterate_all_partitions_for_compaction(Some(&schema))
        .await
        .unwrap_or_else(|e| panic!("iterate {data_db:?}: {e}"));
    assert_eq!(
        rows.len(),
        2,
        "the fixture holds two partitions; decoding the present fixture to a \
         different row count is a hard failure, never a skip"
    );

    let mut out = BTreeMap::new();
    for row in &rows {
        let key = match row.key.0.as_ref() {
            [a, b, c, d] => i32::from_be_bytes([*a, *b, *c, *d]).to_string(),
            other => panic!("unexpected partition key width {}: {other:?}", other.len()),
        };
        let complex = match &row.row_data {
            CompactionRowData::Live { complex, .. } => complex,
            other => panic!("partition {key} did not decode as a live row: {other:?}"),
        };
        for column in complex {
            let per_element = column
                .elements
                .iter()
                .map(|e| ordering_value(&column.column, e.decoded_key.as_ref(), e.value.as_ref()))
                .collect();
            let collapsed = collapsed_ordering_values(&column.column, &column.collapsed_value);
            out.insert(
                (key.clone(), column.column.clone()),
                DecodedColumn {
                    per_element,
                    collapsed,
                },
            );
        }
    }
    out
}

/// The value a complex element is ORDERED BY: a MAP entry's decoded key, or a
/// SET member's decoded element (a set member carries the element in the cell
/// path and an empty cell value, which the reader surfaces as `value`).
///
/// Panics rather than falling back: an element with neither is a decode defect,
/// and silently skipping it would shorten the sequence into a vacuous pass.
fn ordering_value(column: &str, decoded_key: Option<&Value>, value: Option<&Value>) -> Value {
    match (decoded_key, value) {
        (Some(k), _) => k.clone(),
        (None, Some(v)) => v.clone(),
        (None, None) => panic!(
            "{column}: a complex element decoded to neither a map key nor an \
             element value"
        ),
    }
}

/// The same ordering values read off the collapsed whole-collection `Value`.
fn collapsed_ordering_values(column: &str, collapsed: &Value) -> Vec<Value> {
    match collapsed {
        Value::Set(xs) | Value::List(xs) => xs.clone(),
        Value::Map(kvs) => kvs.iter().map(|(k, _)| k.clone()).collect(),
        other => panic!("{column}: collapsed to a non-collection value: {other:?}"),
    }
}

/// One column of one partition, through the real reader.
fn assert_decoded_column(
    decoded: &BTreeMap<(String, String), DecodedColumn>,
    partition: &str,
    column: &str,
    expected: &[Value],
    cmp: &ComparatorType,
) {
    let got = decoded
        .get(&(partition.to_string(), column.to_string()))
        .unwrap_or_else(|| {
            panic!(
                "{column} is absent from decoded partition {partition} — the \
                 fixture IS present, so a missing column is a hard failure"
            )
        });
    assert!(
        !got.per_element.is_empty(),
        "{column}/partition {partition}: the fixture is present and decoded to \
         ZERO elements (0-rows-when-present must never pass)"
    );
    assert_eq!(
        got.per_element, expected,
        "{column}/partition {partition}: CQLite must decode the Cassandra-written \
         cells to the same values, in the same on-disk order, that the golden's \
         cell paths denote"
    );
    assert_eq!(
        got.collapsed, expected,
        "{column}/partition {partition}: the collapsed collection a consumer sees \
         must carry the same order as the per-element cells"
    );
    // The loop that matters: sort what CQLITE DECODED with CQLite's comparator
    // and land back on what CASSANDRA WROTE.
    assert_strict_order(
        cmp,
        &got.per_element,
        &format!("decoded {column}/partition {partition}"),
    );
}

/// `inet_set` / `inet_map` — the live-defect case, end to end over real bytes.
#[tokio::test]
async fn leg2_cqlite_decodes_the_cassandra_inet_order_from_the_real_data_db() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let decoded = decode_fixture().await;
    let cmp = inet_comparator();
    for column in ["inet_set", "inet_map"] {
        for partition in ["1", "2"] {
            let expected: Vec<Value> = golden_order(&golden, partition, column)
                .iter()
                .map(|p| inet_value(p))
                .collect();
            assert_decoded_column(&decoded, partition, column, &expected, &cmp);
        }
    }
}

/// `time_set` / `time_map` — the LATENT case (see the module docs): a value-order
/// pin over Cassandra-written bytes, not a caught misordering.
#[tokio::test]
async fn leg2_cqlite_decodes_the_cassandra_time_order_from_the_real_data_db() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let decoded = decode_fixture().await;
    let cmp = time_comparator();
    for column in ["time_set", "time_map"] {
        for partition in ["1", "2"] {
            let expected: Vec<Value> = golden_order(&golden, partition, column)
                .iter()
                .map(|p| time_value(p))
                .collect();
            assert_decoded_column(&decoded, partition, column, &expected, &cmp);
        }
    }
}

/// `pair_set` — the composite case decoded from real bytes as
/// `Frozen(Tuple([Inet, Time]))`, so the tuple comparator's scalar-leaf
/// delegation is exercised on values CQLite parsed rather than on values this
/// test constructed.
#[tokio::test]
async fn leg2_cqlite_decodes_the_cassandra_composite_order_from_the_real_data_db() {
    let golden = load_golden(&fixture_dir().join(GOLDEN_FILE));
    let decoded = decode_fixture().await;
    let cmp = pair_comparator();
    for partition in ["1", "2"] {
        let expected: Vec<Value> = golden_order(&golden, partition, "pair_set")
            .iter()
            .map(|p| pair_value(p))
            .collect();
        assert_decoded_column(&decoded, partition, "pair_set", &expected, &cmp);
    }
}
