//! Regression test for issue #1104: the compaction stitch path must honor
//! incompressible/raw chunks.
//!
//! Cassandra stores a compressed chunk RAW (uncompressed) when its compressed
//! length would meet/exceed `max_compressed_length` (the incompressible-chunk
//! fallback). The read/scan path (`stitch_all_chunks`) was taught this rule in
//! epic #970, but the compaction paths were not and blindly LZ4/Snappy/etc-decoded
//! every chunk, failing on a raw-stored chunk with e.g. "the offset to copy is
//! not contained in the decompressed buffer". There are TWO compaction read
//! paths and BOTH must honor the rule:
//!
//! - `iterate_all_partitions_for_compaction` -> `stitch_and_parse_all_chunks_for_compaction`
//!   (materializing variant)
//! - `stream_all_partitions_for_compaction` (the streaming variant the real
//!   k-way merge producer in `write_engine/merge.rs` actually drives)
//!
//! This test drives BOTH over the `test_comp/incompressible_uncompressed_chunk`
//! fixture (64 raw chunks + 1 compressed final chunk) and asserts each (a)
//! succeeds, (b) returns the full golden row count, and (c) decodes the raw
//! `payload` blobs byte-for-byte equal to the sstabledump golden — so a garbled
//! raw passthrough cannot pass on row count alone.
//!
//! The fixture's binary `Data.db` is generated by
//! `test-data/scripts/generate-compression-parity.sh` and is gitignored. When it
//! is absent the test SKIPs cleanly (mirrors issue_998); under
//! `CQLITE_REQUIRE_FIXTURES=1` (the strict compression-parity CI lane) a missing
//! binary is a hard failure instead.

use std::fs::{self, File};
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use cqlite_core::storage::scan_cancel::ScanCancel;
use cqlite_core::storage::sstable::reader::{CompactionRow, CompactionRowData, SSTableReader};
use cqlite_core::types::Value;
use cqlite_core::{Config, Platform};

const TABLE: &str = "incompressible_uncompressed_chunk";

/// `CQLITE_REQUIRE_FIXTURES=1` turns a missing binary into a hard failure (the
/// strict compression-parity CI lane that regenerates `test_comp`); otherwise a
/// missing binary is a clean skip (ordinary lanes without the gitignored
/// fixtures). Mirrors the convention in the other `test_comp` parity tests.
fn require_fixtures_strict() -> bool {
    std::env::var("CQLITE_REQUIRE_FIXTURES")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false)
}

/// Locate the test_comp dataset directory, honoring CQLITE_DATASETS_ROOT.
fn datasets_root() -> PathBuf {
    std::env::var("CQLITE_DATASETS_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .map(|p| p.join("test-data/datasets"))
                .unwrap_or_else(|| PathBuf::from("test-data/datasets"))
        })
}

/// Resolve the `<table>-<uuid>` directory that actually holds a `Data.db`
/// (no hardcoded UUID; the generator assigns a fresh UUID per run). Returns the
/// Data.db path, or None when absent so the caller SKIPs.
fn resolve_data_db(table: &str) -> Option<PathBuf> {
    let comp_dir = datasets_root().join("sstables/test_comp");
    if !comp_dir.is_dir() {
        return None;
    }
    let prefix = format!("{}-", table);
    for entry in fs::read_dir(&comp_dir).ok()?.flatten() {
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with(&prefix) && entry.path().is_dir() {
            let data_db = entry.path().join("nb-1-big-Data.db");
            if data_db.exists() {
                return Some(data_db);
            }
        }
    }
    None
}

/// Resolve the Data.db, honoring the strict/skip policy. Returns None (after
/// printing a SKIP) when the fixture is absent and strictness is off.
fn data_db_or_skip() -> Option<PathBuf> {
    if let Some(p) = resolve_data_db(TABLE) {
        return Some(p);
    }
    if require_fixtures_strict() {
        panic!(
            "CQLITE_REQUIRE_FIXTURES=1 but {} Data.db is absent under {} (run generate-compression-parity.sh)",
            TABLE,
            datasets_root().display()
        );
    }
    eprintln!(
        "SKIP[{}]: Data.db absent under {} (run generate-compression-parity.sh)",
        TABLE,
        datasets_root().display()
    );
    None
}

async fn open_reader(data_db: &Path) -> SSTableReader {
    let config = Config::default();
    let platform = Arc::new(Platform::new(&config).await.unwrap());
    SSTableReader::open(data_db, &config, platform)
        .await
        .expect("Failed to open incompressible-chunk SSTable")
}

/// Count `row` objects in an sstabledump JSONL golden. The dump is
/// partition-granular (one JSON object per partition, each carrying a `rows`
/// array), so a line count under-counts a single wide partition — count the
/// embedded `"type":"row"` markers instead.
fn count_golden_rows(path: &Path) -> std::io::Result<usize> {
    let file = File::open(path)?;
    let mut rows = 0usize;
    for line in BufReader::new(file).lines() {
        rows += line?.matches("\"type\":\"row\"").count();
    }
    Ok(rows)
}

/// Extract every `payload` cell value (lowercase hex, no `0x`) from the golden
/// JSONL. The fixture's only regular column is the incompressible `payload`
/// BLOB, rendered by sstabledump as `"name":"payload","value":"0x<hex>"`.
fn golden_payload_hex(path: &Path) -> std::io::Result<Vec<String>> {
    let text = fs::read_to_string(path)?;
    let mut out = Vec::new();
    let needle = "\"name\":\"payload\",\"value\":\"0x";
    let mut rest = text.as_str();
    while let Some(pos) = rest.find(needle) {
        let after = &rest[pos + needle.len()..];
        if let Some(end) = after.find('"') {
            out.push(after[..end].to_ascii_lowercase());
            rest = &after[end..];
        } else {
            break;
        }
    }
    out.sort();
    Ok(out)
}

/// Extract every decoded `payload` blob (lowercase hex) from a set of compaction
/// rows, sorted to form a multiset comparable with [`golden_payload_hex`].
fn rows_payload_hex(rows: &[CompactionRow]) -> Vec<String> {
    let mut out = Vec::new();
    for row in rows {
        if let CompactionRowData::Live { simple, .. } = &row.row_data {
            for cell in simple {
                if cell.column == "payload" {
                    if let Value::Blob(bytes) = &cell.value {
                        out.push(
                            bytes
                                .iter()
                                .map(|b| format!("{:02x}", b))
                                .collect::<String>(),
                        );
                    }
                }
            }
        }
    }
    out.sort();
    out
}

/// The materializing compaction path
/// (`iterate_all_partitions_for_compaction` -> `stitch_and_parse_all_chunks_for_compaction`).
#[tokio::test]
async fn issue_1104_iterate_compaction_over_incompressible_chunks() {
    let Some(data_db) = data_db_or_skip() else {
        return;
    };
    let reader = open_reader(&data_db).await;

    // Before #1104 this errored on the raw chunk with "LZ4 decompression failed:
    // the offset to copy is not contained in the decompressed buffer".
    let rows = reader
        .iterate_all_partitions_for_compaction(None)
        .await
        .unwrap_or_else(|e| {
            panic!(
                "[{}] iterate compaction path failed on incompressible/raw chunk (issue #1104): {}",
                TABLE, e
            )
        });

    assert_row_set_matches_golden(&data_db, &rows, "iterate");
}

/// The STREAMING compaction path (`stream_all_partitions_for_compaction`) — the
/// one the real k-way merge producer in `write_engine/merge.rs` drives. This is
/// the production path; a fix that only patched the materializing variant would
/// leave real compaction broken on incompressible SSTables.
#[tokio::test]
async fn issue_1104_stream_compaction_over_incompressible_chunks() {
    let Some(data_db) = data_db_or_skip() else {
        return;
    };
    let reader = open_reader(&data_db).await;

    let collected: Arc<Mutex<Vec<CompactionRow>>> = Arc::new(Mutex::new(Vec::new()));
    let sink = Arc::clone(&collected);
    reader
        .stream_all_partitions_for_compaction(None, &ScanCancel::default(), None, move |row| {
            sink.lock().unwrap().push(row);
            Ok(std::ops::ControlFlow::Continue(()))
        })
        .await
        .unwrap_or_else(|e| {
            panic!(
                "[{}] streaming compaction path failed on incompressible/raw chunk (issue #1104): {}",
                TABLE, e
            )
        });

    let rows = Arc::try_unwrap(collected)
        .expect("no outstanding refs")
        .into_inner()
        .unwrap();

    assert_row_set_matches_golden(&data_db, &rows, "stream");

    // The streaming (production) and materializing paths must agree exactly.
    let iter_rows = reader
        .iterate_all_partitions_for_compaction(None)
        .await
        .expect("iterate path");
    assert_eq!(
        rows, iter_rows,
        "[{}] streaming and materializing compaction paths disagree",
        TABLE
    );
}

/// Shared assertions: non-empty, golden row-count parity, and byte-for-byte
/// `payload` blob parity against the sstabledump golden.
fn assert_row_set_matches_golden(data_db: &Path, rows: &[CompactionRow], path_label: &str) {
    assert!(
        !rows.is_empty(),
        "[{}/{}] compaction path returned 0 rows on a valid SSTable",
        TABLE,
        path_label
    );

    let jsonl = data_db.with_file_name("nb-1-big-Data.db.jsonl");
    if !jsonl.exists() {
        return;
    }

    let expected = count_golden_rows(&jsonl).expect("read golden JSONL");
    assert_eq!(
        rows.len(),
        expected,
        "[{}/{}] compaction path produced {} rows; golden JSONL has {}",
        TABLE,
        path_label,
        rows.len(),
        expected
    );

    // Value-level correctness: the raw-stored chunks ARE the payload bytes, so a
    // garbled raw passthrough would corrupt these even if the row count matched.
    let golden = golden_payload_hex(&jsonl).expect("read golden payloads");
    let actual = rows_payload_hex(rows);
    assert!(
        !golden.is_empty(),
        "[{}/{}] golden JSONL had no payload cells to compare",
        TABLE,
        path_label
    );
    assert_eq!(
        actual, golden,
        "[{}/{}] decoded payload blobs do not match the golden (raw chunk decoded incorrectly)",
        TABLE, path_label
    );
}
