//! Issue #1190 (epic #969): whole-artifact byte parity of CQLite writer output
//! against committed Cassandra 5.0.2-written reference SSTables.
//!
//! This is the FIRST test that diffs a *finished* CQLite-written SSTable
//! file-vs-file against a Cassandra-written reference for the same logical
//! schema/data (not a derived-value invariant, not a round-trip). It backs the
//! upgrade of two `write_load_path` parity-manifest scenarios from `partial` to
//! `byte_for_byte`:
//!
//!   * cass.write_load_path.cql_sstable_writer.finished_data_db_artifacts
//!     → `finished_data` (int PK, one text col): a finished Data.db artifact.
//!   * cass.write_load_path.flush.partition_boundary_artifacts
//!     → `partition_boundary` (int PK, int CK, text col; two partitions, several
//!     clustering rows each): partition-boundary Data.db + Index.db layout.
//!
//! The reference fixtures are generated by
//! `test-data/scripts/generate-write-load-parity.sh` (Cassandra 5.0.2, sha
//! f278f6774fc76465c182041e081982105c3e7dbb) and committed under
//! `test-data/datasets/sstables/test_writeparity/`. CQLite re-emits the exact
//! same logical input (same fixed writetime `T_WRITE`, same int keys, same text
//! values) via `SSTableWriter` and the bytes are compared.
//!
//! DETERMINISM CONTRACT (why two independent writers can byte-match):
//!   * Every cell uses the single fixed writetime `T_WRITE`, so the
//!     EncodingStats.minTimestamp delta baseline is identical (verified by the
//!     committed `*-Statistics.db.txt`: `EncodingStats minTimestamp: 1700000000000000`).
//!   * Tables are UNCOMPRESSED, so Data.db is a direct byte slice (no chunk
//!     framing differences).
//!   * Partition keys are int / (int,int): identical 4-byte big-endian key
//!     bytes and identical token ordering on both writers.
//!   * No TTL and no DELETE in these two tables. TTL/DELETE `localDeletionTime`
//!     is wall-clock-derived (`nowInSeconds`) and CANNOT byte-match across two
//!     independent writers — that is why the tombstone/TTL scenario stays
//!     `partial` (its byte SHAPE is anchored by issue_764 / issue_821 against
//!     derived expected values, not a whole-artifact diff).
//!
//! WHICH COMPONENTS ARE BYTE-FOR-BYTE (verified empirically against the
//! committed reference):
//!   * Data.db, Index.db, Summary.db, Digest.crc32 → BYTE-IDENTICAL. These are
//!     the data artifact, the partition/row offset table, the summary index, and
//!     the whole-file CRC32. They are diffed byte-for-byte here; any mismatch
//!     FAILS. This is the byte parity backing the scenario upgrades.
//!   * Filter.db and Statistics.db → NOT byte-comparable across two independent
//!     writers: Filter.db embeds implementation-specific bloom-filter sizing
//!     (bucket count / hash count), and Statistics.db embeds metadata histograms,
//!     cardinality (HyperLogLog), and host/encoding bookkeeping. CQLite emits
//!     both, but their bytes are an implementation detail, not a parity target.
//!     Their semantic content is covered elsewhere (Filter membership, Statistics
//!     min/max/EncodingStats are anchored by issue_764 / issue_821).
//!   * CRC.db → KNOWN WRITER GAP: Cassandra emits an (uncompressed-chunk) CRC.db
//!     component even for uncompressed BIG SSTables; CQLite's writer does not yet
//!     emit it (the READ side recognizes it — see
//!     cass.sstable_format.toc_component_manifest). This is a real
//!     component-completeness gap recorded as a pinned reference-only assertion
//!     below (the reference HAS CRC.db, CQLite does NOT). It is tracked as a
//!     separate writer issue; it does not affect any emitted file's bytes.
//!
//! Dataset-dependency doctrine (issue #719 / parity mandate):
//!   * If `CQLITE_DATASETS_ROOT` is unset OR the reference Data.db is genuinely
//!     absent (binaries not fetched), the test SKIPS (returns early with a note).
//!   * If the reference is PRESENT but empty / 0-rows, that is a FAILURE — a
//!     present-but-empty fixture must never silently pass.

#![cfg(feature = "write-support")]

use cqlite_core::schema::{Column, ClusteringColumn, ClusteringOrder, KeyColumn, TableSchema};
use cqlite_core::storage::sstable::writer::{SSTableFormat, SSTableWriter};
use cqlite_core::storage::write_engine::mutation::{
    CellOperation, ClusteringKey, DecoratedKey, Mutation, PartitionKey, TableId,
};
use cqlite_core::types::Value;
use std::collections::{BTreeSet, HashMap};
use std::path::{Path, PathBuf};
use tempfile::TempDir;

/// The single fixed writetime (micros). MUST match the `T_WRITE` constant in
/// `test-data/scripts/generate-write-load-parity.sh`.
const T_WRITE: i64 = 1_700_000_000_000_000;

const KEYSPACE: &str = "test_writeparity";

// ---------------------------------------------------------------------------
// Fixture resolution (skip-on-absence; present-but-empty is a failure)
// ---------------------------------------------------------------------------

/// Resolve the committed Cassandra reference directory for `table` under
/// `test_writeparity`. Returns `None` when the dataset root is unset or the
/// table's reference SSTable has not been fetched (genuine absence → skip).
fn reference_dir(table: &str) -> Option<PathBuf> {
    let root = std::env::var("CQLITE_DATASETS_ROOT").ok()?;
    let base = Path::new(&root).join("sstables").join(KEYSPACE);
    let entries = std::fs::read_dir(&base).ok()?;
    for e in entries.flatten() {
        let name = e.file_name().to_string_lossy().to_string();
        if name.starts_with(&format!("{table}-")) {
            let dir = e.path();
            // Genuine absence = no Data.db committed/fetched yet.
            if dir.join("nb-1-big-Data.db").is_file() {
                return Some(dir);
            }
            return None;
        }
    }
    None
}

/// Read a reference component file. Panics if a *present* reference directory is
/// missing a component (a fetched-but-broken fixture is a real failure, never a
/// silent skip).
fn read_component(dir: &Path, suffix: &str) -> Vec<u8> {
    let path = dir.join(format!("nb-1-big-{suffix}"));
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!("reference component {path:?} unreadable in a present fixture: {e}")
    })
}

// ---------------------------------------------------------------------------
// CQLite writer harness
// ---------------------------------------------------------------------------

/// Write `mutations` for `schema` through the real `SSTableWriter` (BIG/nb,
/// uncompressed) and return the finished component directory.
async fn cqlite_write(schema: &TableSchema, mutations: Vec<Mutation>) -> (TempDir, PathBuf) {
    let dir = TempDir::new().expect("tempdir");
    let mut writer =
        SSTableWriter::with_format(dir.path().to_path_buf(), 1, schema, 16, SSTableFormat::Big)
            .expect("writer");

    // Decorate and group by partition key in ascending token order (the writer
    // requires strict token ordering and one write_partition call per key).
    let mut keyed: Vec<(DecoratedKey, Mutation)> = mutations
        .into_iter()
        .map(|m| (m.decorated_key(schema).expect("decorated key"), m))
        .collect();
    keyed.sort_by_key(|(k, _)| k.token);

    let mut grouped: Vec<(DecoratedKey, Vec<Mutation>)> = Vec::new();
    for (k, m) in keyed {
        match grouped.last_mut() {
            Some((lk, ms)) if lk.token == k.token && lk.key == k.key => ms.push(m),
            _ => grouped.push((k, vec![m])),
        }
    }
    for (k, ms) in grouped {
        writer.write_partition(k, ms).expect("write_partition");
    }
    let info = writer.finish().await.expect("finish");
    let table_dir = info
        .data_path
        .parent()
        .expect("data parent")
        .to_path_buf();
    (dir, table_dir)
}

/// Set of component suffixes present in a directory (strips the `nb-1-big-`
/// descriptor prefix so CQLite (`nb-1-big-`) and Cassandra (`nb-1-big-`) compare
/// on the logical component name).
fn component_suffixes(dir: &Path) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    if let Ok(rd) = std::fs::read_dir(dir) {
        for e in rd.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            if let Some(idx) = name.find("-big-") {
                set.insert(name[idx + 5..].to_string());
            } else if name.contains("TOC") {
                set.insert("TOC.txt".to_string());
            }
        }
    }
    // Drop derived/golden sidecars that only exist in the committed reference
    // tree (not emitted by either writer): JSONL + sstablemetadata text.
    set.retain(|s| !s.ends_with(".jsonl") && !s.ends_with("Statistics.db.txt"));
    set
}

/// TOC.txt content as a set of trimmed non-empty component lines.
fn toc_set(toc_bytes: &[u8]) -> BTreeSet<String> {
    String::from_utf8_lossy(toc_bytes)
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect()
}

/// First differing byte index, if any.
fn first_diff(a: &[u8], b: &[u8]) -> Option<usize> {
    let n = a.len().max(b.len());
    (0..n).find(|&i| a.get(i) != b.get(i))
}

// ---------------------------------------------------------------------------
// Schemas (exactly the schema/data the generator writes)
// ---------------------------------------------------------------------------

fn finished_schema() -> TableSchema {
    TableSchema {
        keyspace: KEYSPACE.into(),
        table: "finished_data".into(),
        partition_keys: vec![KeyColumn {
            name: "id".into(),
            data_type: "int".into(),
            position: 0,
        }],
        clustering_keys: vec![],
        columns: vec![
            Column {
                name: "id".into(),
                data_type: "int".into(),
                nullable: false,
                default: None,
                is_static: false,
            },
            Column {
                name: "name".into(),
                data_type: "text".into(),
                nullable: true,
                default: None,
                is_static: false,
            },
        ],
        comments: HashMap::new(),
        dropped_columns: HashMap::new(),
    }
}

fn partition_boundary_schema() -> TableSchema {
    TableSchema {
        keyspace: KEYSPACE.into(),
        table: "partition_boundary".into(),
        partition_keys: vec![KeyColumn {
            name: "id".into(),
            data_type: "int".into(),
            position: 0,
        }],
        clustering_keys: vec![ClusteringColumn {
            name: "ck".into(),
            data_type: "int".into(),
            position: 0,
            order: ClusteringOrder::Asc,
        }],
        columns: vec![
            Column {
                name: "id".into(),
                data_type: "int".into(),
                nullable: false,
                default: None,
                is_static: false,
            },
            Column {
                name: "ck".into(),
                data_type: "int".into(),
                nullable: false,
                default: None,
                is_static: false,
            },
            Column {
                name: "v".into(),
                data_type: "text".into(),
                nullable: true,
                default: None,
                is_static: false,
            },
        ],
        comments: HashMap::new(),
        dropped_columns: HashMap::new(),
    }
}

fn finished_mutations() -> Vec<Mutation> {
    (0..6)
        .map(|i| {
            Mutation::new(
                TableId::new(KEYSPACE, "finished_data"),
                PartitionKey::single("id", Value::Integer(i)),
                None,
                vec![CellOperation::Write {
                    column: "name".into(),
                    value: Value::Text(format!("name{i}")),
                }],
                T_WRITE,
                None,
            )
        })
        .collect()
}

fn partition_boundary_mutations() -> Vec<Mutation> {
    let mut muts = Vec::new();
    for ck in 1..=4 {
        muts.push(Mutation::new(
            TableId::new(KEYSPACE, "partition_boundary"),
            PartitionKey::single("id", Value::Integer(1)),
            Some(ClusteringKey::single("ck", Value::Integer(ck))),
            vec![CellOperation::Write {
                column: "v".into(),
                value: Value::Text(format!("v_1_{ck}")),
            }],
            T_WRITE,
            None,
        ));
    }
    for ck in 1..=2 {
        muts.push(Mutation::new(
            TableId::new(KEYSPACE, "partition_boundary"),
            PartitionKey::single("id", Value::Integer(2)),
            Some(ClusteringKey::single("ck", Value::Integer(ck))),
            vec![CellOperation::Write {
                column: "v".into(),
                value: Value::Text(format!("v_2_{ck}")),
            }],
            T_WRITE,
            None,
        ));
    }
    muts
}

// ---------------------------------------------------------------------------
// Shared whole-artifact byte-parity assertion
// ---------------------------------------------------------------------------

/// Diff a CQLite-written SSTable against the Cassandra reference for `table`:
/// component presence, TOC.txt, full Data.db bytes, full Index.db bytes (the
/// partition/row offset table), AND the committed sstabledump JSONL golden
/// (non-empty / expected partition count). Any mismatch FAILS.
///
/// `expected_jsonl_partitions` is the number of partitions the committed JSONL
/// golden must contain (present-but-empty / wrong-count is a failure).
async fn assert_byte_parity(
    table: &str,
    schema: TableSchema,
    mutations: Vec<Mutation>,
    expected_jsonl_partitions: usize,
) {
    let Some(ref_dir) = reference_dir(table) else {
        eprintln!(
            "[issue_1190] reference for {KEYSPACE}.{table} absent (dataset not fetched); skipping"
        );
        return;
    };

    let (_guard, out_dir) = cqlite_write(&schema, mutations).await;

    // 1. Component presence: every component CQLite emits must be present in the
    //    reference (no spurious CQLite-only component), and the byte-parity data
    //    components must be present on BOTH sides.
    let ref_components = component_suffixes(&ref_dir);
    let our_components = component_suffixes(&out_dir);
    assert!(
        !ref_components.is_empty(),
        "{table}: reference component set is empty (broken fixture)"
    );
    for needed in ["Data.db", "Index.db", "Summary.db", "Digest.crc32", "Statistics.db", "Filter.db", "TOC.txt"] {
        assert!(
            ref_components.contains(needed),
            "{table}: reference missing required component {needed}; have {ref_components:?}"
        );
        assert!(
            our_components.contains(needed),
            "{table}: CQLite output missing component {needed}; have {our_components:?}"
        );
    }
    // Pinned KNOWN GAP: Cassandra emits CRC.db for uncompressed BIG SSTables;
    // CQLite's writer does not yet. If this ever flips (CQLite starts emitting
    // CRC.db), this assertion fails and forces a manifest review — we must never
    // silently claim component-set parity while a component is missing.
    assert!(
        ref_components.contains("CRC.db"),
        "{table}: reference unexpectedly lacks CRC.db (regenerate fixtures?)"
    );
    assert!(
        !our_components.contains("CRC.db"),
        "{table}: CQLite now emits CRC.db — the known writer gap is closed; \
         re-evaluate write_load_path component-set parity in the manifest"
    );

    // 2. TOC.txt: every component CQLite lists must match the reference TOC; the
    //    only allowed difference is the known-missing CRC.db line.
    let ref_toc = toc_set(&read_component(&ref_dir, "TOC.txt"));
    let our_toc = toc_set(&std::fs::read(out_dir.join("nb-1-big-TOC.txt")).expect("our TOC"));
    let ref_toc_no_crc: BTreeSet<String> =
        ref_toc.iter().filter(|c| *c != "CRC.db").cloned().collect();
    assert_eq!(
        ref_toc_no_crc, our_toc,
        "{table}: TOC.txt component set differs beyond the known CRC.db gap \
         (cass-minus-CRC={ref_toc_no_crc:?} ours={our_toc:?})"
    );

    // 3. Data.db: full byte equality (row layout, headers, offsets, cells).
    assert_component_bytes(table, &ref_dir, &out_dir, "Data.db");

    // 4. Index.db: full byte equality (partition key + Data.db offset table =
    //    the partition/row-offset layout). This is the partition-boundary check.
    assert_component_bytes(table, &ref_dir, &out_dir, "Index.db");

    // 5. Summary.db + Digest.crc32: full byte equality (summary offset index and
    //    whole-file CRC32). Completes the deterministic byte-parity component set.
    assert_component_bytes(table, &ref_dir, &out_dir, "Summary.db");
    assert_component_bytes(table, &ref_dir, &out_dir, "Digest.crc32");

    // 6. sstabledump JSONL golden: must exist, be non-empty, and contain exactly
    //    the expected partition count. Present-but-empty / 0-rows is a failure.
    let jsonl = ref_dir.join("nb-1-big-Data.db.jsonl");
    let jsonl_text = std::fs::read_to_string(&jsonl)
        .unwrap_or_else(|e| panic!("{table}: committed JSONL golden {jsonl:?} unreadable: {e}"));
    let partitions: Vec<&str> = jsonl_text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect();
    assert!(
        !partitions.is_empty(),
        "{table}: committed JSONL golden is present-but-empty (0 partitions) — parity failure"
    );
    assert_eq!(
        partitions.len(),
        expected_jsonl_partitions,
        "{table}: JSONL golden partition count {} != expected {expected_jsonl_partitions}",
        partitions.len()
    );
    for (i, line) in partitions.iter().enumerate() {
        let v: serde_json::Value = serde_json::from_str(line)
            .unwrap_or_else(|e| panic!("{table}: JSONL partition {i} is not valid JSON: {e}"));
        let rows = v.get("rows").and_then(|r| r.as_array());
        assert!(
            rows.is_some_and(|r| !r.is_empty()),
            "{table}: JSONL partition {i} has no rows — parity failure"
        );
    }
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// Assert a CQLite-written component byte-matches the Cassandra reference.
/// Present-but-empty reference is a failure; any byte mismatch FAILS with a
/// first-diff report.
fn assert_component_bytes(table: &str, ref_dir: &Path, out_dir: &Path, suffix: &str) {
    let reference = read_component(ref_dir, suffix);
    let ours = std::fs::read(out_dir.join(format!("nb-1-big-{suffix}")))
        .unwrap_or_else(|e| panic!("{table}: CQLite {suffix} unreadable: {e}"));
    assert!(
        !reference.is_empty(),
        "{table}: reference {suffix} is present-but-empty — parity failure"
    );
    if reference != ours {
        let at = first_diff(&reference, &ours);
        panic!(
            "{table}: {suffix} byte mismatch (cass={} ours={} bytes, first diff at {:?})\n  cass={}\n  ours={}",
            reference.len(),
            ours.len(),
            at,
            hex(&reference),
            hex(&ours),
        );
    }
}

// ---------------------------------------------------------------------------
// Scenario 1: finished_data_db_artifacts — finished Data.db artifact.
// ---------------------------------------------------------------------------

/// Whole-artifact byte parity: CQLite's finished `finished_data` SSTable
/// (Data.db / Index.db / TOC.txt / components) is byte-identical to the
/// Cassandra 5.0.2 reference, and the committed JSONL golden has the 6 written
/// partitions. Backs
/// `cass.write_load_path.cql_sstable_writer.finished_data_db_artifacts`.
#[tokio::test]
async fn finished_data_db_artifacts_byte_for_byte() {
    assert_byte_parity("finished_data", finished_schema(), finished_mutations(), 6).await;
}

// ---------------------------------------------------------------------------
// Scenario 2: partition_boundary_artifacts — partition/row offset layout.
// ---------------------------------------------------------------------------

/// Whole-artifact byte parity: CQLite's finished `partition_boundary` SSTable
/// (multi-partition, multi-clustering-row) is byte-identical to the Cassandra
/// 5.0.2 reference, including the Index.db partition/row-offset table, and the
/// committed JSONL golden has the 2 written partitions. Backs
/// `cass.write_load_path.flush.partition_boundary_artifacts`.
#[tokio::test]
async fn partition_boundary_artifacts_byte_for_byte() {
    assert_byte_parity(
        "partition_boundary",
        partition_boundary_schema(),
        partition_boundary_mutations(),
        2,
    )
    .await;
}
