/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the version of the cqlite-node binding. */
export declare function version(): string
/**
 * Database handle for CQLite SSTable access.
 *
 * Placeholder implementation - full API will be implemented in Phase 2.
 *
 * ## Thread Safety (Phase 2)
 *
 * - Database handles will be thread-safe for use across worker threads
 * - Close operations will be idempotent
 * - Async operations integrate with Node.js event loop via napi's tokio_rt
 */
export declare class Database {
  /**
   * Opens a database at the specified data directory.
   *
   * `data_dir` - Path to the SSTable data directory
   *
   * Currently throws "Not yet implemented - Phase 2" error.
   */
  static open(dataDir: string): Database
}
