#!/usr/bin/env bash
#
# gen-homebrew-formula.sh — render the Homebrew formula for the cqlite CLI.
#
# Downloads the four per-platform `.sha256` checksum sidecars attached to a
# given release tag and emits a `cqlite` formula pinned to that version. Used
# both to bootstrap the pmcfadin/homebrew-cqlite tap by hand and by the
# release workflow (.github/workflows/release.yml) to keep the tap current.
#
# Usage:
#   scripts/gen-homebrew-formula.sh <version> [output-path]
#
#   <version>      release version WITHOUT the leading 'v' (e.g. 0.11.0)
#   [output-path]  where to write the formula (default: Formula/cqlite.rb)
#
# The release at v<version> must already have the platform tarballs and their
# `.sha256` sidecars uploaded, or this script fails (it never invents a hash).
set -euo pipefail

VERSION="${1:-}"
OUT="${2:-Formula/cqlite.rb}"

if [[ -z "$VERSION" ]]; then
  echo "usage: $0 <version> [output-path]   # version without leading 'v'" >&2
  exit 1
fi
# Reject a leading 'v' so callers can't accidentally double it in URLs.
if [[ "$VERSION" == v* ]]; then
  echo "error: pass the version without a leading 'v' (got '$VERSION')" >&2
  exit 1
fi

BASE_URL="https://github.com/pmcfadin/cqlite/releases/download/v${VERSION}"

# Homebrew platform block -> release target triple. Order matters only for
# readability; each maps to one url/sha256 pair in the formula.
MAC_ARM_TARGET="aarch64-apple-darwin"
MAC_INTEL_TARGET="x86_64-apple-darwin"
LINUX_ARM_TARGET="aarch64-unknown-linux-gnu"
LINUX_INTEL_TARGET="x86_64-unknown-linux-gnu"

# Fetch and validate the SHA-256 for one target's tarball. The sidecar holds
# the standard "<hash>  <filename>" line; we take the hash field only.
fetch_sha() {
  local target="$1"
  local url="${BASE_URL}/cqlite-${target}.tar.gz.sha256"
  local line
  if ! line="$(curl -fsSL "$url")"; then
    echo "error: could not download checksum for $target ($url)" >&2
    exit 1
  fi
  local hash="${line%% *}"
  if [[ ! "$hash" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: unexpected checksum content for $target: '$line'" >&2
    exit 1
  fi
  printf '%s' "$hash"
}

MAC_ARM_SHA="$(fetch_sha "$MAC_ARM_TARGET")"
MAC_INTEL_SHA="$(fetch_sha "$MAC_INTEL_TARGET")"
LINUX_ARM_SHA="$(fetch_sha "$LINUX_ARM_TARGET")"
LINUX_INTEL_SHA="$(fetch_sha "$LINUX_INTEL_TARGET")"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# typed: strict
# frozen_string_literal: true

# Homebrew formula for the cqlite CLI — a local Apache Cassandra SSTable reader.
# Generated by scripts/gen-homebrew-formula.sh in pmcfadin/cqlite; do not edit by
# hand. Each release tag refreshes the version and the per-platform checksums.
class Cqlite < Formula
  desc "Local Apache Cassandra SSTable reader CLI"
  homepage "https://github.com/pmcfadin/cqlite"
  license "Apache-2.0"
  # version is scanned from the release URL path (v${VERSION}); see Homebrew audit.

  on_macos do
    on_arm do
      url "${BASE_URL}/cqlite-${MAC_ARM_TARGET}.tar.gz"
      sha256 "${MAC_ARM_SHA}"
    end
    on_intel do
      url "${BASE_URL}/cqlite-${MAC_INTEL_TARGET}.tar.gz"
      sha256 "${MAC_INTEL_SHA}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/cqlite-${LINUX_ARM_TARGET}.tar.gz"
      sha256 "${LINUX_ARM_SHA}"
    end
    on_intel do
      url "${BASE_URL}/cqlite-${LINUX_INTEL_TARGET}.tar.gz"
      sha256 "${LINUX_INTEL_SHA}"
    end
  end

  def install
    bin.install "cqlite"
  end

  test do
    assert_match "cqlite", shell_output("#{bin}/cqlite --help")
  end
end
EOF

echo "wrote $OUT (cqlite ${VERSION})" >&2
