#!/usr/bin/env python3
"""extract-corruption-oracle.py — project the HUMAN-AUTHORED oracle fields out of
corruption-manifest.yml (issue #1294 Item 2).

WHY
---
The compression/corruption-parity CI lane REGENERATES corruption-manifest.yml from
generate-corruption-corpus.sh before running the parity tests. The generator hard-
codes the Cassandra-verdict oracle in its FIXTURES table, so a PR that edits ONLY a
committed oracle field (a captured cassandra_verdict, a verdict_parity, an
expected_error_class, a captured-against sha, ...) would be SILENTLY OVERWRITTEN at
CI time — the tests would then run against the script's hard-coded oracle instead of
the committed change. The CI guard diffs this projection of the COMMITTED manifest
against the same projection of the REGENERATED manifest and fails on any drift, so a
human-committed oracle edit is authoritative, not silently regenerated away.

WHAT IS PROJECTED (the authoritative, human-edited oracle — deterministic, NOT
regeneration-dependent):
  name, manifest_key, status, component, expected_failing_component,
  expected_error_class, rationale, cassandra_verdict, verdict_parity, verdict_note,
  verdict_captured_for_sha256, verdict_captured_for_dir_sha256, verdict_byte_stable

WHAT IS DELIBERATELY EXCLUDED (legitimately drifts when the clean SOURCES are
regenerated by the cassandra:5.0.2 container — NOT human-authored oracle):
  corrupted_sha256, original_sha256, fixture_dir_sha256, *_size_bytes,
  byte_offset, *_bytes_hex, clean_source_path (regenerated table UUID),
  corrupted_path. (corrupted_sha256 / fixture_dir_sha256 are the OBSERVED bytes;
  verdict_captured_for_* are the human-pinned BINDINGS the verdict was captured
  against, which IS oracle and IS projected.)

Usage:
  extract-corruption-oracle.py <manifest.yml>     # prints the canonical projection
Reads the manifest from a path, or from stdin when the path is '-'.
"""
import sys
import re

# Ordered list of oracle keys to project (stable output ordering).
ORACLE_KEYS = [
    "manifest_key",
    "status",
    "component",
    "expected_failing_component",
    "expected_error_class",
    "rationale",
    "cassandra_verdict",
    "verdict_parity",
    "verdict_note",
    "verdict_captured_for_sha256",
    "verdict_captured_for_dir_sha256",
    "verdict_byte_stable",
]


def main() -> int:
    if len(sys.argv) != 2:
        sys.stderr.write("usage: extract-corruption-oracle.py <manifest.yml|->\n")
        return 2
    src = sys.argv[1]
    txt = sys.stdin.read() if src == "-" else open(src, encoding="utf-8").read()

    # Split into per-fixture blocks (the manifest is a flat list of fixtures).
    blocks = re.split(r"\n  - name: ", txt)
    out_lines = []
    for b in blocks[1:]:
        name = b.splitlines()[0].strip()
        out_lines.append(f"fixture: {name}")

        def field(key: str) -> str:
            m = re.search(rf"^    {re.escape(key)}: (.*)$", b, re.M)
            if not m:
                return "<absent>"
            # Normalize: strip surrounding quotes + trailing whitespace so a
            # quoting/whitespace-only change is not flagged as an oracle drift.
            return m.group(1).strip().strip('"')

        for k in ORACLE_KEYS:
            out_lines.append(f"  {k}: {field(k)}")

    # Sort fixtures by name so manifest ordering changes do not cause spurious
    # diffs; within a fixture the key order is the fixed ORACLE_KEYS order.
    # Re-group: each fixture starts with a "fixture: " line.
    fixtures = []
    cur = []
    for ln in out_lines:
        if ln.startswith("fixture: ") and cur:
            fixtures.append(cur)
            cur = []
        cur.append(ln)
    if cur:
        fixtures.append(cur)
    fixtures.sort(key=lambda blk: blk[0])
    for blk in fixtures:
        print("\n".join(blk))
    return 0


if __name__ == "__main__":
    sys.exit(main())
