#!/usr/bin/env python3
"""Deterministic row driver for the issue-#3234 BTI (`da`) perf corpus.

Emits ONE chunk of CSV rows for `<keyspace>.<table>(pk, bucket, seq, payload)`
plus a one-line JSON *plan record* describing exactly what it emitted.

Why a recorded seed instead of `cassandra-stress` (the shape
`gen-perf-corpus-3068.sh` uses): `cassandra-stress`'s row values are not
reproducible from anything a manifest can record, so a regenerated corpus can
only ever be compared on aggregate counts. A recorded seed makes the ROW SET
itself reproducible, which is what lets the manifest's per-`Data.db` sha256 mean
something for a corpus nobody commits. See the generator's header.

Determinism contract:

* NOTHING here depends on the standard library's random module. The bit source
  (:class:`Mt19937`), the weighted width draw (:func:`weighted_choice`) and the
  bucket sampling (:func:`sample_without_replacement`) are all VENDORED in this
  file, with fixed algorithms, so chunk N of a given seed is byte-identical on any
  CPython version, any platform, any interpreter (roborev #3234 M2).

  This replaced ``random.Random`` + ``random.choices`` + ``random.sample``. The core
  generator was never the risk; the SELECTION helpers were. CPython documents their
  ALGORITHMS as implementation details ("the algorithms ... may change"), and
  ``sample`` in particular picks between a pool algorithm and a selection-set
  algorithm on a ``setsize`` heuristic. A change to either would alter partition
  widths, bucket spread and PRNG consumption -- silently invalidating the seed
  identity every committed manifest records, on nothing more than a `python3` that
  resolves to a different interpreter.

  The vendored core IS MT19937 with CPython's ``str``-seeding (sha512 digest
  appended, little-endian 32-bit words, ``init_by_array``), which is what makes the
  already-generated corpora still reproducible from their recorded seeds -- verified
  bit-for-bit against ``random.Random`` on CPython 3.12 for ``getrandbits``,
  ``random()``, weighted choice and sampling, and end-to-end by regenerating the
  committed small golden's CSV and the production corpus's chunk 0/26 byte-identically.
  The point is that the guarantee no longer RESTS on that agreement: the algorithms
  are here, in the tree, and :func:`self_check_digests` pins the resulting bytes.
* the PRNG is seeded from the string ``"<seed>:<chunk-index>"``. Chunks are
  INDEPENDENT (no shared PRNG stream), so a chunk can be regenerated on its own.
* partition keys are ``chunk_index * pk_stride + i``, so no two chunks share a
  partition and every partition lives in exactly one SSTable. `pk` is a CQL
  ``int``, so the largest key is ``INT32_MAX``; :func:`plan_fits_int32` refuses an
  over-ceiling plan at validate time and the write loop re-checks per key.
* the plan record reports OBSERVED counts (rows/partitions actually written,
  the actual rows-per-partition histogram) -- never the requested numbers.

Shape (issue #3234 / #3029): ``PRIMARY KEY (pk, bucket, seq)`` is a COMPOUND
clustering key of two DIFFERING types (`text`, `int`). Bucket names have
distinct first bytes and heterogeneous lengths so the OSS50 byte-comparable
row-index separators branch immediately below the trie root instead of
degenerating into a chain of 2-byte single-transition nodes (the rationale
established by `gen-multiclustering-bti.sh` for #3032).

Usage:
    gen-perf-corpus-bti-rows.py --chunk-index 0 --rows 500000 --seed 20260803 \
        --payload-bytes 160 --widths 200:60,800:30,4000:10 \
        --buckets alpha,bo,charlie-extended-bucket,... \
        --out chunk-0.csv --plan-out row-plan.jsonl
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from bisect import bisect_right
from collections import Counter

# --------------------------------------------------------------------------
# VENDORED PRNG (roborev #3234 M2). MT19937 -- the reference algorithm, not a
# reimplementation of a moving target -- plus CPython's documented `str` seeding, so
# a corpus generated by ANY interpreter from a recorded seed is the same corpus.
#
# Constants and recurrences are the MT19937 reference implementation
# (Matsumoto/Nishimura 1998): N/M/MATRIX_A/the two masks, `init_genrand`,
# `init_by_array`, the twist, and the tempering shifts.
_MT_N = 624
_MT_M = 397
_MT_MATRIX_A = 0x9908B0DF
_MT_UPPER_MASK = 0x80000000
_MT_LOWER_MASK = 0x7FFFFFFF
_MASK32 = 0xFFFFFFFF


class Mt19937:
    """MT19937 seeded from a text seed, self-contained and fully specified here.

    Seeding mirrors CPython's ``random.Random(str)``: the seed text's UTF-8 bytes with
    its sha512 digest appended, read as ONE big-endian integer, split into
    little-endian 32-bit words, fed to ``init_by_array``. That is what keeps every
    already-recorded seed reproducing its already-generated corpus.

    Cost, MEASURED (this box, CPython 3.12): ~13 us per ``getrandbits(640)``, i.e.
    ~3 minutes of PRNG work across the 13.2 M-row production corpus, against a
    generation run dominated by `cqlsh COPY`. Determinism that does not depend on an
    unpinned interpreter is worth that; a C-speed generator whose selection
    algorithms may change under us is not.
    """

    __slots__ = ("_mt", "_buf", "_pos")

    def __init__(self, seed_text: str) -> None:
        raw = seed_text.encode()
        n = int.from_bytes(raw + hashlib.sha512(raw).digest(), "big")
        key: list[int] = []
        while n:
            key.append(n & _MASK32)
            n >>= 32
        self._mt = [0] * _MT_N
        self._buf: list[int] = []
        self._pos = _MT_N  # forces the first refill
        self._init_by_array(key or [0])

    def _init_genrand(self, seed: int) -> None:
        mt = self._mt
        mt[0] = seed & _MASK32
        for i in range(1, _MT_N):
            mt[i] = (1812433253 * (mt[i - 1] ^ (mt[i - 1] >> 30)) + i) & _MASK32

    def _init_by_array(self, key: list[int]) -> None:
        self._init_genrand(19650218)
        mt = self._mt
        i, j, klen = 1, 0, len(key)
        for _ in range(max(_MT_N, klen)):
            mt[i] = (
                (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1664525)) + key[j] + j
            ) & _MASK32
            i += 1
            j += 1
            if i >= _MT_N:
                mt[0] = mt[_MT_N - 1]
                i = 1
            if j >= klen:
                j = 0
        for _ in range(_MT_N - 1):
            mt[i] = ((mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1566083941)) - i) & _MASK32
            i += 1
            if i >= _MT_N:
                mt[0] = mt[_MT_N - 1]
                i = 1
        mt[0] = _MT_UPPER_MASK

    def _refill(self) -> None:
        """Twist the whole state, then temper the whole block (block-at-a-time is an
        implementation detail of SPEED only: the word sequence is unchanged)."""
        mt = self._mt
        for k in range(_MT_N - _MT_M):
            y = (mt[k] & _MT_UPPER_MASK) | (mt[k + 1] & _MT_LOWER_MASK)
            mt[k] = mt[k + _MT_M] ^ (y >> 1) ^ (_MT_MATRIX_A if y & 1 else 0)
        for k in range(_MT_N - _MT_M, _MT_N - 1):
            y = (mt[k] & _MT_UPPER_MASK) | (mt[k + 1] & _MT_LOWER_MASK)
            mt[k] = mt[k + (_MT_M - _MT_N)] ^ (y >> 1) ^ (_MT_MATRIX_A if y & 1 else 0)
        y = (mt[_MT_N - 1] & _MT_UPPER_MASK) | (mt[0] & _MT_LOWER_MASK)
        mt[_MT_N - 1] = mt[_MT_M - 1] ^ (y >> 1) ^ (_MT_MATRIX_A if y & 1 else 0)
        buf: list[int] = []
        append = buf.append
        for y in mt:
            y ^= y >> 11
            y ^= (y << 7) & 0x9D2C5680
            y ^= (y << 15) & 0xEFC60000
            y &= _MASK32
            append(y ^ (y >> 18))
        self._buf = buf
        self._pos = 0

    def u32(self) -> int:
        if self._pos >= _MT_N:
            self._refill()
        value = self._buf[self._pos]
        self._pos += 1
        return value

    def getrandbits(self, k: int) -> int:
        """`k` random bits, assembled exactly as CPython's `getrandbits` does:
        32-bit words least-significant-first, the most significant word right-shifted
        when `k` is not a multiple of 32."""
        if k < 1:
            raise SystemExit(f"getrandbits: k={k} must be >= 1")
        if k <= 32:
            return self.u32() >> (32 - k)
        words = (k - 1) // 32 + 1
        if self._pos + words <= _MT_N:
            pos = self._pos
            chunk = self._buf[pos : pos + words]
            self._pos = pos + words
        else:
            chunk = [self.u32() for _ in range(words)]
        rem = k - 32 * (words - 1)
        if rem < 32:
            chunk[-1] >>= 32 - rem
        out = 0
        for i in range(words - 1, -1, -1):
            out = (out << 32) | chunk[i]
        return out

    def random(self) -> float:
        """A float in [0, 1) with 53 bits of entropy -- MT19937's `genrand_res53`."""
        a = self.u32() >> 5
        b = self.u32() >> 6
        return (a * 67108864.0 + b) * (1.0 / 9007199254740992.0)

    def below(self, n: int) -> int:
        """Uniform int in [0, n), by rejection over the `n.bit_length()` low bits."""
        k = n.bit_length()
        r = self.getrandbits(k)
        while r >= n:
            r = self.getrandbits(k)
        return r


def weighted_choice(rnd: Mt19937, values: list[int], cum_weights: list[int]) -> int:
    """One weighted draw with replacement: bisect the cumulative weights by
    ``random() * total``. One ``random()`` call per draw, fixed here."""
    total = cum_weights[-1] + 0.0
    return values[bisect_right(cum_weights, rnd.random() * total, 0, len(values) - 1)]


def sample_without_replacement(rnd: Mt19937, population: list[str], k: int) -> list[str]:
    """`k` distinct elements, in selection order, by the POOL algorithm.

    Unconditionally the pool algorithm: swap the chosen element out and the last
    non-selected element into its place, `k` calls to :meth:`Mt19937.below`. CPython's
    ``sample`` switches to a selection-set algorithm above a ``setsize`` heuristic --
    exactly the kind of internal this file no longer depends on. (Bucket lists are an
    order of magnitude below that threshold, so this is also what produced every
    corpus generated so far.)
    """
    n = len(population)
    if not 0 <= k <= n:
        raise SystemExit(f"sample_without_replacement: k={k} out of range for n={n}")
    pool = list(population)
    result: list[str] = []
    for i in range(k):
        j = rnd.below(n - i)
        result.append(pool[j])
        pool[j] = pool[n - i - 1]
    return result

# `pk` is a CQL `int`, i.e. SIGNED 32-BIT: the largest partition key the table can
# hold is 2147483647. Since pk = chunk_index * PK_STRIDE + i, the stride bounds how
# many chunks a run may have -- and an over-large stride is NOT a harmless waste of
# key space, it is a hard failure part-way through a multi-GB load.
#
# MEASURED (issue #3234): with the original PK_STRIDE = 1_000_000_000, chunk 3's
# pk_base was 3_000_000_000 > INT32_MAX, so `cqlsh COPY` rejected EVERY row of that
# chunk with "'i' format requires -2147483648 <= number <= 2147483647" and the
# generator died at chunk 3 of 27 -- after ~4 minutes and 3 SSTables of work. The
# 2-chunk --smoke run never reached chunk 3, so the ceiling was invisible to it.
# Hence: a stride with generous but FINITE headroom, plus the two fail-closed
# asserts below (`plan_fits_int32` at validate time, the in-loop ceiling check at
# write time). The ceiling is a property of the COLUMN TYPE, so it is checked here
# rather than left to cqlsh to discover mid-load.
INT32_MAX = 2_147_483_647

# 1e6 partitions of headroom per chunk (~1400x the ~700 partitions a 500k-row chunk
# actually produces), which admits chunk indices 0..2147 -- i.e. a 2147-SSTable
# corpus, far beyond any profileable size. Partition keys still never collide
# across chunks (asserted below, not assumed).
PK_STRIDE = 1_000_000


def max_pk_of_plan(chunks: int, chunk_rows: int) -> int:
    """The largest partition key a (chunks, chunk_rows) plan can emit.

    Keys of chunk N span ``N * PK_STRIDE .. N * PK_STRIDE + partitions - 1`` and
    ``partitions <= rows`` always, so the last chunk's ceiling is
    ``(chunks - 1) * PK_STRIDE + chunk_rows - 1`` -- INCLUSIVE. The ``- 1`` is the
    whole point (roborev #3234 L4): omitting it rejected a plan whose final key is
    EXACTLY ``INT32_MAX``, which is a valid key.
    """
    return (chunks - 1) * PK_STRIDE + chunk_rows - 1


def plan_fits_int32(chunks: int, chunk_rows: int) -> None:
    """Fail closed if a (chunks, chunk_rows) plan would overflow the `pk int` column.

    Called by the generator's `validate_inputs` BEFORE any container starts, so an
    over-sized plan is refused up front instead of dying part-way through the load
    (issue #3234). The bound is INCLUSIVE (see :func:`max_pk_of_plan`): a plan whose
    largest key is exactly ``INT32_MAX`` fits and is accepted.
    """
    if chunks < 1 or chunk_rows < 1:
        raise SystemExit(f"plan_fits_int32: chunks={chunks} chunk_rows={chunk_rows} must be >= 1")
    max_pk = max_pk_of_plan(chunks, chunk_rows)
    if max_pk > INT32_MAX:
        # Largest chunk count that still fits, from the same inclusive arithmetic:
        # (c - 1) * STRIDE + chunk_rows - 1 <= INT32_MAX.
        max_chunks = (INT32_MAX - (chunk_rows - 1)) // PK_STRIDE + 1
        advice = (
            f"Use at most {max_chunks} chunks (raise --chunk-rows, or lower --rows)."
            if max_chunks >= 1
            else f"Even ONE chunk of {chunk_rows} rows cannot fit; lower --chunk-rows."
        )
        raise SystemExit(
            f"plan overflows the `pk int` column: {chunks} chunks x stride {PK_STRIDE} "
            f"reaches pk {max_pk} > INT32_MAX ({INT32_MAX}). cqlsh COPY would reject "
            f"every row of the first over-ceiling chunk. {advice}"
        )


def chunk_fits_int32(chunk_index: int, rows: int) -> int:
    """Return chunk `chunk_index`'s key base, failing closed if the chunk cannot fit.

    Same INCLUSIVE bound as :func:`plan_fits_int32`, applied to the ONE chunk this
    process is about to write: keys span ``pk_base .. pk_base + rows - 1`` at worst
    (one row per partition), so a chunk whose final key is exactly ``INT32_MAX``
    is accepted (roborev #3234 L4).
    """
    pk_base = chunk_index * PK_STRIDE
    if pk_base + rows - 1 > INT32_MAX:
        raise SystemExit(
            f"chunk {chunk_index}: pk_base {pk_base} + {rows} rows reaches pk "
            f"{pk_base + rows - 1} > INT32_MAX ({INT32_MAX}); the `pk int` column "
            f"cannot hold this chunk"
        )
    return pk_base


def parse_widths(spec: str) -> list[tuple[int, int]]:
    """``"200:60,800:30"`` -> ``[(200, 60), (800, 30)]`` (rows-per-partition, weight)."""
    out: list[tuple[int, int]] = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        width, sep, weight = part.partition(":")
        if not sep:
            raise SystemExit(f"malformed --widths entry {part!r}: expected <rows>:<weight>")
        try:
            w, k = int(width), int(weight)
        except ValueError:
            raise SystemExit(f"malformed --widths entry {part!r}: non-integer") from None
        if w < 1 or k < 1:
            raise SystemExit(f"--widths entry {part!r}: rows and weight must both be >= 1")
        out.append((w, k))
    if not out:
        raise SystemExit("--widths is empty")
    return out


def parse_buckets(spec: str) -> list[str]:
    buckets = [b.strip() for b in spec.split(",") if b.strip()]
    if len(buckets) < 2:
        raise SystemExit("--buckets needs >= 2 names (a single bucket cannot branch the trie)")
    firsts = {b[0] for b in buckets}
    if len(firsts) != len(buckets):
        raise SystemExit(
            "--buckets names must have DISTINCT first bytes: they drive the row-index "
            "trie's depth-1 transition spread (see gen-multiclustering-bti.sh, #3032)"
        )
    for b in buckets:
        if any(c in b for c in ',"\n\\'):
            raise SystemExit(f"--buckets name {b!r} contains a CSV-hostile character")
    return buckets


def bucket_count_for(width: int, max_buckets: int) -> int:
    """How many clustering buckets a partition of `width` rows is split across.

    Deliberately width-dependent (not random): a wider partition spreads over
    more distinct first-byte transitions, so the per-partition tries differ in
    SHAPE and not merely in depth.
    """
    return max(2, min(max_buckets, width // 100))


def generate_chunk(
    write,
    *,
    chunk_index: int,
    rows: int,
    seed: str,
    payload_bytes: int,
    widths: list[tuple[int, int]],
    buckets: list[str],
) -> dict:
    """Emit one chunk's CSV rows through `write`, returning the OBSERVED plan record.

    The single generation code path: the CLI passes a file's `write`, the pinned
    self-check passes a hasher's. A digest pinned through any other path would pin a
    copy of the algorithm rather than the algorithm (issue #3042's lesson applied to
    this file).
    """
    width_values = [w for w, _ in widths]
    # Cumulative weights, computed ONCE (the stdlib recomputed them per draw; the
    # PRNG consumption -- one random() per draw -- is identical either way).
    width_cum: list[int] = []
    running = 0
    for _, weight in widths:
        running += weight
        width_cum.append(running)

    seed_material = f"{seed}:{chunk_index}"
    rnd = Mt19937(seed_material)
    pk_base = chunk_fits_int32(chunk_index, rows)

    # Hex payload: one getrandbits() per row (fast, deterministic). Hex is ~2:1
    # LZ4-compressible, i.e. field-shaped rather than either incompressible noise
    # or a repeated string that would collapse to nothing on disk.
    hex_chars = payload_bytes
    bits = 4 * hex_chars

    remaining = rows
    rows_written = 0
    partitions = 0
    width_hist: Counter[int] = Counter()
    bucket_hist: Counter[int] = Counter()
    pk_max = pk_base

    while remaining > 0:
        if partitions >= PK_STRIDE:
            raise SystemExit(
                f"chunk {chunk_index}: partition count reached the pk stride "
                f"({PK_STRIDE}); lower --chunk-rows or raise the stride"
            )
        pk = pk_base + partitions
        # Absolute ceiling, independent of the stride: `pk` is a CQL `int`.
        # Without this, an over-ceiling key is only discovered by cqlsh, which
        # reports it as a per-batch ParseError mid-load (issue #3234).
        if pk > INT32_MAX:
            raise SystemExit(
                f"chunk {chunk_index}: pk {pk} exceeds INT32_MAX "
                f"({INT32_MAX}) — the `pk int` column cannot hold it"
            )
        # Partition-atomic, except the LAST partition of the chunk, which is
        # trimmed so the chunk emits EXACTLY `rows` rows.
        width = min(weighted_choice(rnd, width_values, width_cum), remaining)
        nbuckets = min(bucket_count_for(width, len(buckets)), width)
        chosen = sample_without_replacement(rnd, buckets, nbuckets)
        base, extra = divmod(width, nbuckets)
        for bi, bucket in enumerate(chosen):
            n = base + (1 if bi < extra else 0)
            for seq in range(n):
                payload = format(rnd.getrandbits(bits), f"0{hex_chars}x")
                write(f"{pk},{bucket},{seq},{payload}\n")
        width_hist[width] += 1
        bucket_hist[nbuckets] += 1
        rows_written += width
        remaining -= width
        pk_max = pk
        partitions += 1

    if rows_written != rows:
        raise SystemExit(f"internal error: emitted {rows_written} rows, requested {rows}")

    observed_widths = sorted(width_hist)
    return {
        "chunk": chunk_index,
        "seed": seed,
        "seed_material": seed_material,
        "rows": rows_written,
        "partitions": partitions,
        "pk_min": pk_base,
        "pk_max": pk_max,
        "pk_stride": PK_STRIDE,
        "payload_bytes": payload_bytes,
        "rows_per_partition_histogram": {str(w): width_hist[w] for w in observed_widths},
        "buckets_per_partition_histogram": {
            str(b): bucket_hist[b] for b in sorted(bucket_hist)
        },
        "rows_per_partition_min": observed_widths[0],
        "rows_per_partition_max": observed_widths[-1],
        "rows_per_partition_mean": round(rows_written / partitions, 3),
        "source": "counted while writing the CSV (observed, not requested)",
    }


# --------------------------------------------------------------------------
# PINNED DETERMINISM VECTORS (roborev #3234 M2).
#
# What actually GUARANTEES the determinism claim, as opposed to arguing for it: the
# exact CSV bytes this file produces for a fixed set of configurations, committed
# here as sha256 digests and checked by `--self-check` (run as a case of
# scripts/tests/test_gen_perf_corpus_bti.sh). If ANY layer ever drifts -- the seeding,
# the twist, the tempering, the bit assembly, the weighted draw, the sampling, the
# row/bucket layout -- a digest moves and the suite reds, on the interpreter in front
# of you. Same-seed identity and cross-seed difference are checked here too, but they
# are weaker: they hold even if every byte changed together.
#
# Vector 2 is the COMMITTED SMALL GOLDEN's exact configuration, so the row set behind
# `test_da/wide_multiclustering_small-47f6a3008f6911f1bc0f8df8badcc262` is pinned.
# Vectors 3/4 exist for the bit-assembly edges: a payload whose bit count is NOT a
# multiple of 32 (the truncated most-significant word) and one large enough to cross
# the 624-word MT block boundary mid-row.
_PROD_BUCKETS = (
    "alpha,bo,charlie-extended-bucket,delta,ep,foxtrot-long-bucket-name,golf,hh,"
    "india-bucket,jj"
)
SELF_CHECK_VECTORS = [
    # label, seed, chunk, rows, payload_bytes, widths, buckets, csv_sha256, partitions
    (
        "production-width-mix (the 13.2M-row corpus's own config, chunk 0, 5k rows)",
        "20260803", 0, 5000, 160, "200:60,800:30,4000:10", _PROD_BUCKETS,
        "b243da7e857c58adcf4378e1a1fd601ebae467386f420dc7a91fc36ba2a4ae72", 3,
    ),
    (
        "small-golden (the COMMITTED test_da fixture's exact row set)",
        "20260803", 0, 600, 160, "400:20,80:30,20:50", _PROD_BUCKETS,
        "afe6a1023c715b4690893cae22a8cde6a01c61b280c75a088deee242959e0368", 5,
    ),
    (
        "payload bits NOT a multiple of 32 (truncated most-significant word)",
        "3234", 3, 700, 11, "200:60,80:30", "alpha,bo,charlie,delta",
        "069158cb955faefa5be4222d2bcfe6f07c0c7210978db850a3c35430287e45f8", 5,
    ),
    (
        "payload crossing the MT block boundary mid-row",
        "3234", 1, 400, 2048, "100:1", "alpha,bo",
        "12689eb38699bb840c2ff6646ebc4246eaea2e0a0014ee8953c8d96aebfdc670", 4,
    ),
]


def self_check_digests() -> int:
    """Regenerate the pinned vectors and compare CSV digests, byte for byte."""
    problems: list[str] = []
    for label, seed, chunk, rows, payload, widths, buckets, want, want_parts in SELF_CHECK_VECTORS:
        parsed_widths = parse_widths(widths)
        parsed_buckets = parse_buckets(buckets)
        digest = hashlib.sha256()
        plan = generate_chunk(
            lambda text: digest.update(text.encode()),
            chunk_index=chunk, rows=rows, seed=seed, payload_bytes=payload,
            widths=parsed_widths, buckets=parsed_buckets,
        )
        got = digest.hexdigest()
        print(f"  {got}  parts={plan['partitions']:<6} {label}")
        if got != want:
            problems.append(f"{label}: csv sha256 {got} != pinned {want}")
        if want_parts and plan["partitions"] != want_parts:
            problems.append(
                f"{label}: {plan['partitions']} partitions != pinned {want_parts}"
            )
        # Same seed twice must be identical; another seed must differ. Weaker than the
        # digest, but it localizes a failure to "not deterministic at all".
        again = hashlib.sha256()
        generate_chunk(
            lambda text: again.update(text.encode()),
            chunk_index=chunk, rows=rows, seed=seed, payload_bytes=payload,
            widths=parsed_widths, buckets=parsed_buckets,
        )
        if again.hexdigest() != got:
            problems.append(f"{label}: NOT deterministic across two runs in one process")
        other = hashlib.sha256()
        generate_chunk(
            lambda text: other.update(text.encode()),
            chunk_index=chunk, rows=rows, seed=f"{seed}x", payload_bytes=payload,
            widths=parsed_widths, buckets=parsed_buckets,
        )
        if other.hexdigest() == got:
            problems.append(f"{label}: another seed produced the SAME bytes")
    if problems:
        for problem in problems:
            print(f"SELF-CHECK FAILED: {problem}", file=sys.stderr)
        raise SystemExit(
            "row-driver determinism self-check FAILED: the vendored PRNG / selection "
            "algorithms no longer reproduce the pinned bytes, so every recorded seed "
            "identity (including the committed manifests') is void. Do NOT re-pin the "
            "digests to make this pass -- find what changed."
        )
    print(f"SELF-CHECK-OK {len(SELF_CHECK_VECTORS)} pinned determinism vector(s)")
    return 0


def main() -> int:
    # --self-check is a standalone mode (no corpus, no output files), so it is handled
    # before the parser whose other flags are all required.
    if "--self-check" in sys.argv[1:]:
        if len(sys.argv) != 2:
            raise SystemExit("--self-check takes no other arguments")
        return self_check_digests()

    ap = argparse.ArgumentParser()
    ap.add_argument("--chunk-index", type=int, required=True)
    ap.add_argument("--rows", type=int, required=True,
                    help="rows to emit in THIS chunk (exact)")
    ap.add_argument("--seed", required=True,
                    help="corpus seed; the chunk PRNG is seeded '<seed>:<chunk-index>'")
    ap.add_argument("--payload-bytes", type=int, required=True)
    ap.add_argument("--widths", required=True,
                    help="rows-per-partition distribution, <rows>:<weight>[,...]")
    ap.add_argument("--buckets", required=True)
    ap.add_argument("--out", required=True, help="CSV destination")
    ap.add_argument("--plan-out", required=True,
                    help="JSONL file the plan record is APPENDED to")
    args = ap.parse_args()

    if args.chunk_index < 0:
        raise SystemExit("--chunk-index must be >= 0")
    if args.rows < 1:
        raise SystemExit("--rows must be >= 1")
    if args.payload_bytes < 8:
        raise SystemExit("--payload-bytes must be >= 8")

    widths = parse_widths(args.widths)
    buckets = parse_buckets(args.buckets)

    with open(args.out, "w", newline="") as fh:
        plan = generate_chunk(
            fh.write,
            chunk_index=args.chunk_index,
            rows=args.rows,
            seed=args.seed,
            payload_bytes=args.payload_bytes,
            widths=widths,
            buckets=buckets,
        )

    with open(args.plan_out, "a") as fh:
        fh.write(json.dumps(plan, sort_keys=False) + "\n")

    print(
        f"[rows] chunk {args.chunk_index}: {plan['rows']} rows / {plan['partitions']} "
        f"partitions (width {plan['rows_per_partition_min']}.."
        f"{plan['rows_per_partition_max']}, pk {plan['pk_min']}..{plan['pk_max']}, "
        f"seed_material {plan['seed_material']}) -> {args.out}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
