"""Nested-UDT-in-a-hashable-position read fidelity — issue #3500.

WHAT IS UNDER TEST
------------------
The Python binding projects a CQL ``set`` to a Python ``set`` and a CQL ``map``
to a Python ``dict``, so every set ELEMENT and every map KEY must be reduced to
a HASHABLE Python object. That reduction lives in
``bindings/python/src/value.rs`` (``value_to_hashable_key`` / ``contains_udt``)
and was **not total** over the ``cqlite_core::Value`` tree: a UDT reached
through a TUPLE or through a NESTED COLLECTION fell through to the generic
converter, which yields an unhashable ``dict``/``list``, and the whole
``SELECT`` raised.

Measured on this fixture BEFORE the fix (verbatim):

===============  ===========================================
column           exception
===============  ===========================================
s_tuple_udt      ``TypeError: unhashable type: 'dict'``
s_set_udt        ``TypeError: unhashable type: 'list'``
f_set_tuple_udt  ``TypeError: unhashable type: 'dict'``
``SELECT *``     ``TypeError: unhashable type: 'dict'``
===============  ===========================================

THE ORACLE
----------
Real Cassandra 5.0.2-written bytes:
``test-data/datasets/sstables/test_nested_udt_keys/nested_udt_keys-*`` (BIG
``nb``, uncompressed, 4 partitions), declared by
``test-data/schemas/nested-udt-keys.cql`` and generated by
``test-data/scripts/generate-nested-udt-keys.sh``. Every expectation below is
derived from the committed sstabledump golden ``nb-1-big-Data.db.jsonl`` plus
the generator's own INSERT statements — never from CQLite's prior output. A
CQLite-written/CQLite-read round trip could not detect this class at all.

Element ORDER is Cassandra's: a CQL ``set``/``map`` is stored sorted by the
serialized element/key, so the sequences asserted here are the golden's
cell-path order, not the insertion order.

WHY THESE TESTS ARE pytest AND NOT RUST ``#[test]``
---------------------------------------------------
``cargo test -p cqlite-py`` is structurally impossible — a pyo3 cdylib's test
harness cannot link libpython — so a Rust unit test beside the fix would
execute in no lane on any machine (``scripts/agent-gate.sh``'s
``binding-rust-tests`` census grep-counts those attributes precisely in order to
DECLARE them unrunnable). These run in the full gate's ``python-bindings``
component and the #1893 ``--lite`` python tier.

FAIL-CLOSED, NEVER SKIP (issue #3220)
-------------------------------------
``conftest.py`` resolves ONE corpus root and prefers ``$CQLITE_DATASETS_ROOT``,
so an in-repo COMMITTED fixture is invisible to it and ``skip_if_no_datasets()``
would skip green forever. Neither root is a superset of the other, so no fixed
env-first/checkout-first rule is correct. This module therefore resolves the
corpus root PER TABLE by walking EVERY candidate root for that table's
``*-Data.db`` (the Python mirror of
``cqlite-core/tests/support/datasets_root.rs::sstables_root_for_table``) and
asserts PER CASE: the fixture is git-committed, so it is ``must_run`` and
fail-closed UNCONDITIONALLY — there is no ``pytest.skip`` in this file and no
suite-wide ``assert ran > 0`` (which cannot see one case skipping behind its
siblings).
"""

import os
from pathlib import Path

import pytest

import cqlite

KEYSPACE = "test_nested_udt_keys"
TABLE = "nested_udt_keys"
SCHEMA_FILE = "nested-udt-keys.cql"


# =============================================================================
# Root resolution — committed schema checkout-relative (#3148), corpus per
# table across EVERY candidate root (#3220). Deliberately local to this module:
# conftest's single-root constants are the thing that would hide the fixture.
# =============================================================================


def _workspace_root() -> Path:
    """The checkout root, anchored on the workspace-root ``Cargo.toml`` marker.

    Same rule as ``test-data/support/fixture_roots.rs::workspace_root`` — the
    nearest ancestor whose ``Cargo.toml`` declares ``[workspace]``. Anchoring on
    a marker rather than counting ``..`` levels keeps this correct if the file
    ever moves.
    """
    here = Path(__file__).resolve()
    for ancestor in here.parents:
        manifest = ancestor / "Cargo.toml"
        if not manifest.is_file():
            continue
        try:
            text = manifest.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if any(line.lstrip().startswith("[workspace]") for line in text.splitlines()):
            return ancestor
    raise AssertionError(
        f"no [workspace] Cargo.toml found in any ancestor of {here} — cannot "
        "resolve the checkout root for the committed #3500 fixture"
    )


def _schemas_root() -> Path:
    """The COMMITTED schema-fixture root.

    Checkout-relative source, never derived from ``CQLITE_DATASETS_ROOT``.
    ``CQLITE_SCHEMAS_ROOT`` is an optional out-of-tree override and MUST be
    absolute: the gate resolves a relative value against the repo root while
    pytest runs from the package dir, so it would certify one schemas root while
    the tests read another (#3148). A relative value is REJECTED, never resolved.
    """
    raw = os.environ.get("CQLITE_SCHEMAS_ROOT")
    if raw is not None and raw.strip():
        if any(ord(ch) < 32 or ord(ch) == 127 for ch in raw):
            pytest.fail(
                f"CQLITE_SCHEMAS_ROOT must not contain control characters, got {raw!r}"
            )
        override = Path(raw)
        if not override.is_absolute():
            pytest.fail(
                f"CQLITE_SCHEMAS_ROOT must be an ABSOLUTE path, got {raw!r} — a "
                "relative value cannot mean the same thing to the gate (CWD = repo "
                "root) and to pytest (CWD = package dir), so the gate would certify "
                "a schemas root the run never used (#3148)"
            )
        if override.is_dir():
            return override
    return _workspace_root() / "test-data" / "schemas"


def _sstables_root_candidates() -> list[Path]:
    """Every ``sstables/`` root to search, in order.

    An ORDER, not a preference: ``_sstables_root_for_table`` picks by EVIDENCE
    (which root actually holds the table), because neither root is a superset of
    the other — the fetched corpus carries keyspaces the checkout does not, and
    the checkout carries committed fixtures (this one) the fetched corpus does
    not (#3104/#3220).
    """
    candidates: list[Path] = []
    env_root = os.environ.get("CQLITE_DATASETS_ROOT")
    if env_root and env_root.strip():
        root = Path(env_root)
        nested = root / "sstables"
        candidates.append(nested if nested.is_dir() else root)
    checkout = _workspace_root() / "test-data" / "datasets" / "sstables"
    if checkout not in candidates:
        candidates.append(checkout)
    return candidates


def _table_has_data(root: Path, keyspace: str, table: str) -> bool:
    """True when ``<root>/<keyspace>/<table>-*/`` holds a ``*-Data.db`` FILE.

    Presence is judged by a real Data.db component, never by directory
    existence: this repo commits JSONL sidecars for fixtures whose binaries are
    gitignored, so a ``<table>-<uuid>/`` dir can exist with no SSTable in it.
    """
    ks_dir = root / keyspace
    if not ks_dir.is_dir():
        return False
    prefix = f"{table}-"
    try:
        table_dirs = [
            d for d in ks_dir.iterdir() if d.is_dir() and d.name.startswith(prefix)
        ]
    except OSError:
        return False
    for table_dir in table_dirs:
        try:
            entries = list(table_dir.iterdir())
        except OSError:
            continue
        if any(e.is_file() and e.name.endswith("-Data.db") for e in entries):
            return True
    return False


def _sstables_root_for_table(keyspace: str, table: str) -> Path:
    """The candidate root that really carries ``<keyspace>/<table>-*/…-Data.db``.

    FAIL-CLOSED, naming every root searched. This fixture is git-committed, so
    "not found" is a broken checkout or a broken resolver — never a reason to
    skip.
    """
    candidates = _sstables_root_candidates()
    for root in candidates:
        if _table_has_data(root, keyspace, table):
            return root
    searched = ", ".join(str(c) for c in candidates)
    raise AssertionError(
        f"COMMITTED fixture {keyspace}.{table} carries no *-Data.db under any "
        f"candidate root — searched [{searched}]. This fixture is checked into git "
        "(issue #3500), so this is a broken checkout or a broken resolver, not a "
        "missing download; it must never be skipped (#3220)."
    )


@pytest.fixture(scope="module")
def db():
    """Open the #3500 fixture through the real binding. Never skips."""
    root = _sstables_root_for_table(KEYSPACE, TABLE)
    schema = _schemas_root() / SCHEMA_FILE
    assert schema.is_file(), (
        f"committed schema {schema} is unreadable — it is checked-in source "
        "(#3148), so this is fail-closed, not a skip"
    )
    with cqlite.open(root, schema=schema) as database:
        yield database


def _rows_by_id(database, projection: str) -> dict:
    """``{id: row}`` for a projection, asserting all four partitions arrived."""
    result = database.execute(f"SELECT id, {projection} FROM {KEYSPACE}.{TABLE}")
    rows = {row.get("id"): row for row in result.rows}
    assert sorted(rows) == [1, 2, 3, 4], (
        f"expected partitions 1..4 from the committed fixture, got {sorted(rows)}"
    )
    return rows


# =============================================================================
# Expected-value helpers
# =============================================================================


def kp(label, rank) -> dict:
    """The Python projection of one ``key_part`` UDT value.

    ``udt_to_py`` emits the two metadata keys plus every schema field, including
    fields whose value is NULL (they arrive as ``None``, matching the golden's
    ``"label": null``).
    """
    return {
        "_type": "key_part",
        "_keyspace": KEYSPACE,
        "label": label,
        "rank": rank,
    }


def _component(payload) -> bytes:
    """One Cassandra composite component: int32 BE length + bytes; -1 = null."""
    if payload is None:
        return b"\xff\xff\xff\xff"
    return len(payload).to_bytes(4, "big") + payload


def _key_part_serialized(label, rank) -> bytes:
    """``frozen<key_part>`` as Cassandra serializes it (label text, rank int)."""
    label_bytes = None if label is None else label.encode("utf-8")
    rank_bytes = None if rank is None else rank.to_bytes(4, "big", signed=True)
    return _component(label_bytes) + _component(rank_bytes)


def tuple_udt_int_serialized(label, rank, trailing) -> bytes:
    """``tuple<frozen<key_part>, int>`` as Cassandra serializes it.

    Used ONLY by the ``m_tuple_udt`` documented-gap test: the map key currently
    arrives as these OPAQUE bytes instead of a structured tuple. Cross-checks
    against the golden's ``path`` values byte for byte.
    """
    return _component(_key_part_serialized(label, rank)) + _component(
        trailing.to_bytes(4, "big", signed=True)
    )


# =============================================================================
# The four issue shapes + the frozen-outer column
# =============================================================================


class TestTupleBorneUdtInSetElement:
    """``s_tuple_udt`` — ``set<frozen<tuple<frozen<key_part>, int>>>``.

    Issue #3500 shape 1: the UDT is reached through a TUPLE. Before the fix this
    raised ``TypeError: unhashable type: 'dict'`` — ``contains_udt`` did not
    traverse ``Tuple``, so the set took the frozenset path, and
    ``value_to_hashable_key`` had no ``Tuple`` arm so the element became a
    Python tuple containing an unhashable ``dict``.
    """

    def test_multi_element_partition(self, db):
        """id=1: three tuples, two sharing the same UDT with different ints.

        Order is Cassandra's sorted order (golden cell paths ``alpha\\:1:1``,
        ``alpha\\:1:2``, ``zulu\\:26:7``), NOT the insertion order.
        """
        row = _rows_by_id(db, "s_tuple_udt")[1]
        assert row.get("s_tuple_udt") == [
            (kp("alpha", 1), 1),
            (kp("alpha", 1), 2),
            (kp("zulu", 26), 7),
        ]

    def test_null_udt_fields(self, db):
        """id=2: NULL UDT fields inside the hashable position.

        Reaches ``value_to_hashable_key``'s ``None => py.None()`` UDT-field
        branch, which no committed fixture previously exercised inside a
        hashable position. Golden order: ``\\@\\:5:2`` then
        ``nullrank\\:\\@:1`` (``\\@`` is sstabledump's null marker).
        """
        row = _rows_by_id(db, "s_tuple_udt")[2]
        assert row.get("s_tuple_udt") == [
            (kp(None, 5), 2),
            (kp("nullrank", None), 1),
        ]

    def test_single_element_partition(self, db):
        """id=3: exactly one element, the same UDT value as the other columns."""
        row = _rows_by_id(db, "s_tuple_udt")[3]
        assert row.get("s_tuple_udt") == [(kp("solo", 99), 42)]

    def test_sparse_row(self, db):
        """id=4: the ONLY column written in that partition.

        The sparse row exercises the missing-column path alongside a populated
        hashable-position column: every other column of id=4 must be ``None``
        while this one decodes.
        """
        rows = _rows_by_id(db, "s_tuple_udt")
        assert rows[4].get("s_tuple_udt") == [(kp("partial", 4), 4)]

    def test_elements_are_plain_tuples_and_dicts(self, db):
        """Exact Python types, not merely equal structures."""
        value = _rows_by_id(db, "s_tuple_udt")[3].get("s_tuple_udt")
        assert type(value) is list
        assert type(value[0]) is tuple
        assert type(value[0][0]) is dict
        assert type(value[0][1]) is int


class TestNestedSetBorneUdtInSetElement:
    """``s_set_udt`` — ``set<frozen<set<frozen<key_part>>>>``.

    Issue #3500 shape 2: the UDT is reached through a NESTED SET. Before the fix
    this raised ``TypeError: unhashable type: 'list'`` — ``contains_udt`` did not
    traverse ``Set``, so the OUTER set took the frozenset path, while the INNER
    set correctly detected its UDT elements and returned an unhashable ``list``.
    """

    def test_multi_element_partition(self, db):
        """id=1: a two-element inner set and a one-element inner set.

        Inner-set order is Cassandra's (golden path bytes: ``alpha`` before
        ``beta``); outer order is the golden's cell-path order.
        """
        row = _rows_by_id(db, "s_set_udt")[1]
        assert row.get("s_set_udt") == [
            [kp("alpha", 1), kp("beta", 2)],
            [kp("gamma", 3)],
        ]

    def test_null_udt_fields(self, db):
        """id=2: one inner set, both UDTs carrying a NULL ``rank``.

        Golden path bytes ``…ffffffffffffffff`` (both fields null) sort before
        ``…6e756c6c72616e6b32ffffffff`` (``nullrank2``, null rank).
        """
        row = _rows_by_id(db, "s_set_udt")[2]
        assert row.get("s_set_udt") == [
            [kp(None, None), kp("nullrank2", None)],
        ]

    def test_single_element_partition(self, db):
        """id=3: one inner set holding one UDT."""
        row = _rows_by_id(db, "s_set_udt")[3]
        assert row.get("s_set_udt") == [[kp("solo", 99)]]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column, so it must be ``None``, not ``[]``."""
        assert _rows_by_id(db, "s_set_udt")[4].get("s_set_udt") is None


class TestNestedListBorneUdtInSetElement:
    """``s_list_udt`` — ``set<frozen<list<frozen<key_part>>>>``: the AC5 CONTROL.

    THIS SHAPE'S OUTPUT CHANGED, DELIBERATELY. Read this before treating a diff
    here as a regression.

    Alone among issue #3500's four shapes, this one did NOT raise before the
    fix. ``contains_udt`` returned ``False``, so the outer set took the frozenset
    path, and ``value_to_hashable_key``'s pre-existing ``List`` and ``Udt`` arms
    projected each element to a hashable form — yielding::

        frozenset({(frozenset({('_type', 'key_part'), ('label', 'one'), …}),
                    frozenset({… 'two' …})), …})

    i.e. a frozenset of tuples of frozensets, measured on this exact fixture
    before the fix.

    AC1 mandates that ``contains_udt`` traverse ``List``. That NECESSARILY makes
    ``contains_udt`` true here, so the column now takes the list path and
    returns a plain ``list`` of ``list`` of ``dict`` — the same shape as
    ``s_set_udt`` above.

    WHY THIS IS THE INTENDED RESOLUTION of the AC1-vs-AC5 conflict (escalated on
    the issue thread and resolved in favour of AC1):

    * AC1 is the explicit, testable mandate; AC5 ("no change to shapes that
      already work") and AC1 cannot both hold literally for this column.
    * The issue's own shape table already records this column's output as
      diverging from the Node/CLI rendering — that divergence is #3497's, not
      this issue's, so the shape was never canonical.
    * The defect's stated TELL is that "behavior depends on which nested
      collection you happen to use". Removing that asymmetry IS the fix: all
      four nestings now project identically.
    * The only alternative — keep the frozenset path and lean on the
      now-total hashable projection — would re-shape ``set<frozen<udt>>``
      itself and break #804/#795, a far larger AC5 violation.

    This NARROWS #3497 (the Python binding is now self-consistent across
    nestings) without CLOSING it: aligning the ``set``-of-UDT projection across
    Python/Node/CLI is still that issue's job.
    """

    def test_intended_new_shape_multi_element(self, db):
        """id=1: two lists with the same elements in DIFFERENT order.

        They are distinct list values — the case a ``set`` of ``list`` exists to
        test — and each now keeps its own order inside a plain Python list, which
        the pre-fix frozenset projection could express only as a tuple of
        frozensets.
        """
        row = _rows_by_id(db, "s_list_udt")[1]
        assert row.get("s_list_udt") == [
            [kp("one", 1), kp("two", 2)],
            [kp("two", 2), kp("one", 1)],
        ]

    def test_intended_new_shape_is_not_a_frozenset(self, db):
        """The pre-fix container types are gone at BOTH levels.

        Pinned explicitly so a revert of AC1 reds here rather than silently
        restoring the asymmetry between ``s_list_udt`` and ``s_set_udt``.
        """
        value = _rows_by_id(db, "s_list_udt")[1].get("s_list_udt")
        assert type(value) is list, f"expected list, got {type(value).__name__}"
        assert not isinstance(value, frozenset)
        assert type(value[0]) is list
        assert type(value[0][0]) is dict

    def test_intended_new_shape_null_fields(self, db):
        """id=2: an EMPTY-string label (``''``) stays distinct from ``None``."""
        row = _rows_by_id(db, "s_list_udt")[2]
        assert row.get("s_list_udt") == [[kp("", 0), kp(None, 9)]]

    def test_intended_new_shape_single_element(self, db):
        """id=3: one inner list holding one UDT."""
        row = _rows_by_id(db, "s_list_udt")[3]
        assert row.get("s_list_udt") == [[kp("solo", 99)]]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "s_list_udt")[4].get("s_list_udt") is None


class TestFrozenOuterSetOfTupleBorneUdt:
    """``f_set_tuple_udt`` — ``frozen<set<frozen<tuple<frozen<key_part>, int>>>>``.

    Not one of the issue's four shapes; it exists because the frozen-outer
    column travels a DIFFERENT decode path. A non-frozen collection arrives as
    per-element CELL PATHS, while a frozen one arrives as a single value cell,
    and the two produce structurally different ``Value`` trees — measured on
    this fixture:

    * multicell:     ``Set([Frozen(Tuple([Frozen(Udt), Integer])), …])``
    * frozen outer:  ``Frozen(Set([Tuple([Udt, Integer]), …]))``  — NO inner
      ``Frozen`` wrappers at all.

    So the traversal must handle ``Frozen`` PRESENT and ABSENT at every level;
    a fix that only unwrapped ``Frozen`` would still raise here. Before the fix
    this column raised ``TypeError: unhashable type: 'dict'``.
    """

    def test_multi_element_partition(self, db):
        """id=1: two tuples, golden order ``frozen-a`` then ``frozen-b``."""
        row = _rows_by_id(db, "f_set_tuple_udt")[1]
        assert row.get("f_set_tuple_udt") == [
            (kp("frozen-a", 11), 1),
            (kp("frozen-b", 12), 2),
        ]

    def test_null_udt_field(self, db):
        """id=2: ``{label: null, rank: 7}`` — the golden's ``"label": null``."""
        row = _rows_by_id(db, "f_set_tuple_udt")[2]
        assert row.get("f_set_tuple_udt") == [(kp(None, 7), 3)]

    def test_single_element_partition(self, db):
        """id=3: one tuple."""
        row = _rows_by_id(db, "f_set_tuple_udt")[3]
        assert row.get("f_set_tuple_udt") == [(kp("solo", 99), 42)]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "f_set_tuple_udt")[4].get("f_set_tuple_udt") is None


class TestTupleBorneUdtAsMapKey:
    """``m_tuple_udt`` — ``map<frozen<tuple<frozen<key_part>, int>>, int>``.

    A DOCUMENTED GAP, NOT DESIRED BEHAVIOUR — this test pins what CQLite does
    TODAY so that fixing the core reds it.

    Issue #3500's shape 3 is the tuple-borne UDT in the MAP-KEY position, and it
    is **not reachable through the Python binding today**: the map key never
    arrives as a structured ``Value::Tuple``. ``parse_cell_path_key``
    (``cqlite-core/src/storage/sstable/reader/parsing/row_decoder/complex_column.rs``)
    is a scalar-only allowlist whose catch-all arm returns ``Value::Blob``, so a
    composite map key decodes as the RAW SERIALIZED KEY BYTES. A ``bytes`` object
    is hashable, so there is no ``TypeError`` here — the value is silently WRONG
    instead: opaque bytes where a structured ``(dict, int)`` tuple belongs.

    That is a separate cqlite-core defect, deliberately OUT OF SCOPE for #3500,
    which is a Python-binding fix. CONSEQUENCE, stated plainly: the hashable
    projection for tuple-borne MAP KEYS is therefore currently UNEXERCISED by
    any fixture in this repository. ``value_to_hashable_key``'s new ``Tuple``
    arm is covered only through the set-element path above.

    The expected bytes below are built from Cassandra's composite framing
    (int32 BE length per component, ``-1`` for null) and cross-check against the
    golden's ``path`` values. The day ``parse_cell_path_key`` learns composites,
    these assertions FAIL — which is the point: the failure is the reminder to
    finish the map-key half of the hashable projection.
    """

    def test_map_key_is_currently_opaque_bytes(self, db):
        """id=1: two composite keys, each an opaque ``bytes`` blob."""
        value = _rows_by_id(db, "m_tuple_udt")[1].get("m_tuple_udt")
        assert value == {
            tuple_udt_int_serialized("charlie", 3, 8): 80,
            tuple_udt_int_serialized("delta", 4, 9): 90,
        }
        assert all(type(k) is bytes for k in value), (
            "a structured key here means cqlite-core's parse_cell_path_key now "
            "decodes composites — finish the map-key hashable projection (#3500) "
            "and re-pin this test"
        )

    def test_map_key_with_null_and_empty_udt_fields(self, db):
        """id=2: null-both-fields and empty-string-label keys stay distinct."""
        value = _rows_by_id(db, "m_tuple_udt")[2].get("m_tuple_udt")
        assert value == {
            tuple_udt_int_serialized(None, None, 0): 1,
            tuple_udt_int_serialized("", 0, 0): 2,
        }

    def test_single_key_partition(self, db):
        """id=3: one composite key."""
        value = _rows_by_id(db, "m_tuple_udt")[3].get("m_tuple_udt")
        assert value == {tuple_udt_int_serialized("solo", 99, 42): 7}

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "m_tuple_udt")[4].get("m_tuple_udt") is None


class TestSelectStarWholeRow:
    """``SELECT *`` over every partition — the shape a user actually runs.

    Before the fix this raised ``TypeError: unhashable type: 'dict'`` on the
    first partition, so NO row of this table was readable at all.
    """

    def test_select_star_returns_every_partition(self, db):
        """All four partitions decode, in Murmur3 token order 1, 2, 4, 3."""
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        ids = [row.get("id") for row in result.rows]
        assert ids == [1, 2, 4, 3], (
            "expected the golden's partition order (nb-1-big-Data.db.jsonl), got "
            f"{ids}"
        )

    def test_select_star_whole_row_values(self, db):
        """id=3's complete row — every column at once, exact values."""
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        rows = {row.get("id"): row for row in result.rows}
        row = rows[3]
        assert row.get("s_tuple_udt") == [(kp("solo", 99), 42)]
        assert row.get("s_set_udt") == [[kp("solo", 99)]]
        assert row.get("s_list_udt") == [[kp("solo", 99)]]
        assert row.get("f_set_tuple_udt") == [(kp("solo", 99), 42)]
        assert row.get("m_tuple_udt") == {
            tuple_udt_int_serialized("solo", 99, 42): 7
        }

    def test_select_star_sparse_row_values(self, db):
        """id=4: one populated column, four absent ones, in one ``SELECT *``."""
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        rows = {row.get("id"): row for row in result.rows}
        row = rows[4]
        assert row.get("s_tuple_udt") == [(kp("partial", 4), 4)]
        for absent in ("s_set_udt", "s_list_udt", "f_set_tuple_udt", "m_tuple_udt"):
            assert row.get(absent) is None, f"{absent} should be absent for id=4"


class TestFixtureResolutionContract:
    """The resolver itself (#3220) — the guard that stops this file passing vacuously.

    Every test above depends on the ``db`` fixture having found the RIGHT corpus
    root. On this fleet ``CQLITE_DATASETS_ROOT=/data/datasets``, whose
    ``sstables/`` does NOT contain ``test_nested_udt_keys`` — so a conftest-style
    single-root resolution would skip this entire file green and nobody would
    know. These cases pin the two properties that make that impossible.
    """

    def test_selection_is_by_evidence_not_by_root_order(self):
        """The chosen root must be one that actually holds the table.

        This is the #3220 defect in miniature: the old shape picked a root by
        KEYSPACE and committed to it, so a root holding the keyspace but not the
        table won the selection and the table was then declared absent.
        """
        chosen = _sstables_root_for_table(KEYSPACE, TABLE)
        assert _table_has_data(chosen, KEYSPACE, TABLE), (
            f"resolver returned {chosen}, which does not carry {KEYSPACE}.{TABLE}"
        )
        assert chosen in _sstables_root_candidates()

    def test_keyspace_present_but_table_absent_is_not_a_match(self, tmp_path):
        """A root with the keyspace dir but no table dir must not qualify."""
        (tmp_path / KEYSPACE).mkdir()
        assert _table_has_data(tmp_path, KEYSPACE, TABLE) is False

    def test_table_dir_without_a_data_db_is_not_a_match(self, tmp_path):
        """Presence is judged by a real ``*-Data.db``, never by a directory.

        This repo commits JSONL sidecars for fixtures whose binaries are
        gitignored, so a ``<table>-<uuid>/`` dir can exist with no SSTable in it
        — the exact shape that would otherwise be mistaken for a usable corpus.
        """
        table_dir = tmp_path / KEYSPACE / f"{TABLE}-cafebabe"
        table_dir.mkdir(parents=True)
        (table_dir / "nb-1-big-Data.db.jsonl").write_text("{}\n", encoding="utf-8")
        assert _table_has_data(tmp_path, KEYSPACE, TABLE) is False
        (table_dir / "nb-1-big-Data.db").write_bytes(b"\x00")
        assert _table_has_data(tmp_path, KEYSPACE, TABLE) is True

    def test_unresolvable_table_fails_closed_naming_every_root(self):
        """An unresolvable table RAISES and names every root searched.

        Never ``pytest.skip``: this fixture is git-committed, so "not found" is a
        broken checkout or a broken resolver, and a skip here would be a green
        report about a test that never ran.
        """
        with pytest.raises(AssertionError) as excinfo:
            _sstables_root_for_table(KEYSPACE, "no_such_table_3500")
        message = str(excinfo.value)
        for root in _sstables_root_candidates():
            assert str(root) in message, f"diagnostic omits candidate root {root}"
        assert "must never be skipped" in message

    def test_no_skip_anywhere_in_this_module(self):
        """Structural: this module must contain no skip of any kind.

        A ``pytest.skip(...)`` call or a ``@pytest.mark.skip``/``skipif``
        decorator added later would silently restore exactly the failure mode
        the rest of this class exists to prevent, and no behavioural test can
        see a skip that was never added.

        Judged over the PARSED SYNTAX TREE, not the file's text: this module
        discusses skipping at length in its docstrings, and a text search would
        red on its own prose — an assertion that fails on correct input is one
        that gets waived. Docstrings are ``Constant`` nodes and are therefore
        invisible here; only real attribute access counts.
        """
        import ast

        def dotted(node) -> str:
            parts: list[str] = []
            while isinstance(node, ast.Attribute):
                parts.append(node.attr)
                node = node.value
            if not isinstance(node, ast.Name):
                return ""
            parts.append(node.id)
            return ".".join(reversed(parts))

        tree = ast.parse(Path(__file__).read_text(encoding="utf-8"))
        offenders = sorted(
            {
                name
                for node in ast.walk(tree)
                if isinstance(node, ast.Attribute)
                for name in (dotted(node),)
                if name.startswith("pytest.")
                and any(part in ("skip", "skipif") for part in name.split("."))
            }
        )
        assert offenders == [], (
            f"skip constructs found in {Path(__file__).name}: {offenders} — this "
            "module is fail-closed by contract (#3220) and must never skip"
        )

    def test_the_no_skip_guard_can_actually_fail(self):
        """RED-verify the guard above against a planted skip.

        A structural assert over a file that legitimately contains none of the
        forbidden constructs passes whether or not its detection works, so the
        detection is exercised here against source that DOES contain them.
        Without this, ``test_no_skip_anywhere_in_this_module`` would be a
        vacuous green.
        """
        import ast

        def dotted(node) -> str:
            parts: list[str] = []
            while isinstance(node, ast.Attribute):
                parts.append(node.attr)
                node = node.value
            if not isinstance(node, ast.Name):
                return ""
            parts.append(node.id)
            return ".".join(reversed(parts))

        def offenders_in(source: str) -> list[str]:
            tree = ast.parse(source)
            return sorted(
                {
                    name
                    for node in ast.walk(tree)
                    if isinstance(node, ast.Attribute)
                    for name in (dotted(node),)
                    if name.startswith("pytest.")
                    and any(part in ("skip", "skipif") for part in name.split("."))
                }
            )

        # A skip CALL, a mark decorator, and a conditional mark are each caught.
        assert offenders_in("pytest.skip('nope')") == ["pytest.skip"]
        assert offenders_in(
            "@pytest.mark.skip\ndef t():\n    pass\n"
        ) == ["pytest.mark.skip"]
        assert offenders_in(
            "@pytest.mark.skipif(True, reason='x')\ndef t():\n    pass\n"
        ) == ["pytest.mark.skipif"]
        # Prose mentioning them is NOT a violation — the point of using the AST.
        assert offenders_in('"""never pytest.skip; no pytest.mark.skipif."""') == []
