"""Nested-UDT-in-a-hashable-position read fidelity — issue #3500.

WHAT IS UNDER TEST
------------------
The Python binding projects a CQL ``set`` to a Python ``set`` and a CQL ``map``
to a Python ``dict``, so every set ELEMENT and every map KEY must be reduced to
a HASHABLE Python object. That reduction lives in
``bindings/python/src/value.rs`` (``value_to_hashable_key`` / ``contains_udt``)
and was **not total** over the ``cqlite_core::Value`` tree: a UDT reached
through a TUPLE or through a NESTED COLLECTION fell through to the generic
converter, which yields an unhashable ``dict``/``list``, and the whole
``SELECT`` raised.

Measured on this fixture BEFORE the fix (verbatim):

===============  ===========================================
column           exception
===============  ===========================================
s_tuple_udt      ``TypeError: unhashable type: 'dict'``
s_set_udt        ``TypeError: unhashable type: 'list'``
f_set_tuple_udt  ``TypeError: unhashable type: 'dict'``
f_map_tuple_udt  ``TypeError: unhashable type: 'dict'``
f_map_set_udt    ``TypeError: unhashable type: 'list'``
``SELECT *``     ``TypeError: unhashable type: 'dict'``
===============  ===========================================

WHICH COLUMNS COVER ``value_to_hashable_key``, AND WHICH DO NOT
---------------------------------------------------------------
Only the two FROZEN-MAP columns reach that function. A ``set`` whose elements
contain a UDT takes ``set_to_py``'s list fallback and converts elements with
``value_to_py``; a MULTICELL map's keys arrive as opaque ``Value::Blob`` from
the scalar-only ``parse_cell_path_key`` (#3612). A frozen map escapes both: its
keys are decoded structurally and ``map_to_py`` projects every one of them
through ``value_to_hashable_key``. So ``f_map_tuple_udt`` covers the ``Tuple``
arm, ``f_map_set_udt`` the ``Set`` arm, and their id=2 keys are the only values
in this repository that execute the ``Udt`` arm's ``None => py.None()`` branch.
Without those two columns all three could regress with zero test failures.

``contains_udt`` IS A SEPARATE MATTER, AND ITS ``Map`` ARM NEEDED ITS OWN
COLUMNS. ``set_to_py`` is that function's only caller, so the value it inspects
is always a SET ELEMENT — a ``Map`` at the TOP of a column is never passed to
it. Its ``Map`` arm (``any(|(k, v)| contains_udt(k) || contains_udt(v))``) was
therefore covered by NOTHING until ``s_map_udt_key`` / ``s_map_udt_val`` put a
frozen map INSIDE a set element, one column per half because ``||``
short-circuits. A regression there is SILENT rather than a ``TypeError``: the
hashable projection is total, so the element still projects hashably and the
column merely comes back as a ``frozenset`` instead of #804's ``list`` of
``dict``s. See :class:`TestSetElementFrozenMapWithUdtKeyHalf`.

THE ORACLE
----------
Real Cassandra 5.0.2-written bytes:
``test-data/datasets/sstables/test_nested_udt_keys/nested_udt_keys-*`` (BIG
``nb``, uncompressed, 4 partitions), declared by
``test-data/schemas/nested-udt-keys.cql`` and generated by
``test-data/scripts/generate-nested-udt-keys.sh``. Every expectation below is
derived from the committed sstabledump golden ``nb-1-big-Data.db.jsonl`` plus
the generator's own INSERT statements — never from CQLite's prior output. A
CQLite-written/CQLite-read round trip could not detect this class at all.

Element ORDER is Cassandra's: a CQL ``set``/``map`` is stored sorted by the
serialized element/key, so the sequences asserted here are the golden's
cell-path order, not the insertion order.

WHY THESE TESTS ARE pytest AND NOT RUST ``#[test]``
---------------------------------------------------
``cargo test -p cqlite-py`` is structurally impossible — a pyo3 cdylib's test
harness cannot link libpython — so a Rust unit test beside the fix would
execute in no lane on any machine (``scripts/agent-gate.sh``'s
``binding-rust-tests`` census grep-counts those attributes precisely in order to
DECLARE them unrunnable). These run in the full gate's ``python-bindings``
component and the #1893 ``--lite`` python tier.

FAIL-CLOSED, NEVER SKIP (issue #3220)
-------------------------------------
``conftest.py`` resolves ONE corpus root and prefers ``$CQLITE_DATASETS_ROOT``,
so an in-repo COMMITTED fixture is invisible to it and ``skip_if_no_datasets()``
would skip green forever. Neither root is a superset of the other, so no fixed
env-first/checkout-first rule is correct. This module therefore resolves the
corpus root PER TABLE by walking EVERY candidate root for that table's
``*-Data.db`` (the Python mirror of
``cqlite-core/tests/support/datasets_root.rs::sstables_root_for_table``) and
asserts PER CASE: the fixture is git-committed, so it is ``must_run`` and
fail-closed UNCONDITIONALLY — there is no ``pytest.skip`` in this file and no
suite-wide ``assert ran > 0`` (which cannot see one case skipping behind its
siblings).
"""

import ast
import os
from pathlib import Path

import pytest

import cqlite

KEYSPACE = "test_nested_udt_keys"
TABLE = "nested_udt_keys"
SCHEMA_FILE = "nested-udt-keys.cql"


# =============================================================================
# The no-skip detector — ONE definition, used by BOTH the guard and its
# RED-verify test (issue #3500)
# =============================================================================

#: The ONLY ``pytest`` attributes this module may touch. An ALLOWLIST, not a
#: blocklist: a blocklist can only ever name the evasion someone already thought
#: of, and the first version of this guard proved it — it caught
#: ``pytest.skip`` / ``pytest.mark.skip`` / ``pytest.mark.skipif`` and missed
#: ``pytest.importorskip``, ``pytest.mark.xfail`` and
#: ``from pytest import skip as _skip``, all of which skip just as green.
#: Inverting it closes the whole family in one move: anything not named here
#: FAILS, including a construct nobody has invented yet. Extend it only when
#: this module genuinely needs another pytest API — and never with a
#: skip/xfail-capable one.
_PYTEST_ALLOWED_ATTRS = frozenset({"fixture", "raises", "fail", "approx"})

#: The ONE permitted spelling of a pytest import in this module is a bare,
#: unaliased ``import pytest``. An ALLOWLIST of a single FORM, for exactly the
#: reason :data:`_PYTEST_ALLOWED_ATTRS` is one. The import channel was left as a
#: blocklist of forbidden NAMES (``skip``, ``skipif``, ``xfail``, …) and that is
#: precisely why an eighth evasion existed: ``from pytest import *`` imports
#: every one of those names while naming none of them, and binds them with no
#: ``pytest.`` prefix for the attribute scan to read. There is nothing to extend
#: here — any other route into these packages (aliased, submodule, or a
#: ``from``-import of anything at all, star included) is an offender BY
#: CONSTRUCTION, so evasion nine cannot be a new import spelling. ``_pytest`` is
#: listed because ``from _pytest.outcomes import skip`` is the same skip by its
#: private path.
_PYTEST_IMPORT_PACKAGES = frozenset({"pytest", "_pytest"})


def _pytest_import_offenders(node: ast.AST) -> set[str]:
    """Offending pytest imports in ONE ``import`` / ``from ... import``.

    One rule, stated positively: a bare unaliased ``import pytest`` is the only
    permitted form, and every other way of reaching
    :data:`_PYTEST_IMPORT_PACKAGES` is reported. Enumerating forbidden NAMES is
    what let ``from pytest import *`` through; enumerating the one permitted
    FORM cannot be evaded by choosing a different name, because no name is what
    makes a form permitted.
    """
    offenders: set[str] = set()
    if isinstance(node, ast.Import):
        for alias in node.names:
            if alias.name.split(".")[0] not in _PYTEST_IMPORT_PACKAGES:
                continue
            if alias.name == "pytest" and alias.asname is None:
                continue  # the one permitted spelling
            bound = f" as {alias.asname}" if alias.asname else ""
            offenders.add(f"import {alias.name}{bound}")
        return offenders
    if not isinstance(node, ast.ImportFrom):
        return offenders
    # A relative import (``level`` > 0, ``module`` possibly None) resolves
    # inside this test package and cannot reach pytest.
    if node.level or node.module is None:
        return offenders
    if node.module.split(".")[0] not in _PYTEST_IMPORT_PACKAGES:
        return offenders
    for alias in node.names:
        bound = f" as {alias.asname}" if alias.asname else ""
        offenders.add(f"from {node.module} import {alias.name}{bound}")
    return offenders


def _dotted_name(node: ast.AST) -> str:
    """``a.b.c`` for a chain of ``Attribute`` nodes rooted at a ``Name``."""
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if not isinstance(node, ast.Name):
        return ""
    parts.append(node.id)
    return ".".join(reversed(parts))


def _skip_offenders(source: str) -> list[str]:
    """Every skip-capable construct in ``source``, judged over the SYNTAX TREE.

    THE SINGLE DEFINITION. The guard
    (``test_no_skip_anywhere_in_this_module``) and its RED-verify
    (``test_the_no_skip_guard_can_actually_fail``) both call THIS function, so
    weakening the predicate — the exact edit someone makes in order to land a
    skip — reds the RED-verify too. The two used to hold verbatim COPIES of the
    predicate, which meant the anti-vacuity proof was bound to a copy and not to
    the detector, i.e. the proof could stay green while the detector was gutted.

    Judged over the parsed tree, not the file's text: this module discusses
    skipping at length in its docstrings, and a text search would red on its own
    prose — an assertion that fails on correct input is one that gets waived.
    Docstrings are ``Constant`` nodes and are invisible here.

    TWO channels, and BOTH are allowlists — there is no list of forbidden
    spellings left to be incomplete:

    * the ATTRIBUTE channel: any ``pytest.<x>`` access whose first attribute is
      not in :data:`_PYTEST_ALLOWED_ATTRS` (so ``pytest.mark.anything``,
      ``pytest.importorskip`` and ``pytest.skip`` are all offenders);
    * the IMPORT channel: anything but a bare unaliased ``import pytest`` —
      see :func:`_pytest_import_offenders`. This half USED to be a blocklist of
      forbidden names, which is why an eighth evasion (``from pytest import *``)
      existed after seven had been named individually.

    STATED LIMIT — this is a SOURCE SCANNER, and a source scanner over Python
    cannot be complete. Recorded here deliberately: a guard documented as
    partial is honest, while one claiming "fail-closed, no skip anywhere" with a
    known one-line evasion is misleading. No AST rule can see any of these, and
    they are the acknowledged residual:

    * a dynamically spelled attribute — ``getattr(pytest, "sk" + "ip")()``;
    * a dynamic import — ``__import__("pytest").skip()``;
    * anything routed through ``exec`` / ``eval``;
    * a skip raised from an imported helper, whose source is not this file;
    * a marker applied to this module from OUTSIDE it — a ``conftest.py`` hook,
      an ini-file marker, or ``--deselect`` / ``-k`` on the command line.

    If a ninth evasion ever appears, the answer is NOT a tenth pattern:
    replace this source scan with an OUTCOME-based check — assert that every
    test function defined in this module actually collected AND ran (compare a
    per-test ran-marker, or a count, against the module's own definitions). An
    outcome assertion is spelling-independent and closes the entire family
    above, dynamic and out-of-file cases included. It is deliberately NOT built
    now: it needs a collection hook to observe, and two allowlists are
    proportionate to the risk this one module carries.
    """
    tree = ast.parse(source)
    # An attribute chain reports ONCE, at its outermost node: without this,
    # `pytest.mark.skip` would report both "pytest.mark" and "pytest.mark.skip"
    # and the RED-verify's exact-match assertions would be about noise.
    nested = {
        node.value for node in ast.walk(tree) if isinstance(node, ast.Attribute)
    }
    offenders: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Attribute) and node not in nested:
            name = _dotted_name(node)
            if not name.startswith("pytest."):
                continue
            if name.split(".")[1] not in _PYTEST_ALLOWED_ATTRS:
                offenders.add(name)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            offenders.update(_pytest_import_offenders(node))
    return sorted(offenders)


# =============================================================================
# Root resolution — committed schema checkout-relative (#3148), corpus per
# table across EVERY candidate root (#3220). Deliberately local to this module:
# conftest's single-root constants are the thing that would hide the fixture.
# =============================================================================


def _workspace_root() -> Path:
    """The checkout root, anchored on the workspace-root ``Cargo.toml`` marker.

    Same rule as ``test-data/support/fixture_roots.rs::workspace_root`` — the
    nearest ancestor whose ``Cargo.toml`` declares ``[workspace]``. Anchoring on
    a marker rather than counting ``..`` levels keeps this correct if the file
    ever moves.
    """
    here = Path(__file__).resolve()
    for ancestor in here.parents:
        manifest = ancestor / "Cargo.toml"
        if not manifest.is_file():
            continue
        try:
            text = manifest.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if any(line.lstrip().startswith("[workspace]") for line in text.splitlines()):
            return ancestor
    raise AssertionError(
        f"no [workspace] Cargo.toml found in any ancestor of {here} — cannot "
        "resolve the checkout root for the committed #3500 fixture"
    )


def _schemas_root() -> Path:
    """The COMMITTED schema-fixture root.

    Checkout-relative source, never derived from ``CQLITE_DATASETS_ROOT``.
    ``CQLITE_SCHEMAS_ROOT`` is an optional out-of-tree override and MUST be
    absolute: the gate resolves a relative value against the repo root while
    pytest runs from the package dir, so it would certify one schemas root while
    the tests read another (#3148). A relative value is REJECTED, never resolved.

    An override that is absolute but NOT a readable directory is rejected too.
    It used to fall back silently to the checkout, which is the guessing posture
    #3148 exists to remove: the operator asked for one schemas root, the run
    used another, and the report said nothing. Both refusals name the value.
    """
    raw = os.environ.get("CQLITE_SCHEMAS_ROOT")
    if raw is not None and raw.strip():
        if any(ord(ch) < 32 or ord(ch) == 127 for ch in raw):
            pytest.fail(
                f"CQLITE_SCHEMAS_ROOT must not contain control characters, got {raw!r}"
            )
        override = Path(raw)
        if not override.is_absolute():
            pytest.fail(
                f"CQLITE_SCHEMAS_ROOT must be an ABSOLUTE path, got {raw!r} — a "
                "relative value cannot mean the same thing to the gate (CWD = repo "
                "root) and to pytest (CWD = package dir), so the gate would certify "
                "a schemas root the run never used (#3148)"
            )
        if not override.is_dir():
            pytest.fail(
                f"CQLITE_SCHEMAS_ROOT={raw!r} is absolute but is not a readable "
                "directory — refused rather than silently falling back to the "
                "checkout, which would run against a schemas root the operator "
                "did not ask for (#3148)"
            )
        return override
    return _workspace_root() / "test-data" / "schemas"


def _sstables_root_candidates() -> list[Path]:
    """Every ``sstables/`` root to search, in order.

    An ORDER, not a preference: ``_sstables_root_for_table`` picks by EVIDENCE
    (which root actually holds the table), because neither root is a superset of
    the other — the fetched corpus carries keyspaces the checkout does not, and
    the checkout carries committed fixtures (this one) the fetched corpus does
    not (#3104/#3220).
    """
    candidates: list[Path] = []
    env_root = os.environ.get("CQLITE_DATASETS_ROOT")
    if env_root and env_root.strip():
        root = Path(env_root)
        nested = root / "sstables"
        candidates.append(nested if nested.is_dir() else root)
    checkout = _workspace_root() / "test-data" / "datasets" / "sstables"
    if checkout not in candidates:
        candidates.append(checkout)
    return candidates


def _table_has_data(root: Path, keyspace: str, table: str) -> bool:
    """True when ``<root>/<keyspace>/<table>-*/`` holds a ``*-Data.db`` FILE.

    Presence is judged by a real Data.db component, never by directory
    existence: this repo commits JSONL sidecars for fixtures whose binaries are
    gitignored, so a ``<table>-<uuid>/`` dir can exist with no SSTable in it.
    """
    ks_dir = root / keyspace
    if not ks_dir.is_dir():
        return False
    prefix = f"{table}-"
    try:
        table_dirs = [
            d for d in ks_dir.iterdir() if d.is_dir() and d.name.startswith(prefix)
        ]
    except OSError:
        return False
    for table_dir in table_dirs:
        try:
            entries = list(table_dir.iterdir())
        except OSError:
            continue
        if any(e.is_file() and e.name.endswith("-Data.db") for e in entries):
            return True
    return False


def _sstables_root_for_table(keyspace: str, table: str) -> Path:
    """The candidate root that really carries ``<keyspace>/<table>-*/…-Data.db``.

    FAIL-CLOSED, naming every root searched. This fixture is git-committed, so
    "not found" is a broken checkout or a broken resolver — never a reason to
    skip.
    """
    candidates = _sstables_root_candidates()
    for root in candidates:
        if _table_has_data(root, keyspace, table):
            return root
    searched = ", ".join(str(c) for c in candidates)
    raise AssertionError(
        f"COMMITTED fixture {keyspace}.{table} carries no *-Data.db under any "
        f"candidate root — searched [{searched}]. This fixture is checked into git "
        "(issue #3500), so this is a broken checkout or a broken resolver, not a "
        "missing download; it must never be skipped (#3220)."
    )


@pytest.fixture(scope="module")
def db():
    """Open the #3500 fixture through the real binding. Never skips."""
    root = _sstables_root_for_table(KEYSPACE, TABLE)
    schema = _schemas_root() / SCHEMA_FILE
    assert schema.is_file(), (
        f"committed schema {schema} is unreadable — it is checked-in source "
        "(#3148), so this is fail-closed, not a skip"
    )
    with cqlite.open(root, schema=schema) as database:
        yield database


def _rows_by_id(database, projection: str) -> dict:
    """``{id: row}`` for a projection, pinning the partitions AND the shape.

    The shape assertion is what makes every ``row.get(col) is None`` assertion
    below SELF-SUFFICIENT. ``Row.get`` returns ``None`` for a column that is not
    in the result at all (``bindings/python/src/result.rs``: a miss falls back to
    the default, which is ``None``), so on its own ``assert row.get(col) is
    None`` cannot tell "absent for THIS row" from "never selected" or "silently
    dropped from the projection" — it would be leaning on a sibling test for the
    half that matters. Asserting the row's key set here removes that dependency
    once for every caller.
    """
    columns = [c.strip() for c in projection.split(",")]
    expected_shape = sorted(["id", *columns])
    result = database.execute(f"SELECT id, {projection} FROM {KEYSPACE}.{TABLE}")
    for row in result.rows:
        assert sorted(row.to_dict()) == expected_shape, (
            f"projection 'id, {projection}' returned columns "
            f"{sorted(row.to_dict())}, expected {expected_shape} — a None below "
            "would otherwise be indistinguishable from a dropped column"
        )
    rows = {row.get("id"): row for row in result.rows}
    assert sorted(rows) == [1, 2, 3, 4], (
        f"expected partitions 1..4 from the committed fixture, got {sorted(rows)}"
    )
    return rows


# =============================================================================
# Expected-value helpers
# =============================================================================


def kp(label, rank) -> dict:
    """The Python projection of one ``key_part`` UDT value.

    ``udt_to_py`` emits the two metadata keys plus every schema field, including
    fields whose value is NULL (they arrive as ``None``, matching the golden's
    ``"label": null``).
    """
    return {
        "_type": "key_part",
        "_keyspace": KEYSPACE,
        "label": label,
        "rank": rank,
    }


def kp_hashable(label, rank) -> frozenset:
    """The HASHABLE projection of one ``key_part`` UDT value.

    ``value_to_hashable_key``'s ``Udt`` arm emits a ``frozenset`` of
    ``(field_name, value)`` pairs — the two metadata fields plus every schema
    field, with a NULL field arriving as ``None`` from its
    ``None => py.None()`` branch. Deliberately DIFFERENT from :func:`kp`, which
    is ``udt_to_py``'s ``dict``: the two functions are separate code paths and
    conflating them is what made #3500 invisible.
    """
    return frozenset(
        {
            ("_type", "key_part"),
            ("_keyspace", KEYSPACE),
            ("label", label),
            ("rank", rank),
        }
    )


def _component(payload) -> bytes:
    """One Cassandra composite component: int32 BE length + bytes; -1 = null."""
    if payload is None:
        return b"\xff\xff\xff\xff"
    return len(payload).to_bytes(4, "big") + payload


def _key_part_serialized(label, rank) -> bytes:
    """``frozen<key_part>`` as Cassandra serializes it (label text, rank int)."""
    label_bytes = None if label is None else label.encode("utf-8")
    rank_bytes = None if rank is None else rank.to_bytes(4, "big", signed=True)
    return _component(label_bytes) + _component(rank_bytes)


def tuple_udt_int_serialized(label, rank, trailing) -> bytes:
    """``tuple<frozen<key_part>, int>`` as Cassandra serializes it.

    Used ONLY by the ``m_tuple_udt`` documented-gap test: the map key currently
    arrives as these OPAQUE bytes instead of a structured tuple. Cross-checks
    against the golden's ``path`` values byte for byte.
    """
    return _component(_key_part_serialized(label, rank)) + _component(
        trailing.to_bytes(4, "big", signed=True)
    )


# =============================================================================
# The four issue shapes + the frozen-outer column
# =============================================================================


class TestTupleBorneUdtInSetElement:
    """``s_tuple_udt`` — ``set<frozen<tuple<frozen<key_part>, int>>>``.

    Issue #3500 shape 1: the UDT is reached through a TUPLE. Before the fix this
    raised ``TypeError: unhashable type: 'dict'`` — ``contains_udt`` did not
    traverse ``Tuple``, so the set took the frozenset path, and
    ``value_to_hashable_key`` had no ``Tuple`` arm so the element became a
    Python tuple containing an unhashable ``dict``.
    """

    def test_multi_element_partition(self, db):
        """id=1: three tuples, two sharing the same UDT with different ints.

        Order is Cassandra's sorted order (golden cell paths ``alpha\\:1:1``,
        ``alpha\\:1:2``, ``zulu\\:26:7``), NOT the insertion order.
        """
        row = _rows_by_id(db, "s_tuple_udt")[1]
        assert row.get("s_tuple_udt") == [
            (kp("alpha", 1), 1),
            (kp("alpha", 1), 2),
            (kp("zulu", 26), 7),
        ]

    def test_null_udt_fields(self, db):
        """id=2: NULL UDT fields inside the hashable position.

        Reaches ``value_to_hashable_key``'s ``None => py.None()`` UDT-field
        branch, which no committed fixture previously exercised inside a
        hashable position. Golden order: ``\\@\\:5:2`` then
        ``nullrank\\:\\@:1`` (``\\@`` is sstabledump's null marker).
        """
        row = _rows_by_id(db, "s_tuple_udt")[2]
        assert row.get("s_tuple_udt") == [
            (kp(None, 5), 2),
            (kp("nullrank", None), 1),
        ]

    def test_single_element_partition(self, db):
        """id=3: exactly one element, the same UDT value as the other columns."""
        row = _rows_by_id(db, "s_tuple_udt")[3]
        assert row.get("s_tuple_udt") == [(kp("solo", 99), 42)]

    def test_sparse_row(self, db):
        """id=4: this column decodes even though it is the only one written.

        Asserts THIS column only. The other six columns of id=4 are checked
        where they belong — each column class has its own
        ``test_absent_in_sparse_row``, and ``TestSelectStarWholeRow`` checks all
        of them together in one ``SELECT *``.
        """
        rows = _rows_by_id(db, "s_tuple_udt")
        assert rows[4].get("s_tuple_udt") == [(kp("partial", 4), 4)]

    def test_elements_are_plain_tuples_and_dicts(self, db):
        """Exact Python types, not merely equal structures."""
        value = _rows_by_id(db, "s_tuple_udt")[3].get("s_tuple_udt")
        assert type(value) is list
        assert type(value[0]) is tuple
        assert type(value[0][0]) is dict
        assert type(value[0][1]) is int


class TestNestedSetBorneUdtInSetElement:
    """``s_set_udt`` — ``set<frozen<set<frozen<key_part>>>>``.

    Issue #3500 shape 2: the UDT is reached through a NESTED SET. Before the fix
    this raised ``TypeError: unhashable type: 'list'`` — ``contains_udt`` did not
    traverse ``Set``, so the OUTER set took the frozenset path, while the INNER
    set correctly detected its UDT elements and returned an unhashable ``list``.
    """

    def test_multi_element_partition(self, db):
        """id=1: a two-element inner set and a one-element inner set.

        Inner-set order is Cassandra's (golden path bytes: ``alpha`` before
        ``beta``); outer order is the golden's cell-path order.
        """
        row = _rows_by_id(db, "s_set_udt")[1]
        assert row.get("s_set_udt") == [
            [kp("alpha", 1), kp("beta", 2)],
            [kp("gamma", 3)],
        ]

    def test_null_udt_fields(self, db):
        """id=2: one inner set, both UDTs carrying a NULL ``rank``.

        Golden path bytes ``…ffffffffffffffff`` (both fields null) sort before
        ``…6e756c6c72616e6b32ffffffff`` (``nullrank2``, null rank).
        """
        row = _rows_by_id(db, "s_set_udt")[2]
        assert row.get("s_set_udt") == [
            [kp(None, None), kp("nullrank2", None)],
        ]

    def test_single_element_partition(self, db):
        """id=3: one inner set holding one UDT."""
        row = _rows_by_id(db, "s_set_udt")[3]
        assert row.get("s_set_udt") == [[kp("solo", 99)]]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column, so it must be ``None``, not ``[]``."""
        assert _rows_by_id(db, "s_set_udt")[4].get("s_set_udt") is None


class TestNestedListBorneUdtInSetElement:
    """``s_list_udt`` — ``set<frozen<list<frozen<key_part>>>>``: the AC5 CONTROL.

    THIS SHAPE'S OUTPUT CHANGED, DELIBERATELY. Read this before treating a diff
    here as a regression.

    Alone among issue #3500's four shapes, this one did NOT raise before the
    fix. ``contains_udt`` returned ``False``, so the outer set took the frozenset
    path, and ``value_to_hashable_key``'s pre-existing ``List`` and ``Udt`` arms
    projected each element to a hashable form — yielding::

        frozenset({(frozenset({('_type', 'key_part'), ('label', 'one'), …}),
                    frozenset({… 'two' …})), …})

    i.e. a frozenset of tuples of frozensets, measured on this exact fixture
    before the fix.

    AC1 mandates that ``contains_udt`` traverse ``List``. That NECESSARILY makes
    ``contains_udt`` true here, so the column now takes the list path and
    returns a plain ``list`` of ``list`` of ``dict`` — the same shape as
    ``s_set_udt`` above.

    WHY THIS IS THE INTENDED RESOLUTION of the AC1-vs-AC5 conflict (escalated on
    the issue thread and resolved in favour of AC1):

    * AC1 is the explicit, testable mandate; AC5 ("no change to shapes that
      already work") and AC1 cannot both hold literally for this column.
    * The issue's own shape table already records this column's output as
      diverging from the Node/CLI rendering — that divergence is #3497's, not
      this issue's, so the shape was never canonical.
    * The defect's stated TELL is that "behavior depends on which nested
      collection you happen to use". Removing that asymmetry IS the fix: all
      four nestings now project identically.
    * The only alternative — keep the frozenset path and lean on the
      now-total hashable projection — would re-shape ``set<frozen<udt>>``
      itself and break #804/#795, a far larger AC5 violation.

    This NARROWS #3497 (the Python binding is now self-consistent across
    nestings) without CLOSING it: aligning the ``set``-of-UDT projection across
    Python/Node/CLI is still that issue's job.
    """

    def test_intended_new_shape_multi_element(self, db):
        """id=1: two lists with the same elements in DIFFERENT order.

        They are distinct list values — the case a ``set`` of ``list`` exists to
        test — and each now keeps its own order inside a plain Python list, which
        the pre-fix frozenset projection could express only as a tuple of
        frozensets.
        """
        row = _rows_by_id(db, "s_list_udt")[1]
        assert row.get("s_list_udt") == [
            [kp("one", 1), kp("two", 2)],
            [kp("two", 2), kp("one", 1)],
        ]

    def test_intended_new_shape_is_not_a_frozenset(self, db):
        """The pre-fix container types are gone at BOTH levels.

        ``type(value) is list`` is the assertion that reds on a revert of AC1
        (the pre-fix projection was a ``frozenset``), and the two nested checks
        pin the inner levels. A further ``assert not isinstance(value,
        frozenset)`` used to sit here and has been removed: after ``type(value)
        is list`` it cannot fail for any input, so it read as coverage while
        testing nothing.
        """
        value = _rows_by_id(db, "s_list_udt")[1].get("s_list_udt")
        assert type(value) is list, f"expected list, got {type(value).__name__}"
        assert type(value[0]) is list
        assert type(value[0][0]) is dict

    def test_intended_new_shape_null_fields(self, db):
        """id=2: an EMPTY-string label (``''``) stays distinct from ``None``."""
        row = _rows_by_id(db, "s_list_udt")[2]
        assert row.get("s_list_udt") == [[kp("", 0), kp(None, 9)]]

    def test_intended_new_shape_single_element(self, db):
        """id=3: one inner list holding one UDT."""
        row = _rows_by_id(db, "s_list_udt")[3]
        assert row.get("s_list_udt") == [[kp("solo", 99)]]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "s_list_udt")[4].get("s_list_udt") is None


class TestFrozenOuterSetOfTupleBorneUdt:
    """``f_set_tuple_udt`` — ``frozen<set<frozen<tuple<frozen<key_part>, int>>>>``.

    Not one of the issue's four shapes; it exists because the frozen-outer
    column travels a DIFFERENT decode path. A non-frozen collection arrives as
    per-element CELL PATHS, while a frozen one arrives as a single value cell,
    and the two produce structurally different ``Value`` trees — measured on
    this fixture:

    * multicell:     ``Set([Frozen(Tuple([Frozen(Udt), Integer])), …])``
    * frozen outer:  ``Frozen(Set([Tuple([Udt, Integer]), …]))``  — NO inner
      ``Frozen`` wrappers at all.

    What this column therefore proves, precisely: the SINGLE-VALUE-CELL decode
    path produces a tree with NO inner ``Frozen`` wrappers, and the traversal
    handles it. It does NOT prove anything ``s_tuple_udt`` does not — that
    column reds on an unwrap-only fix too. The claim once made here, that "a fix
    that only unwrapped ``Frozen`` would still raise here", was true and not
    distinguishing. Before the fix this column raised
    ``TypeError: unhashable type: 'dict'``.
    """

    def test_multi_element_partition(self, db):
        """id=1: two tuples, golden order ``frozen-a`` then ``frozen-b``."""
        row = _rows_by_id(db, "f_set_tuple_udt")[1]
        assert row.get("f_set_tuple_udt") == [
            (kp("frozen-a", 11), 1),
            (kp("frozen-b", 12), 2),
        ]

    def test_null_udt_field(self, db):
        """id=2: ``{label: null, rank: 7}`` — the golden's ``"label": null``."""
        row = _rows_by_id(db, "f_set_tuple_udt")[2]
        assert row.get("f_set_tuple_udt") == [(kp(None, 7), 3)]

    def test_single_element_partition(self, db):
        """id=3: one tuple."""
        row = _rows_by_id(db, "f_set_tuple_udt")[3]
        assert row.get("f_set_tuple_udt") == [(kp("solo", 99), 42)]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "f_set_tuple_udt")[4].get("f_set_tuple_udt") is None


class TestTupleBorneUdtAsMapKey:
    """``m_tuple_udt`` — ``map<frozen<tuple<frozen<key_part>, int>>, int>``.

    A DOCUMENTED GAP, NOT DESIRED BEHAVIOUR — this test pins what CQLite does
    TODAY so that fixing the core reds it.

    Issue #3500's shape 3 is the tuple-borne UDT in the MAP-KEY position, and it
    is **not reachable through the Python binding today**: the map key never
    arrives as a structured ``Value::Tuple``. ``parse_cell_path_key``
    (``cqlite-core/src/storage/sstable/reader/parsing/row_decoder/complex_column.rs``)
    is a scalar-only allowlist whose catch-all arm returns ``Value::Blob``, so a
    composite map key decodes as the RAW SERIALIZED KEY BYTES. A ``bytes`` object
    is hashable, so there is no ``TypeError`` here — the value is silently WRONG
    instead: opaque bytes where a structured ``(dict, int)`` tuple belongs.

    That is a separate cqlite-core defect, deliberately OUT OF SCOPE for #3500,
    which is a Python-binding fix. CONSEQUENCE, stated plainly: the hashable
    projection for tuple-borne MAP KEYS is therefore currently UNEXERCISED by
    any fixture in this repository. ``value_to_hashable_key``'s new ``Tuple``
    arm is covered only through the set-element path above.

    AC SHAPE 3 IS DISCHARGED BY THIS PINNED GAP TEST PLUS #3612 — BY LEAD
    RULING, not by a worker descope. Issue #3500's acceptance criteria expect
    shape 3 to raise ``TypeError``; it cannot, because the key never becomes a
    ``dict`` in the first place (see above). The lead amended the AC accordingly
    (#3500 thread, 2026-08-30) and raised #3612 to P1. A later spec audit should
    read shape 3 as AMENDED-AND-SATISFIED, not unmet.

    The expected bytes below are built from Cassandra's composite framing
    (int32 BE length per component, ``-1`` for null) and cross-check against the
    golden's ``path`` values.

    EVERY ASSERTION IN THIS CLASS CARRIES THE SAME MESSAGE, AND THAT IS
    DELIBERATE: the day ``parse_cell_path_key`` learns composites — i.e. when
    **#3612** is fixed — these assertions FAIL, and a bare dict diff would say
    nothing about why. A gap assertion that cannot explain its own failure is a
    comment with a test harness around it. Each message therefore names #3612 as
    the trigger, says the failure is the EXPECTED signal that #3612 landed, and
    says what to do: re-pin the expectation to the structured ``(dict, int)``
    tuple key that the frozen-map columns already produce, and finish the
    map-key half of the hashable projection (``bindings/python/src/value.rs``,
    where #3500 put it). #3500 is cited only as WHERE the projection lives — it
    is this PR and will be closed, and a gap marker pointing at a closed issue
    is how a gap becomes permanent.
    """

    #: Attached to every assertion in this class. See the class docstring.
    _GAP = (
        "m_tuple_udt: DOCUMENTED GAP #3612 (multicell map keys decode as opaque "
        "Value::Blob via the scalar-only parse_cell_path_key). A FAILURE HERE IS "
        "THE EXPECTED SIGNAL THAT #3612 HAS BEEN FIXED, not a regression of this "
        "test: re-pin the expectation to the structured (dict, int) tuple key the "
        "frozen-map columns already produce, and finish the map-key half of the "
        "hashable projection in bindings/python/src/value.rs (added by #3500, "
        "which is closed — #3612 is the live issue)."
    )

    def test_map_key_is_currently_opaque_bytes(self, db):
        """id=1: two composite keys, each an opaque ``bytes`` blob."""
        value = _rows_by_id(db, "m_tuple_udt")[1].get("m_tuple_udt")
        assert value == {
            tuple_udt_int_serialized("charlie", 3, 8): 80,
            tuple_udt_int_serialized("delta", 4, 9): 90,
        }, self._GAP
        assert all(type(k) is bytes for k in value), self._GAP

    def test_map_key_with_null_and_empty_udt_fields(self, db):
        """id=2: null-both-fields and empty-string-label keys stay distinct."""
        value = _rows_by_id(db, "m_tuple_udt")[2].get("m_tuple_udt")
        assert value == {
            tuple_udt_int_serialized(None, None, 0): 1,
            tuple_udt_int_serialized("", 0, 0): 2,
        }, self._GAP

    def test_single_key_partition(self, db):
        """id=3: one composite key."""
        value = _rows_by_id(db, "m_tuple_udt")[3].get("m_tuple_udt")
        assert value == {tuple_udt_int_serialized("solo", 99, 42): 7}, self._GAP

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column.

        Carries the gap message too: #3612 does not change this expectation (an
        absent column is ``None`` either way), so if THIS one ever reds, #3612 is
        not the explanation and the message says which parts to re-pin.
        """
        assert _rows_by_id(db, "m_tuple_udt")[4].get("m_tuple_udt") is None, self._GAP


class TestFrozenMapWithTupleBorneUdtKey:
    """``f_map_tuple_udt`` — ``frozen<map<frozen<tuple<frozen<key_part>, int>>, int>>``.

    THE COLUMN THAT COVERS ``value_to_hashable_key``'s ``Tuple`` ARM. Read this
    before deleting it as redundant with ``s_tuple_udt``.

    Every OTHER column in this fixture leaves the new arm unexecuted, for two
    independent reasons:

    * a ``set`` whose elements contain a UDT takes ``set_to_py``'s LIST
      fallback, which converts elements with ``value_to_py`` and never calls
      ``value_to_hashable_key``. Issue #3500's own AC1 — make ``contains_udt``
      total — is what makes that true of every UDT-bearing set column;
    * a MULTICELL map's keys arrive as opaque ``Value::Blob`` from the
      scalar-only ``parse_cell_path_key`` (see ``TestTupleBorneUdtAsMapKey``
      and #3612), so they never reach the ``Tuple`` arm either.

    A FROZEN map escapes both. It arrives as ONE value cell, and
    ``parse_frozen_map_value`` → ``read_frozen_element`` →
    ``parse_value_from_raw_bytes``
    (``cqlite-core/src/storage/sstable/reader/parsing/row_decoder/``) decodes
    each KEY structurally into a real ``Value::Frozen(Value::Tuple([...]))``.
    ``map_to_py`` then projects every key through ``value_to_hashable_key``.

    RED-VERIFIED, not argued: with this fixture and the PRE-FIX binding
    (commit ``01c28646b``) this column raises
    ``TypeError: unhashable type: 'dict'`` — issue #3500's shape-1 signature,
    reached through the map-key path. So the arm is load-bearing here and a
    revert reds this class.
    """

    def test_two_composite_keys_project_hashably(self, db):
        """id=1: two structured keys, each ``(frozenset, int)``.

        Cassandra's frozen-map key order (``mkey-a`` before ``mkey-b``) is the
        golden's; a Python ``dict`` preserves it on iteration, but the assertion
        is on the mapping, which is order-insensitive by construction.
        """
        value = _rows_by_id(db, "f_map_tuple_udt")[1].get("f_map_tuple_udt")
        assert value == {
            (kp_hashable("mkey-a", 21), 1): 210,
            (kp_hashable("mkey-b", 22), 2): 220,
        }

    def test_key_is_a_tuple_of_a_frozenset(self, db):
        """Exact container TYPES, not merely equal structures.

        A ``dict`` key that is a ``tuple`` whose first element is a
        ``frozenset`` is the observable signature of the ``Tuple`` arm having
        recursed via ``value_to_hashable_key`` instead of ``value_to_py``: the
        latter builds a ``tuple`` holding a ``dict``, which cannot be a key at
        all.
        """
        value = _rows_by_id(db, "f_map_tuple_udt")[3].get("f_map_tuple_udt")
        assert type(value) is dict
        [key] = list(value)
        assert type(key) is tuple
        assert type(key[0]) is frozenset
        assert type(key[1]) is int
        assert value[key] == 7

    def test_null_udt_field_inside_a_hashable_key(self, db):
        """id=2: ``None`` field values INSIDE a dict key — the ``Udt`` ``None`` arm.

        This is the ONLY place in the repository that executes
        ``value_to_hashable_key``'s ``Udt``-arm ``None => py.None()`` branch. The
        set columns' null fields travel ``udt_to_py``'s own ``None`` branch — a
        DIFFERENT function — so ``test_null_udt_fields`` above does not cover it.

        Both directions are pinned: a null ``rank`` and a null ``label``, in two
        keys that must stay DISTINCT (a projection that collapsed ``None`` onto a
        default would merge them and the dict would hold one entry).
        """
        value = _rows_by_id(db, "f_map_tuple_udt")[2].get("f_map_tuple_udt")
        assert value == {
            (kp_hashable("nullrank3", None), 1): 51,
            (kp_hashable(None, 5), 2): 52,
        }
        assert len(value) == 2, "the two null-bearing keys must not collapse"
        nulls = {
            field_value
            for key in value
            for field_name, field_value in key[0]
            if field_name in ("label", "rank")
        }
        assert None in nulls, (
            "no None reached a hashable key — the Udt arm's None branch did not "
            "execute, so this test would be covering nothing"
        )

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column, so it must be ``None``, not ``{}``."""
        assert _rows_by_id(db, "f_map_tuple_udt")[4].get("f_map_tuple_udt") is None


class TestFrozenMapWithNestedSetUdtKey:
    """``f_map_set_udt`` — ``frozen<map<frozen<set<frozen<key_part>>>, int>>``.

    THE COLUMN THAT COVERS ``value_to_hashable_key``'s ``Set`` ARM, by the same
    frozen-map route as the class above — see its docstring for why no set
    column can do this.

    The ``Set`` arm deliberately does NOT delegate to ``set_to_py``, whose UDT
    fallback returns a ``list``: a ``list`` cannot be a ``dict`` key, and that
    is precisely issue #3500's shape-2 crash. RED-VERIFIED: with this fixture
    and the pre-fix binding this column raises
    ``TypeError: unhashable type: 'list'``.
    """

    def test_nested_set_keys_project_to_nested_frozensets(self, db):
        """id=1: a two-element inner set and a one-element inner set, as keys."""
        value = _rows_by_id(db, "f_map_set_udt")[1].get("f_map_set_udt")
        assert value == {
            frozenset({kp_hashable("mset-a", 31), kp_hashable("mset-b", 32)}): 310,
            frozenset({kp_hashable("mset-c", 33)}): 330,
        }

    def test_key_is_a_frozenset_of_frozensets(self, db):
        """Exact container types: ``frozenset`` at BOTH levels, never a ``list``."""
        value = _rows_by_id(db, "f_map_set_udt")[3].get("f_map_set_udt")
        assert type(value) is dict
        [key] = list(value)
        assert type(key) is frozenset
        [inner] = list(key)
        assert type(inner) is frozenset
        assert value[key] == 7

    def test_null_and_empty_udt_fields_stay_distinct(self, db):
        """id=2: an all-null UDT key and an empty-string/zero one, both hashable.

        ``''`` is not ``None``: two keys, two entries. The all-null key also
        drives the ``Udt`` arm's ``None`` branch through the ``Set`` arm rather
        than the ``Tuple`` arm, so the branch is covered on both routes.
        """
        value = _rows_by_id(db, "f_map_set_udt")[2].get("f_map_set_udt")
        assert value == {
            frozenset({kp_hashable(None, None)}): 61,
            frozenset({kp_hashable("", 0)}): 62,
        }
        assert len(value) == 2

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "f_map_set_udt")[4].get("f_map_set_udt") is None


class TestSetElementFrozenMapWithUdtKeyHalf:
    """``s_map_udt_key`` — ``set<frozen<map<frozen<key_part>, int>>>``.

    THE COLUMN THAT COVERS ``contains_udt``'s MAP arm, KEY half. Read this
    before deleting it as redundant with the frozen-map classes above.

    ``contains_udt``'s Map arm is::

        Value::Map(pairs) => pairs.iter().any(|(k, v)| contains_udt(k) || contains_udt(v))

    and NOTHING in this fixture reached it before: the ``List``, ``Set`` and
    ``Tuple`` arms are exercised by the columns above, but a ``Map`` only ever
    appeared at the TOP of a column (``m_tuple_udt``, ``f_map_*``), where
    ``contains_udt`` is not consulted at all — ``set_to_py`` is the only caller,
    so the value it inspects is always a SET ELEMENT. A map therefore has to be
    INSIDE a set element to be seen, which is exactly this column's type.

    WHY A REGRESSION HERE WOULD BE SILENT, hence why the column is needed:
    ``value_to_hashable_key`` is TOTAL, so if the Map arm stopped seeing the
    nested UDT the element would still project HASHABLY and the ``frozenset``
    would build. No ``TypeError``, no crash — the column would simply come back
    as a ``frozenset`` of tuples where #804 requires a ``list`` of ``dict``s.
    That is a SHAPE regression, and ``test_takes_the_list_fallback_not_a_frozenset``
    below is what detects it.

    ONE HALF PER COLUMN, DELIBERATELY. ``||`` short-circuits: with a UDT in both
    the key and the value of the same map, a broken ``contains_udt(v)`` is
    invisible (``k`` answers ``true`` first and ``v`` is never consulted), and a
    failure could not say WHICH half broke. So this column puts the UDT in the
    KEY only (``int`` values) and :class:`TestSetElementFrozenMapWithUdtValueHalf`
    puts it in the VALUE only.

    RED-VERIFIED against this fixture: with ``contains_udt``'s Map arm reverted
    to ``pairs.iter().any(|(_, v)| contains_udt(v))`` — i.e. only the key half
    removed — this class reds and the value-half class stays green.
    """

    def test_multi_element_partition(self, db):
        """id=1: two frozen-map elements, the first with two entries.

        Element order is Cassandra's: a frozen map's element comparator compares
        the maps PAIRWISE, so ``{ka…, kb…}`` sorts before ``{kc…}`` on their
        first keys (golden cell paths ``…6b61…6b62…`` then ``…6b63…``) — it is
        not a raw byte compare of the serialized maps.

        The dict KEY is a ``frozenset`` because ``map_to_py`` projects every key
        through ``value_to_hashable_key``; the map values are plain ``int``.
        """
        row = _rows_by_id(db, "s_map_udt_key")[1]
        assert row.get("s_map_udt_key") == [
            {kp_hashable("ka", 1): 10, kp_hashable("kb", 2): 20},
            {kp_hashable("kc", 3): 30},
        ]

    def test_takes_the_list_fallback_not_a_frozenset(self, db):
        """THE assertion that reds on a Map-arm KEY-half revert.

        ``contains_udt`` true => ``set_to_py`` returns a ``list`` whose elements
        are converted with ``value_to_py`` (so each element is a ``dict``).
        ``contains_udt`` false => a ``frozenset`` of tuples, which is hashable
        and therefore raises nothing. Only the container TYPES distinguish them.
        """
        value = _rows_by_id(db, "s_map_udt_key")[1].get("s_map_udt_key")
        assert type(value) is list, (
            f"expected the set_to_py list fallback, got {type(value).__name__} — "
            "contains_udt's Map arm did not see the UDT in the map KEY"
        )
        assert type(value[0]) is dict
        [key] = list(value[1])
        assert type(key) is frozenset
        assert value[1][key] == 30

    def test_empty_string_field_in_the_map_key(self, db):
        """id=2: an EMPTY-string label and a populated one, in one element.

        The two keys must stay DISTINCT (a projection that collapsed ``''`` onto
        a default would merge them into one entry).
        """
        row = _rows_by_id(db, "s_map_udt_key")[2]
        assert row.get("s_map_udt_key") == [
            {kp_hashable("", 0): 1, kp_hashable("zz", 9): 2},
        ]
        assert len(row.get("s_map_udt_key")[0]) == 2

    def test_single_element_partition(self, db):
        """id=3: one element, one entry."""
        row = _rows_by_id(db, "s_map_udt_key")[3]
        assert row.get("s_map_udt_key") == [{kp_hashable("solo", 99): 42}]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column, so it must be ``None``, not ``[]``."""
        assert _rows_by_id(db, "s_map_udt_key")[4].get("s_map_udt_key") is None


class TestSetElementFrozenMapWithUdtValueHalf:
    """``s_map_udt_val`` — ``set<frozen<map<int, frozen<key_part>>>>``.

    THE COLUMN THAT COVERS ``contains_udt``'s MAP arm, VALUE half — the sibling
    of :class:`TestSetElementFrozenMapWithUdtKeyHalf`; see that docstring for
    why the arm was covered by nothing and why the two halves are separate
    columns rather than one map with a UDT on both sides.

    Here the map KEYS are ``int`` and the UDT is in the map VALUE, so
    ``contains_udt(k)`` answers ``false`` for every pair and only
    ``contains_udt(v)`` can put the column on the list path. RED-VERIFIED: with
    the Map arm reverted to ``pairs.iter().any(|(k, _)| contains_udt(k))`` this
    class reds and the key-half class stays green.
    """

    def test_multi_element_partition(self, db):
        """id=1: two frozen-map elements, the first with two entries.

        The map values are UDTs, so they arrive as ``udt_to_py`` ``dict``s (NOT
        the ``frozenset`` a hashable position would yield) — a map VALUE is not a
        hashable position.
        """
        row = _rows_by_id(db, "s_map_udt_val")[1]
        assert row.get("s_map_udt_val") == [
            {1: kp("va", 11), 2: kp("vb", 12)},
            {3: kp("vc", 13)},
        ]

    def test_takes_the_list_fallback_not_a_frozenset(self, db):
        """THE assertion that reds on a Map-arm VALUE-half revert.

        Same mechanism as the key-half class: the reverted form still projects
        hashably (``value_to_hashable_key``'s Map arm builds a tuple of
        ``(key, value)`` tuples), so the only observable difference is the
        container type.
        """
        value = _rows_by_id(db, "s_map_udt_val")[1].get("s_map_udt_val")
        assert type(value) is list, (
            f"expected the set_to_py list fallback, got {type(value).__name__} — "
            "contains_udt's Map arm did not see the UDT in the map VALUE"
        )
        assert type(value[0]) is dict
        [(key, val)] = list(value[1].items())
        assert type(key) is int
        assert type(val) is dict
        assert val == kp("vc", 13)

    def test_null_udt_fields_in_the_map_value(self, db):
        """id=2: a wholly-null UDT value beside an empty-string/zero one.

        ``''`` is not ``None``, and both survive as separate entries. These
        travel ``udt_to_py``'s own ``None`` branch (the map VALUE is projected
        with ``value_to_py``), not ``value_to_hashable_key``'s — the two are
        different functions and the frozen-map classes above cover the other one.
        """
        row = _rows_by_id(db, "s_map_udt_val")[2]
        assert row.get("s_map_udt_val") == [
            {1: kp(None, None), 2: kp("", 0)},
        ]

    def test_single_element_partition(self, db):
        """id=3: one element, one entry."""
        row = _rows_by_id(db, "s_map_udt_val")[3]
        assert row.get("s_map_udt_val") == [{42: kp("solo", 99)}]

    def test_absent_in_sparse_row(self, db):
        """id=4 never wrote this column."""
        assert _rows_by_id(db, "s_map_udt_val")[4].get("s_map_udt_val") is None


class TestSelectStarWholeRow:
    """``SELECT *`` over every partition — the shape a user actually runs.

    Before the fix this raised ``TypeError: unhashable type: 'dict'`` on the
    first partition, so NO row of this table was readable at all.
    """

    def test_select_star_returns_every_partition(self, db):
        """All four partitions decode, in Murmur3 token order 1, 2, 4, 3."""
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        ids = [row.get("id") for row in result.rows]
        assert ids == [1, 2, 4, 3], (
            "expected the golden's partition order (nb-1-big-Data.db.jsonl), got "
            f"{ids}"
        )

    def test_select_star_returns_every_column(self, db):
        """``SELECT *`` yields exactly the nine declared columns plus ``id``.

        Pinned so the ``is None`` assertions in the sparse-row test below cannot
        be satisfied by a column having been dropped from the projection
        (``Row.get`` answers ``None`` for an unknown column too).
        """
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        expected = sorted(
            [
                "id",
                "s_tuple_udt",
                "s_set_udt",
                "m_tuple_udt",
                "s_list_udt",
                "f_set_tuple_udt",
                "f_map_tuple_udt",
                "f_map_set_udt",
                "s_map_udt_key",
                "s_map_udt_val",
            ]
        )
        for row in result.rows:
            assert sorted(row.to_dict()) == expected

    def test_select_star_whole_row_values(self, db):
        """id=3's complete row — every column at once, exact values."""
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        rows = {row.get("id"): row for row in result.rows}
        row = rows[3]
        assert row.get("s_tuple_udt") == [(kp("solo", 99), 42)]
        assert row.get("s_set_udt") == [[kp("solo", 99)]]
        assert row.get("s_list_udt") == [[kp("solo", 99)]]
        assert row.get("f_set_tuple_udt") == [(kp("solo", 99), 42)]
        assert row.get("m_tuple_udt") == {
            tuple_udt_int_serialized("solo", 99, 42): 7
        }
        assert row.get("f_map_tuple_udt") == {(kp_hashable("solo", 99), 42): 7}
        assert row.get("f_map_set_udt") == {
            frozenset({kp_hashable("solo", 99)}): 7
        }
        assert row.get("s_map_udt_key") == [{kp_hashable("solo", 99): 42}]
        assert row.get("s_map_udt_val") == [{42: kp("solo", 99)}]

    def test_select_star_sparse_row_values(self, db):
        """id=4: one populated column, EIGHT absent ones, in one ``SELECT *``."""
        result = db.execute(f"SELECT * FROM {KEYSPACE}.{TABLE}")
        rows = {row.get("id"): row for row in result.rows}
        row = rows[4]
        assert row.get("s_tuple_udt") == [(kp("partial", 4), 4)]
        for absent in (
            "s_set_udt",
            "s_list_udt",
            "f_set_tuple_udt",
            "m_tuple_udt",
            "f_map_tuple_udt",
            "f_map_set_udt",
            "s_map_udt_key",
            "s_map_udt_val",
        ):
            assert row.get(absent) is None, f"{absent} should be absent for id=4"


class TestFixtureResolutionContract:
    """The resolver itself (#3220) — the guard that stops this file passing vacuously.

    Every test above depends on the ``db`` fixture having found the RIGHT corpus
    root. On this fleet ``CQLITE_DATASETS_ROOT=/data/datasets``, whose
    ``sstables/`` does NOT contain ``test_nested_udt_keys`` — so a conftest-style
    single-root resolution would skip this entire file green and nobody would
    know. These cases pin the two properties that make that impossible.
    """

    def test_selection_is_by_evidence_not_by_root_order(self):
        """The chosen root must be one that actually holds the table.

        WEAK BY ITSELF, and kept only as a live-environment smoke check: it
        asserts a property ("the chosen root holds the table") that is true
        under ANY selection rule, so it exercises order-independence only when
        the environment happens to supply a first root that lacks the fixture.
        The deterministic case is the next test.
        """
        chosen = _sstables_root_for_table(KEYSPACE, TABLE)
        assert _table_has_data(chosen, KEYSPACE, TABLE), (
            f"resolver returned {chosen}, which does not carry {KEYSPACE}.{TABLE}"
        )
        assert chosen in _sstables_root_candidates()

    def test_first_searched_root_without_a_data_db_loses_to_the_checkout(
        self, tmp_path, monkeypatch
    ):
        """A DECOY env root, searched FIRST, must still lose to the checkout.

        Deterministic, environment-independent: the decoy is constructed here
        with the keyspace dir AND a plausible ``<table>-<id>/`` dir but no
        ``*-Data.db``, and ``CQLITE_DATASETS_ROOT`` points at it, so it is
        candidate ZERO. An env-first resolver — the #3104 shape — returns the
        decoy; an evidence-first one returns the checkout.

        This is the case the test above cannot make: on this fleet the real
        ``CQLITE_DATASETS_ROOT`` merely LACKS the keyspace, which the weaker
        assertion cannot distinguish from a correct rule.
        """
        decoy = tmp_path / "decoy"
        (decoy / "sstables" / KEYSPACE / f"{TABLE}-0badc0de").mkdir(parents=True)
        monkeypatch.setenv("CQLITE_DATASETS_ROOT", str(decoy))

        candidates = _sstables_root_candidates()
        assert candidates[0] == decoy / "sstables", (
            "the decoy must be searched FIRST or this test proves nothing about "
            f"ordering; candidates were {candidates}"
        )
        checkout = _workspace_root() / "test-data" / "datasets" / "sstables"
        assert _sstables_root_for_table(KEYSPACE, TABLE) == checkout

    def test_keyspace_present_but_table_absent_is_not_a_match(self, tmp_path):
        """A root with the keyspace dir but no table dir must not qualify."""
        (tmp_path / KEYSPACE).mkdir()
        assert _table_has_data(tmp_path, KEYSPACE, TABLE) is False

    def test_table_dir_without_a_data_db_is_not_a_match(self, tmp_path):
        """Presence is judged by a real ``*-Data.db``, never by a directory.

        This repo commits JSONL sidecars for fixtures whose binaries are
        gitignored, so a ``<table>-<uuid>/`` dir can exist with no SSTable in it
        — the exact shape that would otherwise be mistaken for a usable corpus.
        """
        table_dir = tmp_path / KEYSPACE / f"{TABLE}-cafebabe"
        table_dir.mkdir(parents=True)
        (table_dir / "nb-1-big-Data.db.jsonl").write_text("{}\n", encoding="utf-8")
        assert _table_has_data(tmp_path, KEYSPACE, TABLE) is False
        (table_dir / "nb-1-big-Data.db").write_bytes(b"\x00")
        assert _table_has_data(tmp_path, KEYSPACE, TABLE) is True

    def test_unresolvable_table_fails_closed_naming_every_root(self):
        """An unresolvable table RAISES and names every root searched.

        Never ``pytest.skip``: this fixture is git-committed, so "not found" is a
        broken checkout or a broken resolver, and a skip here would be a green
        report about a test that never ran.
        """
        with pytest.raises(AssertionError) as excinfo:
            _sstables_root_for_table(KEYSPACE, "no_such_table_3500")
        message = str(excinfo.value)
        for root in _sstables_root_candidates():
            assert str(root) in message, f"diagnostic omits candidate root {root}"
        assert "must never be skipped" in message

    def test_absolute_but_unreadable_schemas_root_fails_closed(
        self, tmp_path, monkeypatch
    ):
        """An absolute ``CQLITE_SCHEMAS_ROOT`` that is not a directory FAILS.

        It used to fall back silently to the checkout, so an operator pointing
        at a typo'd path got a green run against a schemas root they never
        named. Both this and the relative-path refusal name the offending value.
        """
        missing = tmp_path / "no_such_schemas_root"
        monkeypatch.setenv("CQLITE_SCHEMAS_ROOT", str(missing))
        with pytest.raises(BaseException) as excinfo:
            _schemas_root()
        assert str(missing) in str(excinfo.value)

    def test_relative_schemas_root_is_rejected_not_resolved(self, monkeypatch):
        """A RELATIVE override is refused: it would mean two different roots.

        The gate resolves a relative value against the repo root, pytest against
        the package dir — so it could certify one schemas root while the run
        read another (#3148).
        """
        monkeypatch.setenv("CQLITE_SCHEMAS_ROOT", "test-data/schemas")
        with pytest.raises(BaseException) as excinfo:
            _schemas_root()
        assert "ABSOLUTE" in str(excinfo.value)

    def test_unset_schemas_root_resolves_to_the_checkout(self, monkeypatch):
        """With no override, the committed checkout-relative root is used.

        The positive half of the two refusals above: without it, a bug that made
        ``_schemas_root`` raise unconditionally would still satisfy them.
        """
        monkeypatch.delenv("CQLITE_SCHEMAS_ROOT", raising=False)
        expected = _workspace_root() / "test-data" / "schemas"
        assert _schemas_root() == expected
        assert (expected / SCHEMA_FILE).is_file()

    def test_no_skip_anywhere_in_this_module(self):
        """Structural: this module must contain no skip of any kind.

        A skip added later would silently restore exactly the failure mode the
        rest of this class exists to prevent, and no behavioural test can see a
        skip that was never added.

        The detection lives in the module-level :func:`_skip_offenders`, which
        this test and its RED-verify BOTH call — see that function for the
        allowlist rationale and for the limit it does not cover.
        """
        offenders = _skip_offenders(Path(__file__).read_text(encoding="utf-8"))
        assert offenders == [], (
            f"skip-capable constructs found in {Path(__file__).name}: "
            f"{offenders} — this module is fail-closed by contract (#3220) and "
            "must never skip"
        )

    def test_the_no_skip_guard_can_actually_fail(self):
        """RED-verify the guard against planted skips, one per evasion shape.

        A structural assert over a file that legitimately contains none of the
        forbidden constructs passes whether or not its detection works, so the
        detection is exercised here against source that DOES contain them.
        Without this, ``test_no_skip_anywhere_in_this_module`` would be a
        vacuous green.

        This calls the SAME :func:`_skip_offenders` the guard calls. It used to
        hold a verbatim COPY of the predicate, which bound the anti-vacuity
        proof to the copy: gutting the real detector — the exact edit someone
        makes in order to land a skip — left this test green.

        The cases after the first three are the shapes a previous BLOCKLIST
        missed — each was found only after the one before it had been named. They
        are listed individually rather than as a loop so a failure names the
        shape that regressed. Both channels are allowlists now, so this list is
        a record of history, not a specification: a spelling absent from it
        still fails, which is the whole point of inverting them.
        """
        # The shapes the old blocklist DID catch.
        assert _skip_offenders("pytest.skip('nope')") == ["pytest.skip"]
        assert _skip_offenders("@pytest.mark.skip\ndef t():\n    pass\n") == [
            "pytest.mark.skip"
        ]
        assert _skip_offenders(
            "@pytest.mark.skipif(True, reason='x')\ndef t():\n    pass\n"
        ) == ["pytest.mark.skipif"]
        # The shapes it MISSED — each of these skipped green under the blocklist.
        assert _skip_offenders("pytest.importorskip('numpy')") == [
            "pytest.importorskip"
        ]
        assert _skip_offenders("@pytest.mark.xfail\ndef t():\n    pass\n") == [
            "pytest.mark.xfail"
        ]
        assert _skip_offenders("from pytest import skip as _skip\n_skip('x')\n") == [
            "from pytest import skip as _skip"
        ]
        assert _skip_offenders("import pytest as pt\npt.skip('x')\n") == [
            "import pytest as pt"
        ]
        # Evasion EIGHT, and the reason the import channel is now an allowlist
        # of one FORM: a star import binds skip/xfail/importorskip while naming
        # none of them, so no blocklist of names could ever have seen it, and
        # the calls it enables carry no ``pytest.`` prefix either.
        assert _skip_offenders("from pytest import *\nskip('x')\n") == [
            "from pytest import *"
        ]
        # The same inversion covers the unaliased from-import and the submodule
        # and private-path routes, none of which needed to be thought of
        # individually — they are simply not the one permitted form.
        assert _skip_offenders("from pytest import skip\nskip('x')\n") == [
            "from pytest import skip"
        ]
        assert _skip_offenders("import pytest.mark\n") == ["import pytest.mark"]
        assert _skip_offenders("from _pytest.outcomes import skip\nskip('x')\n") == [
            "from _pytest.outcomes import skip"
        ]
        # A from-import of a HARMLESS name is an offender too: what is judged is
        # the FORM, not the name, which is exactly what makes the channel closed.
        assert _skip_offenders("from pytest import fixture\n") == [
            "from pytest import fixture"
        ]
        # An alias that re-binds the same name is still not the permitted form.
        assert _skip_offenders("import pytest as pytest\n") == [
            "import pytest as pytest"
        ]
        # Non-pytest imports, including relative ones, are none of its business.
        assert _skip_offenders(
            "import os\nfrom pathlib import Path\nfrom . import helpers\n"
        ) == []
        # An UNKNOWN pytest attribute is an offender too: the allowlist is what
        # makes a construct nobody has invented yet fail closed.
        assert _skip_offenders("pytest.some_future_skipper()") == [
            "pytest.some_future_skipper"
        ]
        # ...and the APIs this module legitimately uses must NOT be offenders,
        # or the guard would red on correct input and get waived.
        assert _skip_offenders(
            "import pytest\n"
            "@pytest.fixture\ndef f():\n    pass\n"
            "def t():\n"
            "    with pytest.raises(AssertionError):\n        pass\n"
            "    pytest.fail('x')\n"
            "    assert 1 == pytest.approx(1)\n"
        ) == []
        # Prose mentioning them is NOT a violation — the point of using the AST.
        assert _skip_offenders('"""never pytest.skip; no pytest.mark.skipif."""') == []
